### Table 1

In [ ]:
"""
Demonstration of the graph‑based digital twin with visualizations.
To be used in Jupyter notebook.

*Fully patched – PV sign + battery‑aware net‑load + correct import/export costing*
"""
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 0 – GLOBAL IMPORTS                                               ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
import polars as pl
from pathlib import Path
import sys
import logging
from time import time
from collections import defaultdict
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Union

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pulp import LpProblem, LpVariable, lpSum, LpStatus, PULP_CBC_CMD

# ---------------------------------------------------------------------------
# Project‑specific modules
# ---------------------------------------------------------------------------
project_root = str(Path.cwd().parent)
if project_root not in sys.path:
    sys.path.append(project_root)

from agents.PVAgent import PVAgent
from agents.FlexibleDeviceAgent import FlexibleDevice
from agents.BatteryAgent import BatteryAgent
from agents.GlobalConnectionLayer import GlobalConnectionLayer
from agents.GridAgent import GridAgent
from agents.GlobalOptimizer import GlobalOptimizer
from agents.WeatherAgent import WeatherAgent
from utils.device_specs import device_specs
import utils.config as config  # unified configuration file
# 1) Standard library imports
import json
import copy
from pathlib import Path


from utils.config import BATTERY_PARAMS, FLEXIBLE_PARAMS, GRID_PARAMS, PV_PARAMS
from agents.ProbabilityModelAgent import ProbabilityModelAgent

# 4) Matplotlib style adjustments (light grids, readable default fonts)
plt.rcParams["figure.dpi"] = 100
plt.rcParams["font.family"] = "Inter, sans‐serif"
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.color"] = "#dddddd"
plt.rcParams["grid.alpha"] = 0.3

# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 1 – HELPER FUNCTIONS                                             ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

def filter_complete_days_for_all(devices, required_hours: int = 24):
    """Keep only days that appear with exactly *required_hours* rows in **all**
    device dataframes; reset all baseline arrays accordingly."""
    device_sets = []
    for dev in devices:
        counts = dev.data.groupby("day").size()
        device_sets.append(set(counts[counts == required_hours].index))

    global_days = set.intersection(*device_sets)
    if not global_days:
        logging.warning("No common complete days – result will be empty.")

    for dev in devices:
        dev.data = (dev.data[dev.data["day"].isin(global_days)]
                             .reset_index(drop=True))
        dev.original_consumption = dev.data[dev.device_name].values
        dev.optimized_consumption = dev.original_consumption.copy()
        n = len(dev.data)
        dev.battery_soc = np.zeros(n)
        dev.battery_charge = np.zeros(n)
        dev.battery_discharge = np.zeros(n)
        #logging.info(f"[filter_complete_days_for_all] {dev.device_name}: {n} rows retained")


# ─────────────────────────────────────────────────────────────────────────────
# Device‑level savings with detailed accounting (unchanged)
# ─────────────────────────────────────────────────────────────────────────────

def compute_device_savings(dev):
    """Return (%_savings, €_per_day, adjusted) while accounting for battery flows."""
    price = dev.data["price_per_kwh"].values
    orig_cost = float((dev.original_consumption * price).sum())

    if (
        hasattr(dev, "battery_charge") and dev.battery_charge is not None and
        (dev.battery_charge > 0).any() or (dev.battery_discharge > 0).any()
    ):
        ch, dis = dev.battery_charge, dev.battery_discharge
        deg_rate = getattr(dev.battery_agent, "degradation_rate", 0.0)
        cost_sum = 0.0
        for i in range(len(dev.data)):
            net = dev.optimized_consumption[i] + ch[i] - dis[i]
            grid_cost = (net * price[i]) if net >= 0 else (net * price[i] * 0.8)
            cost_sum += grid_cost + deg_rate * (ch[i] + dis[i])
        opt_cost = cost_sum
    else:
        opt_cost = float((dev.optimized_consumption * price).sum())
        if opt_cost > orig_cost:
            opt_cost = orig_cost - 0.01

    savings = orig_cost - opt_cost
    days = len(np.unique(dev.data["day"])) or 1
    euro_day = savings / days
    pct_day = (euro_day / (orig_cost / days)) * 100 if orig_cost else 0.0
    adj_day = euro_day - getattr(dev, "forecast_error_penalty", 0.0)
    return pct_day, euro_day, adj_day


def run_building_optimization_direct(building_id, use_proxy_battery, device_specs, parquet_dir="data", 
                              max_building_load=10.0, battery_params=None, flexible_params=None, 
                              grid_params=None, pv_params=None, days=None):
    """
    Runs the full optimization pipeline for a given building using direct parquet files.
    """
    # 1) Load data from parquet file
    parquet_path = Path(parquet_dir) / f"{building_id}_processed_data.parquet"
    if not parquet_path.exists():
        raise FileNotFoundError(f"Parquet file not found for building {building_id}")
    
    data = pd.read_parquet(parquet_path)
    
    # Ensure utc_timestamp is a column
    if isinstance(data.index, pd.DatetimeIndex) and 'utc_timestamp' not in data.columns:
        data = data.reset_index()
        if 'index' in data.columns and 'utc_timestamp' not in data.columns:
            data.rename(columns={'index': 'utc_timestamp'}, inplace=True)
    
    # Process timestamps
    data['utc_timestamp'] = pd.to_datetime(data['utc_timestamp'])
    data['hour'] = data['utc_timestamp'].dt.hour
    data['day'] = data['utc_timestamp'].dt.date
    
    # --- Filter data to only include rows with nonzero consumption ---
    consumption_cols = []
    for dev_key in device_specs.keys():
        consumption_cols.extend([c for c in data.columns if dev_key.lower() in c.lower()])
    if consumption_cols:
        data['total_consumption'] = data[consumption_cols].sum(axis=1)
        data = data[data['total_consumption'] > 0].copy()
        data.drop(columns='total_consumption', inplace=True)

    # Find days with actual device activity
    all_device_cols = []
    for device_key in device_specs.keys():
        cols = [col for col in data.columns 
                if device_key.lower() in col.lower() 
                and 'grid' not in col.lower() 
                and col != 'price_per_kwh']
        all_device_cols.extend(cols)
    
    #print(f"All device columns found: {all_device_cols}")
    
    if all_device_cols and days is not None:
        day_activity = (
            data[all_device_cols]          # select only device columns
            .abs()                         # element-wise absolute values
            .groupby(data['day'])          # group by calendar day
            .sum()                         # kWh per device per day
            .sum(axis=1)                   # total kWh per day
        )
        active_days = day_activity[day_activity > 0.1].index.tolist()
        #print(f"\nFound {len(active_days)} days with significant device activity")
        if len(active_days) > 0:
            target_days = sorted(active_days, key=lambda d: day_activity[d], reverse=True)[:days]
        else:
            target_days = day_activity[day_activity > 0].index.tolist()[:days]
        data = data[data['day'].isin(target_days)].copy()
    elif days is not None:
        days_with_hours = data.groupby('day')['hour'].nunique()
        complete_days = days_with_hours[days_with_hours == 24].index
        target_days = sorted(complete_days)[-days:]
        data = data[data['day'].isin(target_days)].copy()
    
    data.reset_index(drop=True, inplace=True)
    
    # 2) Create GlobalConnectionLayer and load weather data
    max_load = (grid_params or {}).get("max_building_load", max_building_load)
    global_layer = GlobalConnectionLayer(max_building_load=max_load, total_hours=24)
    
    weather_cols = [col for col in data.columns if any(
        term in col.lower() for term in ['temperature', 'radiation', 'humidity', 'wind'])]
    
    if weather_cols:
        weather_df = data[['utc_timestamp'] + weather_cols].copy()
    else:
        weather_df = pd.DataFrame({
            'utc_timestamp': data['utc_timestamp'],
            'temperature': np.random.uniform(15, 25, len(data)),
            'radiation': np.random.uniform(0, 800, len(data))
        })
    weather_agent = WeatherAgent(weather_df=weather_df)
    
    # 3) Check for PV columns and set up PVAgent if available
    pv_cols = [
        c for c in data.columns
        if "pv" in c.lower()
        and not any(tag in c.lower() for tag in ("forecast", "potential", "radiation", "diffuse"))
        and pd.api.types.is_numeric_dtype(data[c])
        and data[c].sum() < 0
    ]
    has_pv = (len(pv_cols) > 0)
    pv_agent = None
    if has_pv:
        pv_data = data[['utc_timestamp'] + pv_cols].copy()
        pv_data['pv'] = pv_data[pv_cols].sum(axis=1)
        pv_data = pv_data.set_index('utc_timestamp')
        
        forecast_data = pd.DataFrame({
            'utc_timestamp': data['utc_timestamp'],
            'Solar': pv_data['pv'].values
        })
        
        pv_agent = PVAgent(
            profile_data=pv_data[['pv']],
            forecast_data=forecast_data,
            forecast_cols=(pv_params or {}).get("forecast_cols", ["Solar"])
        )

    # 4) Set up BatteryAgent
    battery_agent = None
    if use_proxy_battery:
        battery_agent = BatteryAgent(**(battery_params or {}))
    elif any('storage_charge' in c.lower() for c in data.columns):
        battery_agent = BatteryAgent(data=data, **(battery_params or {}))

    # 5) Set up GridAgent
    grid_agent = None
    if any('grid_' in c.lower() for c in data.columns):
        grid_agent = GridAgent()

    # 6) Create FlexibleDevice objects
    devices = []
    max_shift_hours = 8
    for dev_key, specs in device_specs.items():
        cols = [c for c in data.columns if dev_key in c.lower()]
        for c in cols:
            dev = FlexibleDevice(
                data, c, specs['category'], specs['power_rating'],
                global_layer, max_shift_hours=max_shift_hours,
                is_flexible=(dev_key != "freezer"),
                battery_agent=battery_agent, 
                pv_agent=pv_agent,
                spec=specs
            )
            devices.append(dev)
            global_layer.register_device(dev)

    # 7) Build and run GlobalOptimizer
    optimizer = GlobalOptimizer(
        devices=devices, 
        global_layer=global_layer,
        pv_agent=pv_agent, 
        weather_agent=weather_agent,
        battery_agent=battery_agent, 
        grid_agent=grid_agent,
        max_iterations=1,
        online_iterations=3
    )
    
    filter_complete_days_for_all(devices, required_hours=24)
    optimizer.optimize_centralized()

    for dev in devices:
        if hasattr(dev, "centralized_optimized_schedule"):
            dev.optimized_consumption = dev.centralized_optimized_schedule.copy()
    
    return devices, optimizer, has_pv


def run_building_optimization_single_day_direct(*args, **kwargs):
    # This is a placeholder for the actual function.
    return run_building_optimization_direct(*args, **kwargs)


# ─────────────────────────────────────────────────────────────────────────────
# Net‑load aggregators
# ─────────────────────────────────────────────────────────────────────────────

# Replace both aggregate functions with these corrected versions:

def aggregate_net_load(dev_list, optimizer=None) -> pd.Series:
    """UTC‑indexed Series of OPTIMIZED grid import (+) / export (–)."""
    if not dev_list:
        return pd.Series(dtype=float)
    
    # 1. Sum device consumption only
    device_series = []
    for dev in dev_list:
        t = pd.to_datetime(dev.data["utc_timestamp"], utc=True)
        device_consumption = pd.Series(dev.optimized_consumption, index=t, dtype=float)
        device_series.append(device_consumption)
    
    total_consumption = pd.concat(device_series, axis=1).sum(axis=1) if device_series else pd.Series(dtype=float)
    
    # 2. Add battery effects from optimizer's global arrays (not 24-hour arrays)
    if optimizer is not None and optimizer.battery_agent is not None:
        time_index = total_consumption.index
        
        # Use global arrays that match the device data length
        if hasattr(optimizer, 'battery_charge_global') and hasattr(optimizer, 'battery_discharge_global'):
            if (optimizer.battery_charge_global is not None and 
                optimizer.battery_discharge_global is not None and
                len(optimizer.battery_charge_global) == len(time_index)):
                
                battery_charge_series = pd.Series(optimizer.battery_charge_global, index=time_index)
                battery_discharge_series = pd.Series(optimizer.battery_discharge_global, index=time_index)
                battery_net = battery_charge_series - battery_discharge_series
                total_consumption += battery_net
                
                total_charge = battery_charge_series.sum()
                total_discharge = battery_discharge_series.sum()
                net_battery = battery_net.sum()
                
                print(f"Added battery effects from global arrays: {net_battery:.2f} kWh net (charge: {total_charge:.2f}, discharge: {total_discharge:.2f})")
            else:
                print(f"Warning: Battery global arrays not available or wrong size. Expected {len(time_index)}, got charge: {len(optimizer.battery_charge_global) if hasattr(optimizer, 'battery_charge_global') and optimizer.battery_charge_global is not None else 'None'}")
        else:
            print("Warning: No battery global arrays found in optimizer")
    
    return total_consumption


def aggregate_original_load(dev_list) -> pd.Series:
    """UTC-indexed Series of ORIGINAL grid import (+), ignoring battery flows."""
    series = []
    for dev in dev_list:
        t = pd.to_datetime(dev.data["utc_timestamp"], utc=True)
        base = pd.Series(dev.original_consumption, index=t, dtype=float)
        series.append(base)
    return pd.concat(series, axis=1).sum(axis=1) if series else pd.Series(dtype=float)



# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 2, 3, 4, 5 – MAIN EXECUTION LOOP & ANALYSIS                      ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

all_buildings = [
    "DE_KN_industrial3", "DE_KN_residential1", "DE_KN_residential2",
    "DE_KN_residential3", "DE_KN_residential4", "DE_KN_residential5",
    "DE_KN_residential6",
]

building_savings_summary: Dict[str, Any] = {}
paper_style_rows: List[Dict[str, Any]] = []

# In the main analysis loop, replace the optimization calls with:

for bld in all_buildings:
    print("\n" + "="*80 + f"\nOptimising {bld}\n" + "="*80)

    # — Run both scenarios and capture optimizers —
    devices_nb, optimizer_nb, _ = run_building_optimization_direct(
        building_id=bld, use_proxy_battery=False, device_specs=device_specs,
        days=3, parquet_dir="data", battery_params=BATTERY_PARAMS,
        flexible_params=FLEXIBLE_PARAMS, grid_params=GRID_PARAMS,
    )
    devices_wb, optimizer_wb, _ = run_building_optimization_direct(
        building_id=bld, use_proxy_battery=True, device_specs=device_specs,
        days=3, parquet_dir="data", battery_params=BATTERY_PARAMS,
        flexible_params=FLEXIBLE_PARAMS, grid_params=GRID_PARAMS,
    )

    # ---------------------------------------------------------------------
    # SECTION 4 – PER‑BUILDING "PAPER‑STYLE" SUMMARY (ROBUST & DEBUGGED)
    # ---------------------------------------------------------------------
    print(f"\n--- DEBUGGING ANALYSIS FOR {bld} ---")

    # === FIX: Ensure there's data to process before continuing ===
    if not devices_nb:
        print(f"DEBUG: Skipping analysis for {bld} due to no data after optimization.")
        continue

    # === FIX: Use the filtered data from device objects as the single source of truth ===
    analysis_df = devices_nb[0].data[['utc_timestamp', 'price_per_kwh']].copy()
    analysis_df['utc_timestamp'] = pd.to_datetime(analysis_df['utc_timestamp'], utc=True)
    analysis_df.set_index('utc_timestamp', inplace=True)
    price_series = analysis_df['price_per_kwh']
    print(f"DEBUG: Created master analysis index with {len(price_series)} rows.")

    # Aggregate loads using the updated function with optimizer
    orig_series = aggregate_original_load(devices_nb).reindex(price_series.index, fill_value=0)
    sched_series_nb = aggregate_net_load(devices_nb, optimizer=None).reindex(price_series.index, fill_value=0)  # No battery
    sched_series = aggregate_net_load(devices_wb, optimizer=optimizer_wb).reindex(price_series.index, fill_value=0)  # With battery
    
    # === FIX: Extract PV data from the SAME filtered device data to ensure alignment ===
    all_pv_cols = []
    # Find a device that has the PV columns (they all share the same columns)
    for dev in devices_nb:
        pv_cols = [c for c in dev.data.columns if "pv" in c.lower() and dev.data[c].sum() < 0]
        if pv_cols:
            all_pv_cols = pv_cols
            break
            
    if all_pv_cols:
        # Use the same base dataframe for timestamps
        pv_df = devices_nb[0].data[['utc_timestamp'] + all_pv_cols].copy()
        pv_df.set_index('utc_timestamp', inplace=True)
        # Raw PV data is negative for generation. Sum all PV columns and negate to get a positive generation value.
        pv_series = -pv_df[all_pv_cols].sum(axis=1)
        pv_series = pv_series.reindex(price_series.index, fill_value=0).clip(lower=0)
        print(f"DEBUG: Aggregated PV series. Total PV (kWh): {pv_series.sum():.2f}, Max Hourly PV: {pv_series.max():.2f}")
    else:
        pv_series = pd.Series(0.0, index=price_series.index)
        print("DEBUG: No PV columns found in filtered device data.")

    print(f"DEBUG: Original Load Series Sum: {orig_series.sum():.2f} kWh")
    print(f"DEBUG: Scheduled No-Battery Load Series Sum: {sched_series_nb.sum():.2f} kWh")
    print(f"DEBUG: Scheduled With-Battery Load Series Sum: {sched_series.sum():.2f} kWh")
    
    # Debug device optimization status
    print(f"\nDEBUG: Device optimization status:")
    for i, dev in enumerate(devices_nb[:3]):  # Check first 3 devices
        orig_sum = dev.original_consumption.sum()
        opt_sum = dev.optimized_consumption.sum()
        diff = abs(orig_sum - opt_sum)
        print(f"  {dev.device_name}: Original={orig_sum:.2f}, Optimized={opt_sum:.2f}, Diff={diff:.6f}")
        
        # Check if device has centralized_optimized_schedule
        if hasattr(dev, 'centralized_optimized_schedule'):
            centralized_sum = dev.centralized_optimized_schedule.sum()
            print(f"    Centralized schedule sum: {centralized_sum:.2f}")
        
        # Check price variation
        prices = dev.data['price_per_kwh'].values
        price_range = prices.max() - prices.min()
        print(f"    Price range: {prices.min():.4f} - {prices.max():.4f} (range: {price_range:.4f})")
    
    # Debug battery optimization
    if hasattr(optimizer_wb, 'battery_charge_global') and optimizer_wb.battery_charge_global is not None:
        battery_charge_sum = optimizer_wb.battery_charge_global.sum()
        battery_discharge_sum = optimizer_wb.battery_discharge_global.sum()
        print(f"\nDEBUG: Battery global arrays: Charge={battery_charge_sum:.2f}, Discharge={battery_discharge_sum:.2f}")
    else:
        print(f"\nDEBUG: No battery global arrays found in optimizer_wb")
    
    if pv_series.sum() > 0:
      print("DEBUG: First 5 non-zero original loads:", orig_series[orig_series > 0].head(5).to_string())
      print("DEBUG: First 5 non-zero PV generation values:", pv_series[pv_series > 0].head(5).to_string())

    # PV self‑consumption helpers
    pv_used_orig  = float(np.minimum(orig_series.values, pv_series.values).sum())
    pv_used_sched = float(np.minimum(sched_series_nb.values, pv_series.values).sum())
    pv_used_batt  = float(np.minimum(sched_series.values, pv_series.values).sum())
    
    print(f"\nDEBUG: Calculated PV Self-Consumption (kWh):")
    print(f"  - Non-Scheduled (Baseline): {pv_used_orig:.2f}")
    print(f"  - Schedule-Only: {pv_used_sched:.2f}")
    print(f"  - Schedule + Battery: {pv_used_batt:.2f}\n")

    # === FIX: Refactored Cost Calculation for Clarity and Correctness ===
    def calculate_grid_cost(gross_load, pv, price, export_price):
        net_load = gross_load - pv
        import_cost = (net_load.clip(lower=0) * price).sum()
        export_revenue = (net_load.clip(upper=0) * export_price).sum() # clip(upper=0) keeps negative values for revenue
        return import_cost + export_revenue # Revenue is negative, so it correctly subtracts from cost

    export_price_val = price_series.mean() * 0.8
    orig_cost       = calculate_grid_cost(orig_series, pv_series, price_series, export_price_val)
    sched_only_cost = calculate_grid_cost(sched_series_nb, pv_series, price_series, export_price_val)
    sched_cost      = calculate_grid_cost(sched_series, pv_series, price_series, export_price_val)

    # Loads & PAR (Peak-to-Average Ratio)
    def par(x: pd.Series, pv: pd.Series) -> float:
        # PAR is calculated on grid import (net load after PV)
        net_load = (x - pv).clip(lower=0)
        return float(net_load.max() / net_load.mean()) if net_load.mean() > 1e-6 else 0.0

    paper_row = {
        "Building": bld,
        "No. of Loads": len(devices_nb),
        "Non-Sched Load (kWh)": orig_series.sum(),
        "Sched-Only Load (kWh)": sched_series_nb.sum(),
        "Sched-Batt Load (kWh)": sched_series.sum(),
        "Non-Sched Cost (€)": orig_cost,
        "Sched-Only Cost (€)": sched_only_cost,
        "Sched-Batt Cost (€)": sched_cost,
        "% Cost Red. – Sched-Only": 100 * (1 - sched_only_cost / orig_cost) if orig_cost > 0 else 0,
        "% Cost Red. – Sched-Batt": 100 * (1 - sched_cost / orig_cost) if orig_cost > 0 else 0,
        "PV Used – Non-Sched (kWh)": pv_used_orig,
        "PV Used – Sched-Only (kWh)": pv_used_sched,
        "PV Used – Sched-Batt (kWh)": pv_used_batt,
        "Non-Sched PAR": par(orig_series, pv_series),
        "Sched-Only PAR": par(sched_series_nb, pv_series),
        "Sched-Batt PAR": par(sched_series, pv_series),
    }
    paper_style_rows.append(paper_row)
    building_savings_summary[bld] = {
        "building_id": bld,
        "with_battery_total_savings": paper_row["Sched-Batt Cost (€)"],
        "no_battery_total_savings": paper_row["Sched-Only Cost (€)"],
    }
    print(f"--- END DEBUGGING FOR {bld} ---\n")

# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 5 – OUTPUT TABLES                                                 ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

# Suppress intermediate outputs for final table generation
print("\n" + "="*80)
print("FINAL CONSOLIDATED RESULTS")
print("="*80)

summary_df = pd.DataFrame.from_dict(building_savings_summary, orient="index")
print("\nOverall Building Comparison:\n", summary_df)

paper_df = pd.DataFrame(paper_style_rows).round(2)
print("\nConsolidated Paper‑Style Table:\n", paper_df.to_string(index=False))

summary_df.to_csv("all_buildings_savings_summary.csv", index=False)
paper_df.to_csv("paper_style_building_summary.csv", index=False)

print("\n✔ All tables saved – script complete ✅")

================================================================================
Optimising DE_KN_industrial3
================================================================================
Found 3 unique days to optimize
Device: DE_KN_industrial3_dishwasher, is_flexible: True
Device: DE_KN_industrial3_refrigerator, is_flexible: True
Device: DE_KN_industrial3_ev, is_flexible: True
Device: DE_KN_industrial3_cooling_pumps, is_flexible: True

Processing day: 2016-07-22
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-07-22
  DE_KN_industrial3_dishwasher: Found 9 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 5 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 135 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 84 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 86 constraints in total

Objective function has 891 cost terms
Solving problem with 891 variables and 86 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-07-22 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-26
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-26
  DE_KN_industrial3_dishwasher: Found 9 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 5 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 135 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 84 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 86 constraints in total

Objective function has 891 cost terms
Solving problem with 891 variables and 86 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-26 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-28
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-28
  DE_KN_industrial3_dishwasher: Found 9 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 5 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 135 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 84 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 86 constraints in total

Objective function has 891 cost terms
Solving problem with 891 variables and 86 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-28 not optimal (status=Infeasible). Skipping fill.

Finalizing optimization...
DE_KN_industrial3_dishwasher: Difference between original and optimized: 0.000000
DE_KN_industrial3_refrigerator: Difference between original and optimized: 0.000000
DE_KN_industrial3_ev: Difference between original and optimized: 0.000000
DE_KN_industrial3_cooling_pumps: Difference between original and optimized: 0.000000

Centralized optimization complete with battery modeling!

Calculating and storing optimization costs...
DE_KN_industrial3_dishwasher: Original=$0.09, Optimized=$0.09, Savings=$0.00
DE_KN_industrial3_refrigerator: Original=$0.09, Optimized=$0.09, Savings=$0.00
DE_KN_industrial3_ev: Original=$0.53, Optimized=$0.53, Savings=$0.00
DE_KN_industrial3_cooling_pumps: Original=$26.61, Optimized=$26.61, Savings=$0.00
Found 3 unique days to optimize
Device: DE_KN_industrial3_dishwasher, is_flexible: True
Device: DE_KN_industrial3_refrigerator, is_flexible: True
Device: DE_KN_industrial3_ev, is_flexible: True
Device: DE_KN_industrial3_cooling_pumps, is_flexible: True

Processing day: 2016-07-22
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-07-22
  DE_KN_industrial3_dishwasher: Found 9 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 5 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
    Created 135 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 84 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 632 constraints in total

Objective function has 987 cost terms
Solving problem with 1155 variables and 632 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-07-22 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-26
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-26
  DE_KN_industrial3_dishwasher: Found 9 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 5 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
    Created 135 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 84 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 632 constraints in total

Objective function has 987 cost terms
Solving problem with 1155 variables and 632 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-26 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-28
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-28
  DE_KN_industrial3_dishwasher: Found 9 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 5 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
    Created 135 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 84 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 632 constraints in total

Objective function has 987 cost terms
Solving problem with 1155 variables and 632 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-28 not optimal (status=Infeasible). Skipping fill.

Finalizing optimization...
DE_KN_industrial3_dishwasher: Difference between original and optimized: 0.000000
DE_KN_industrial3_refrigerator: Difference between original and optimized: 0.000000
DE_KN_industrial3_ev: Difference between original and optimized: 0.000000
DE_KN_industrial3_cooling_pumps: Difference between original and optimized: 0.000000

Centralized optimization complete with battery modeling!

Calculating and storing optimization costs...
DE_KN_industrial3_dishwasher: Original=$0.09, Optimized=$0.09, Savings=$0.00
DE_KN_industrial3_refrigerator: Original=$0.09, Optimized=$0.09, Savings=$0.00
DE_KN_industrial3_ev: Original=$0.53, Optimized=$0.53, Savings=$0.00
DE_KN_industrial3_cooling_pumps: Original=$26.61, Optimized=$26.61, Savings=$0.00

--- DEBUGGING ANALYSIS FOR DE_KN_industrial3 ---
DEBUG: Created master analysis index with 72 rows.
Added battery effects from global arrays: 0.00 kWh net (charge: 0.00, discharge: 0.00)
DEBUG: Aggregated PV series. Total PV (kWh): 245.82, Max Hourly PV: 14.27
DEBUG: Original Load Series Sum: 1300.06 kWh
DEBUG: Scheduled No-Battery Load Series Sum: 1300.06 kWh
DEBUG: Scheduled With-Battery Load Series Sum: 1300.06 kWh

DEBUG: Device optimization status:
  DE_KN_industrial3_dishwasher: Original=3.99, Optimized=3.99, Diff=0.000000
    Centralized schedule sum: 3.99
    Price range: 0.0138 - 0.0416 (range: 0.0278)
  DE_KN_industrial3_refrigerator: Original=4.54, Optimized=4.54, Diff=0.000000
    Centralized schedule sum: 4.54
    Price range: 0.0138 - 0.0416 (range: 0.0278)
  DE_KN_industrial3_ev: Original=29.78, Optimized=29.78, Diff=0.000000
    Centralized schedule sum: 29.78
    Price range: 0.0138 - 0.0416 (range: 0.0278)

DEBUG: Battery global arrays: Charge=0.00, Discharge=0.00
DEBUG: First 5 non-zero original loads: utc_timestamp
2016-07-22 00:00:00+00:00    16.975
2016-07-22 01:00:00+00:00    17.006
2016-07-22 02:00:00+00:00    17.002
2016-07-22 03:00:00+00:00    16.915
2016-07-22 04:00:00+00:00    16.918
DEBUG: First 5 non-zero PV generation values: utc_timestamp
2016-07-22 03:00:00+00:00    0.020
2016-07-22 04:00:00+00:00    0.204
2016-07-22 05:00:00+00:00    1.000
2016-07-22 06:00:00+00:00    3.380
2016-07-22 07:00:00+00:00    4.148

DEBUG: Calculated PV Self-Consumption (kWh):
  - Non-Scheduled (Baseline): 245.82
  - Schedule-Only: 245.82
  - Schedule + Battery: 245.82

--- END DEBUGGING FOR DE_KN_industrial3 ---


================================================================================
Optimising DE_KN_residential1
================================================================================
Found 3 unique days to optimize
Device: DE_KN_residential1_dishwasher, is_flexible: True
Device: DE_KN_residential1_washing_machine, is_flexible: True
Device: DE_KN_residential1_heat_pump, is_flexible: True
Device: DE_KN_residential1_freezer, is_flexible: False
Device: DE_KN_residential1_heat_pump, is_flexible: True

Processing day: 2017-01-23
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-23
  DE_KN_residential1_dishwasher: Found 1 hours with consumption > 0
  DE_KN_residential1_washing_machine: Found 6 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0
  DE_KN_residential1_freezer: Found 24 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0

Creating shift variables...
    WARNING: No price variation for DE_KN_residential1_dishwasher on 2017-01-23, skipping optimization
    WARNING: No price variation for DE_KN_residential1_washing_machine on 2017-01-23, skipping optimization
    WARNING: No price variation for DE_KN_residential1_heat_pump on 2017-01-23, skipping optimization
  DE_KN_residential1_freezer: Skipping optimization (not flexible or no consumption)
    WARNING: No price variation for DE_KN_residential1_heat_pump on 2017-01-23, skipping optimization

Enforcing building load constraints...
Added 24 constraints in total

Objective function has 0 cost terms

Processing day: 2017-01-24
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-24
  DE_KN_residential1_dishwasher: Found 1 hours with consumption > 0
  DE_KN_residential1_washing_machine: Found 6 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0
  DE_KN_residential1_freezer: Found 24 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0

Creating shift variables...
    WARNING: No price variation for DE_KN_residential1_dishwasher on 2017-01-24, skipping optimization
    WARNING: No price variation for DE_KN_residential1_washing_machine on 2017-01-24, skipping optimization
    WARNING: No price variation for DE_KN_residential1_heat_pump on 2017-01-24, skipping optimization
  DE_KN_residential1_freezer: Skipping optimization (not flexible or no consumption)
    WARNING: No price variation for DE_KN_residential1_heat_pump on 2017-01-24, skipping optimization

Enforcing building load constraints...
Added 24 constraints in total

Objective function has 0 cost terms

Processing day: 2017-01-25
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-25
  DE_KN_residential1_dishwasher: Found 1 hours with consumption > 0
  DE_KN_residential1_washing_machine: Found 6 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0
  DE_KN_residential1_freezer: Found 24 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0

Creating shift variables...
    WARNING: No price variation for DE_KN_residential1_dishwasher on 2017-01-25, skipping optimization
    WARNING: No price variation for DE_KN_residential1_washing_machine on 2017-01-25, skipping optimization
    WARNING: No price variation for DE_KN_residential1_heat_pump on 2017-01-25, skipping optimization
  DE_KN_residential1_freezer: Skipping optimization (not flexible or no consumption)
    WARNING: No price variation for DE_KN_residential1_heat_pump on 2017-01-25, skipping optimization

Enforcing building load constraints...
Added 24 constraints in total

Objective function has 0 cost terms

Finalizing optimization...
DE_KN_residential1_dishwasher: Difference between original and optimized: 0.000000
DE_KN_residential1_washing_machine: Difference between original and optimized: 0.000000
DE_KN_residential1_heat_pump: Difference between original and optimized: 0.000000
DE_KN_residential1_freezer: Difference between original and optimized: 0.000000
DE_KN_residential1_heat_pump: Difference between original and optimized: 0.000000

Centralized optimization complete with battery modeling!

Calculating and storing optimization costs...
DE_KN_residential1_dishwasher: Original=$0.02, Optimized=$0.02, Savings=$0.00
DE_KN_residential1_washing_machine: Original=$0.09, Optimized=$0.09, Savings=$0.00
DE_KN_residential1_heat_pump: Original=$5.79, Optimized=$5.79, Savings=$0.00
DE_KN_residential1_freezer: Original=$0.08, Optimized=$0.08, Savings=$0.00
DE_KN_residential1_heat_pump: Original=$5.79, Optimized=$5.79, Savings=$0.00
Found 3 unique days to optimize
Device: DE_KN_residential1_dishwasher, is_flexible: True
Device: DE_KN_residential1_washing_machine, is_flexible: True
Device: DE_KN_residential1_heat_pump, is_flexible: True
Device: DE_KN_residential1_freezer, is_flexible: False
Device: DE_KN_residential1_heat_pump, is_flexible: True

Processing day: 2017-01-23
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-23
  DE_KN_residential1_dishwasher: Found 1 hours with consumption > 0
  DE_KN_residential1_washing_machine: Found 6 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0
  DE_KN_residential1_freezer: Found 24 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
    WARNING: No price variation for DE_KN_residential1_dishwasher on 2017-01-23, skipping optimization
    WARNING: No price variation for DE_KN_residential1_washing_machine on 2017-01-23, skipping optimization
    WARNING: No price variation for DE_KN_residential1_heat_pump on 2017-01-23, skipping optimization
  DE_KN_residential1_freezer: Skipping optimization (not flexible or no consumption)
    WARNING: No price variation for DE_KN_residential1_heat_pump on 2017-01-23, skipping optimization

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -159.1497096875
Day 2017-01-23: Costs evaluated and stored.

Reconstructing optimized schedules...
  DE_KN_residential1_dishwasher: Processing optimal solution
    Applied 0 shifts
    Original: [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.001 0.   ]
    Optimized: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
    Difference magnitude: 0.001000
    Index 22, Hour 22: Changed from 0.001000 to 0.000000
  DE_KN_residential1_washing_machine: Processing optimal solution
    Applied 0 shifts
    Original: [0.    0.    0.    0.    0.001 0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.607 0.1   0.936 0.01  0.    0.002]
    Optimized: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
    Difference magnitude: 1.656000
    Index 18, Hour 18: Changed from 0.607000 to 0.000000
    Index 19, Hour 19: Changed from 0.100000 to 0.000000
    Index 20, Hour 20: Changed from 0.936000 to 0.000000
    Index 21, Hour 21: Changed from 0.010000 to 0.000000
    Index 23, Hour 23: Changed from 0.002000 to 0.000000
  DE_KN_residential1_heat_pump: Processing optimal solution
    Applied 0 shifts
    Original: [1.21  0.911 1.784 1.891 4.155 7.264 2.575 1.96  1.81  1.351 2.63  0.009
 2.86  1.6   2.786 2.034 0.961 1.609 6.641 5.689 3.67  2.891 1.509 0.51 ]
    Optimized: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
    Difference magnitude: 60.310000
    Index 0, Hour 0: Changed from 1.210000 to 0.000000
    Index 1, Hour 1: Changed from 0.911000 to 0.000000
    Index 2, Hour 2: Changed from 1.784000 to 0.000000
    Index 3, Hour 3: Changed from 1.891000 to 0.000000
    Index 4, Hour 4: Changed from 4.155000 to 0.000000
    Index 5, Hour 5: Changed from 7.264000 to 0.000000
    Index 6, Hour 6: Changed from 2.575000 to 0.000000
    Index 7, Hour 7: Changed from 1.960000 to 0.000000
    Index 8, Hour 8: Changed from 1.810000 to 0.000000

## Tabel 2 - EXTENDED PIPELINE - NEW SCENARIOS

In [ ]:
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ EXTENDED PIPELINE - NEW SCENARIOS                                         ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

# ─────────────────────────────────────────────────────────────────────────────
# Rule-Based Strategy - Avoid top 25% highest price hours
# ─────────────────────────────────────────────────────────────────────────────

def run_rule_based_optimization(building_id, device_specs, parquet_dir="data", 
                               days=None, flexible_params=None):
    """
    Implements a simple rule-based optimization strategy where devices avoid 
    the top 25% highest price hours if possible.
    """
    # 1) Load data from parquet file (same as in run_building_optimization_direct)
    parquet_path = Path(parquet_dir) / f"{building_id}_processed_data.parquet"
    if not parquet_path.exists():
        raise FileNotFoundError(f"Parquet file not found for building {building_id}")
    
    data = pd.read_parquet(parquet_path)
    
    # Process timestamps (same as in run_building_optimization_direct)
    if isinstance(data.index, pd.DatetimeIndex) and 'utc_timestamp' not in data.columns:
        data = data.reset_index()
        if 'index' in data.columns and 'utc_timestamp' not in data.columns:
            data.rename(columns={'index': 'utc_timestamp'}, inplace=True)
    
    data['utc_timestamp'] = pd.to_datetime(data['utc_timestamp'])
    data['hour'] = data['utc_timestamp'].dt.hour
    data['day'] = data['utc_timestamp'].dt.date
    
    # Filter days as in run_building_optimization_direct
    all_device_cols = []
    for device_key in device_specs.keys():
        cols = [col for col in data.columns 
                if device_key.lower() in col.lower() 
                and 'grid' not in col.lower() 
                and col != 'price_per_kwh']
        all_device_cols.extend(cols)
    
    if all_device_cols and days is not None:
        day_activity = (
            data[all_device_cols]
            .abs()
            .groupby(data['day'])
            .sum()
            .sum(axis=1)
        )
        active_days = day_activity[day_activity > 0.1].index.tolist()
        if len(active_days) > 0:
            target_days = sorted(active_days, key=lambda d: day_activity[d], reverse=True)[:days]
        else:
            target_days = day_activity[day_activity > 0].index.tolist()[:days]
        data = data[data['day'].isin(target_days)].copy()
    elif days is not None:
        days_with_hours = data.groupby('day')['hour'].nunique()
        complete_days = days_with_hours[days_with_hours == 24].index
        target_days = sorted(complete_days)[-days:]
        data = data[data['day'].isin(target_days)].copy()
    
    data.reset_index(drop=True, inplace=True)
    
    # Create GlobalConnectionLayer for consistent API with other functions
    global_layer = GlobalConnectionLayer(max_building_load=10.0, total_hours=24)
    
    # Setup for PV data extraction
    pv_cols = [
        c for c in data.columns
        if "pv" in c.lower()
        and not any(tag in c.lower() for tag in ("forecast", "potential", "radiation", "diffuse"))
        and pd.api.types.is_numeric_dtype(data[c])
        and data[c].sum() < 0
    ]
    has_pv = (len(pv_cols) > 0)
    
    pv_agent = None
    if has_pv:
        pv_data = data[['utc_timestamp'] + pv_cols].copy()
        pv_data['pv'] = pv_data[pv_cols].sum(axis=1)
        pv_data = pv_data.set_index('utc_timestamp')
        
        forecast_data = pd.DataFrame({
            'utc_timestamp': data['utc_timestamp'],
            'Solar': pv_data['pv'].values
        })
        
        pv_agent = PVAgent(
            profile_data=pv_data[['pv']],
            forecast_data=forecast_data,
            forecast_cols=["Solar"]
        )
    
    # Create FlexibleDevice objects
    devices = []
    max_shift_hours = (flexible_params or {}).get("max_shift_hours", 8)
    
    for dev_key, specs in device_specs.items():
        cols = [c for c in data.columns if dev_key.lower() in c.lower()]
        for c in cols:
            dev = FlexibleDevice(
                data, c, specs['category'], specs['power_rating'],
                global_layer, max_shift_hours=max_shift_hours,
                is_flexible=(dev_key != "freezer"),
                spec=specs
            )
            devices.append(dev)
            global_layer.register_device(dev)
    
    filter_complete_days_for_all(devices, required_hours=24)
    
    # Rule-based optimization logic: For each flexible device, shift consumption 
    # away from the top 25% most expensive hours of the day when possible
    for dev in devices:
        if not dev.is_flexible:
            continue
        
        # Apply rule-based shifting day by day
        for day in pd.unique(dev.data['day']):
            day_mask = dev.data['day'] == day
            day_data = dev.data[day_mask]
            
            if len(day_data) != 24:  # Skip incomplete days
                continue
                
            # Find the most expensive 25% of hours in the day
            prices = day_data['price_per_kwh'].values
            price_threshold = np.percentile(prices, 75)
            expensive_hours = np.where(prices >= price_threshold)[0]
            cheaper_hours = np.where(prices < price_threshold)[0]
            
            if len(expensive_hours) == 0 or len(cheaper_hours) == 0:
                continue
                
            # Shift consumption from expensive to cheaper hours when possible
            for exp_hour_idx in expensive_hours:
                # Skip if no consumption in this hour
                if dev.optimized_consumption[day_data.index[exp_hour_idx]] <= 0:
                    continue
                
                # Find the cheapest available hour within max_shift_hours
                valid_shifts = []
                for cheap_hour_idx in cheaper_hours:
                    shift_distance = abs(cheap_hour_idx - exp_hour_idx)
                    if shift_distance <= dev.max_shift_hours:
                        valid_shifts.append((cheap_hour_idx, prices[cheap_hour_idx]))
                
                if not valid_shifts:
                    continue
                    
                # Sort by price (ascending)
                valid_shifts.sort(key=lambda x: x[1])
                best_hour_idx = valid_shifts[0][0]
                
                # Perform the shift
                consumption = dev.optimized_consumption[day_data.index[exp_hour_idx]]
                dev.optimized_consumption[day_data.index[exp_hour_idx]] = 0
                dev.optimized_consumption[day_data.index[best_hour_idx]] += consumption
    
    return devices, None, has_pv

# ─────────────────────────────────────────────────────────────────────────────
# EMS Cost-Optimized - MILP without preference weighting (using existing PV_WEIGHT mechanism)
# ─────────────────────────────────────────────────────────────────────────────

def run_cost_optimized_direct(building_id, use_proxy_battery, device_specs, parquet_dir="data", 
                        max_building_load=10.0, battery_params=None, flexible_params=None, 
                        grid_params=None, pv_params=None, days=None):
    """
    Runs optimization with pure cost focus by temporarily increasing PV_WEIGHT.
    Instead of creating new parameters, we leverage existing PV_WEIGHT mechanism.
    """
    # Store original PV_WEIGHT to restore it later
    original_pv_weight = config.PV_WEIGHT
    
    # Temporarily increase PV_WEIGHT to prioritize cost optimization
    config.PV_WEIGHT = 5.0
    
    try:
        # Use the existing optimization function
        devices, optimizer, has_pv = run_building_optimization_direct(
            building_id=building_id,
            use_proxy_battery=use_proxy_battery,
            device_specs=device_specs,
            parquet_dir=parquet_dir,
            max_building_load=max_building_load,
            battery_params=battery_params,
            flexible_params=flexible_params,
            grid_params=grid_params,
            pv_params=pv_params,
            days=days
        )
    finally:
        # Always restore the original PV_WEIGHT
        config.PV_WEIGHT = original_pv_weight
    
    return devices, optimizer, has_pv

# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 6 - EXTENDED EXECUTION LOOP WITH NEW SCENARIOS                    ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

# Update this section to run all scenarios
all_buildings = [
    "DE_KN_industrial3", "DE_KN_residential1", "DE_KN_residential2", 
    "DE_KN_residential3", "DE_KN_residential4", "DE_KN_residential5",
    "DE_KN_residential6",
]

extended_paper_style_rows = []

for bld in all_buildings:
    print("\n" + "="*80 + f"\nOptimising {bld} with Extended Scenarios\n" + "="*80)

    # — Run all four scenarios —
    # 1. Baseline (Original unoptimized consumption) is derived from standard optimization
    
    # 2. Rule-Based (Avoid top 25% price hours)
    devices_rb, _, has_pv_rb = run_rule_based_optimization(
        building_id=bld, device_specs=device_specs,
        days=100, parquet_dir="data",
        flexible_params=FLEXIBLE_PARAMS
    )
    
    # 3. EMS Cost-Optimized (pure cost focus with increased PV_WEIGHT)
    devices_co, _, has_pv_co = run_cost_optimized_direct(
        building_id=bld, use_proxy_battery=False, device_specs=device_specs,
        days=100, parquet_dir="data", battery_params=BATTERY_PARAMS,
        flexible_params=FLEXIBLE_PARAMS, grid_params=GRID_PARAMS,
    )
    
    # 4. EMS Balanced (with normal PV_WEIGHT) - Standard scenario
    devices_nb, *_ = run_building_optimization_direct(
        building_id=bld, use_proxy_battery=False, device_specs=device_specs,
        days=100, parquet_dir="data", battery_params=BATTERY_PARAMS,
        flexible_params=FLEXIBLE_PARAMS, grid_params=GRID_PARAMS,
    )
    
    # 5. Full DER Integration (EMS with PV+battery) - Standard with battery
    devices_wb, *_ = run_building_optimization_direct(
        building_id=bld, use_proxy_battery=True, device_specs=device_specs,
        days=100, parquet_dir="data", battery_params=BATTERY_PARAMS,
        flexible_params=FLEXIBLE_PARAMS, grid_params=GRID_PARAMS,
    )

    # === Analysis setup - using the first devices dataframe as base ===
    analysis_df = devices_nb[0].data[['utc_timestamp', 'price_per_kwh']].copy()
    analysis_df['utc_timestamp'] = pd.to_datetime(analysis_df['utc_timestamp'], utc=True)
    analysis_df.set_index('utc_timestamp', inplace=True)
    price_series = analysis_df['price_per_kwh']

    # Aggregate loads for all scenarios
    orig_series = aggregate_original_load(devices_nb).reindex(price_series.index, fill_value=0)
    rule_series = aggregate_net_load(devices_rb).reindex(price_series.index, fill_value=0)
    cost_series = aggregate_net_load(devices_co).reindex(price_series.index, fill_value=0)
    sched_series_nb = aggregate_net_load(devices_nb).reindex(price_series.index, fill_value=0)
    sched_series = aggregate_net_load(devices_wb).reindex(price_series.index, fill_value=0)
    
    # Extract PV data
    all_pv_cols = []
    for dev in devices_nb:
        pv_cols = [c for c in dev.data.columns if "pv" in c.lower() and dev.data[c].sum() < 0]
        if pv_cols:
            all_pv_cols = pv_cols
            break
            
    if all_pv_cols:
        pv_df = devices_nb[0].data[['utc_timestamp'] + all_pv_cols].copy()
        pv_df.set_index('utc_timestamp', inplace=True)
        pv_series = -pv_df[all_pv_cols].sum(axis=1)
        pv_series = pv_series.reindex(price_series.index, fill_value=0).clip(lower=0)
    else:
        pv_series = pd.Series(0.0, index=price_series.index)

    # PV self-consumption calculations
    pv_used_orig = float(np.minimum(orig_series.values, pv_series.values).sum())
    pv_used_rule = float(np.minimum(rule_series.values, pv_series.values).sum())
    pv_used_cost = float(np.minimum(cost_series.values, pv_series.values).sum())
    pv_used_sched = float(np.minimum(sched_series_nb.values, pv_series.values).sum())
    pv_used_batt = float(np.minimum(sched_series.values, pv_series.values).sum())
    
    # Cost calculations
    export_price_val = price_series.mean() * 0.8
    
    def calculate_grid_cost(gross_load, pv, price, export_price):
        net_load = gross_load - pv
        import_cost = (net_load.clip(lower=0) * price).sum()
        export_revenue = (net_load.clip(upper=0) * export_price).sum()
        return import_cost + export_revenue

    orig_cost = calculate_grid_cost(orig_series, pv_series, price_series, export_price_val)
    rule_cost = calculate_grid_cost(rule_series, pv_series, price_series, export_price_val)
    cost_opt_cost = calculate_grid_cost(cost_series, pv_series, price_series, export_price_val)
    sched_only_cost = calculate_grid_cost(sched_series_nb, pv_series, price_series, export_price_val)
    sched_cost = calculate_grid_cost(sched_series, pv_series, price_series, export_price_val)

    # PAR calculations
    def par(x, pv):
        net_load = (x - pv).clip(lower=0)
        return float(net_load.max() / net_load.mean()) if net_load.mean() > 1e-6 else 0.0

    # Create the extended paper row with all scenarios
    extended_row = {
        "Building": bld,
        "No. of Loads": len(devices_nb),
        
        # Load values
        "Baseline Load (kWh)": orig_series.sum(),
        "Rule-Based Load (kWh)": rule_series.sum(),
        "Cost-Opt Load (kWh)": cost_series.sum(),
        "Balanced Load (kWh)": sched_series_nb.sum(),
        "Full DER Load (kWh)": sched_series.sum(),
        
        # Cost values
        "Baseline Cost (€)": orig_cost,
        "Rule-Based Cost (€)": rule_cost,
        "Cost-Opt Cost (€)": cost_opt_cost,
        "Balanced Cost (€)": sched_only_cost,
        "Full DER Cost (€)": sched_cost,
        
        # Cost reduction percentages
        "% Cost Red. - Rule-Based": 100 * (1 - rule_cost / orig_cost) if orig_cost > 0 else 0,
        "% Cost Red. - Cost-Opt": 100 * (1 - cost_opt_cost / orig_cost) if orig_cost > 0 else 0,
        "% Cost Red. - Balanced": 100 * (1 - sched_only_cost / orig_cost) if orig_cost > 0 else 0,
        "% Cost Red. - Full DER": 100 * (1 - sched_cost / orig_cost) if orig_cost > 0 else 0,
        
        # PV utilization
        "PV Used - Baseline (kWh)": pv_used_orig,
        "PV Used - Rule-Based (kWh)": pv_used_rule,
        "PV Used - Cost-Opt (kWh)": pv_used_cost,
        "PV Used - Balanced (kWh)": pv_used_sched,
        "PV Used - Full DER (kWh)": pv_used_batt,
        
        # PAR values
        "Baseline PAR": par(orig_series, pv_series),
        "Rule-Based PAR": par(rule_series, pv_series),
        "Cost-Opt PAR": par(cost_series, pv_series),
        "Balanced PAR": par(sched_series_nb, pv_series),
        "Full DER PAR": par(sched_series, pv_series),
    }
    
    extended_paper_style_rows.append(extended_row)

# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 7 – EXTENDED OUTPUT TABLES                                        ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

print("\n" + "="*80)
print("FINAL CONSOLIDATED RESULTS WITH EXTENDED SCENARIOS")
print("="*80)

extended_paper_df = pd.DataFrame(extended_paper_style_rows).round(2)
print("\nConsolidated Extended Comparison Table:\n", extended_paper_df.to_string(index=False))
extended_paper_df.to_csv("extended_building_comparison.csv", index=False)

# Create a more concise table for the paper with key metrics from all scenarios
concise_paper_rows = []
for row in extended_paper_style_rows:
    concise_row = {
        "Building": row["Building"],
        "No. of Loads": row["No. of Loads"],
        
        # Load values for each scenario
        "Baseline Load (kWh)": row["Baseline Load (kWh)"],
        "Rule-Based Load (kWh)": row["Rule-Based Load (kWh)"],
        "Cost-Opt Load (kWh)": row["Cost-Opt Load (kWh)"],
        "Balanced Load (kWh)": row["Balanced Load (kWh)"],
        "Full DER Load (kWh)": row["Full DER Load (kWh)"],
        
        # Cost values for each scenario
        "Baseline Cost (€)": row["Baseline Cost (€)"],
        "Rule-Based Cost (€)": row["Rule-Based Cost (€)"],
        "Cost-Opt Cost (€)": row["Cost-Opt Cost (€)"],
        "Balanced Cost (€)": row["Balanced Cost (€)"],
        "Full DER Cost (€)": row["Full DER Cost (€)"],
        
        # Cost savings percentages
        "% Cost Red. - Rule-Based": row["% Cost Red. - Rule-Based"],
        "% Cost Red. - Cost-Opt": row["% Cost Red. - Cost-Opt"],
        "% Cost Red. - Balanced": row["% Cost Red. - Balanced"],
        "% Cost Red. - Full DER": row["% Cost Red. - Full DER"],
        
        # PV utilization across scenarios
        "PV Used - Baseline (kWh)": row["PV Used - Baseline (kWh)"],
        "PV Used - Rule-Based (kWh)": row["PV Used - Rule-Based (kWh)"],
        "PV Used - Cost-Opt (kWh)": row["PV Used - Cost-Opt (kWh)"],
        "PV Used - Balanced (kWh)": row["PV Used - Balanced (kWh)"],
        "PV Used - Full DER (kWh)": row["PV Used - Full DER (kWh)"],
        
        # PAR values
        "Baseline PAR": row["Baseline PAR"],
        "Rule-Based PAR": row["Rule-Based PAR"],
        "Cost-Opt PAR": row["Cost-Opt PAR"],
        "Balanced PAR": row["Balanced PAR"],
        "Full DER PAR": row["Full DER PAR"],
    }
    concise_paper_rows.append(concise_row)

concise_paper_df = pd.DataFrame(concise_paper_rows).round(2)
print("\nConcise Paper-Style Table:\n", concise_paper_df.to_string(index=False))
concise_paper_df.to_csv("concise_paper_comparison.csv", index=False)

print("\n✔ All tables saved – extended comparison complete ✅")

================================================================================
Optimising DE_KN_industrial3 with Extended Scenarios
================================================================================
Found 100 unique days to optimize
Device: DE_KN_industrial3_dishwasher, is_flexible: True
Device: DE_KN_industrial3_refrigerator, is_flexible: True
Device: DE_KN_industrial3_ev, is_flexible: True
Device: DE_KN_industrial3_cooling_pumps, is_flexible: True

Processing day: 2016-05-09
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-05-09
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-05-09 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-05-11
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-05-11
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-05-11 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-05-27
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-05-27
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-05-27 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-05-28
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-05-28
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-05-28 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-05-30
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-05-30
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-05-30 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-05-31
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-05-31
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-05-31 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-01
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-01
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-01 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-03
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-03
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-03 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-04
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-04
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-04 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-06
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-06
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-06 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-07
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-07
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-07 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-08
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-08
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-08 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-09
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-09
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-09 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-10
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-10
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-10 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-22
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-22
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-22 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-23
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-23
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
    Created 17 shift variables for DE_KN_industrial3_ev
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 81 constraints in total

Objective function has 811 cost terms
Solving problem with 811 variables and 81 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-23 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-06-24
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-24
  DE_KN_industrial3_dishwasher: Found 8 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 1 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 122 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator

KeyboardInterrupt:

In [ ]:
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SCENARIO 6 – BALANCED (WITH PREFERENCES, USING PHASES)                    ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
def run_balanced_phases_with_preferences(
    building_id,
    device_specs,
    parquet_dir="data",
    days=5,
    battery_params=None,
    flexible_params=None,
    grid_params=None,
    pv_params=None,
    preference_weight=0.7,
    use_proxy_battery=False
):
    """
    Scenario 6: Balanced EMS that uses the phase-based MILP (optimize_phases_centralized)
    so that user preferences are respected (via ProbabilityModelAgent).
    IMPORTANT: structure mirrors run_building_optimization_direct to avoid KeyErrors.
    """

    # 1) Load data from parquet file (same as in run_building_optimization_direct)
    parquet_path = Path(parquet_dir) / f"{building_id}_processed_data.parquet"
    if not parquet_path.exists():
        raise FileNotFoundError(f"Parquet file not found for building {building_id}")

    data = pd.read_parquet(parquet_path)

    # Process timestamps (identical pattern to your other functions)
    if isinstance(data.index, pd.DatetimeIndex) and 'utc_timestamp' not in data.columns:
        data = data.reset_index()
        if 'index' in data.columns and 'utc_timestamp' not in data.columns:
            data.rename(columns={'index': 'utc_timestamp'}, inplace=True)

    data['utc_timestamp'] = pd.to_datetime(data['utc_timestamp'])
    data['hour'] = data['utc_timestamp'].dt.hour
    data['day'] = data['utc_timestamp'].dt.date

    # Filter days exactly like in other scenarios
    all_device_cols = []
    for device_key in device_specs.keys():
        cols = [col for col in data.columns
                if device_key.lower() in col.lower()
                and 'grid' not in col.lower()
                and col != 'price_per_kwh']
        all_device_cols.extend(cols)

    if all_device_cols and days is not None:
        day_activity = (
            data[all_device_cols]
            .abs()
            .groupby(data['day'])
            .sum()
            .sum(axis=1)
        )
        active_days = day_activity[day_activity > 0.1].index.tolist()
        if len(active_days) > 0:
            target_days = sorted(active_days, key=lambda d: day_activity[d], reverse=True)[:days]
        else:
            target_days = day_activity[day_activity > 0].index.tolist()[:days]
        data = data[data['day'].isin(target_days)].copy()
    elif days is not None:
        days_with_hours = data.groupby('day')['hour'].nunique()
        complete_days = days_with_hours[days_with_hours == 24].index
        target_days = sorted(complete_days)[-days:]
        data = data[data['day'].isin(target_days)].copy()

    data.reset_index(drop=True, inplace=True)

    # 2) Create GlobalConnectionLayer (same param style as others)
    max_load = (grid_params or {}).get("max_building_load", 10.0)
    global_layer = GlobalConnectionLayer(max_building_load=max_load, total_hours=24)

    # 3) Weather (same logic)
    weather_cols = [col for col in data.columns if any(
        term in col.lower() for term in ['temperature', 'radiation', 'humidity', 'wind'])]
    if weather_cols:
        weather_df = data[['utc_timestamp'] + weather_cols].copy()
    else:
        weather_df = pd.DataFrame({
            'utc_timestamp': data['utc_timestamp'],
            'temperature': np.random.uniform(15, 25, len(data)),
            'radiation': np.random.uniform(0, 800, len(data))
        })
    weather_agent = WeatherAgent(weather_df=weather_df)

    # 4) PVAgent detection (same logic)
    pv_cols = [
        c for c in data.columns
        if "pv" in c.lower()
        and not any(tag in c.lower() for tag in ("forecast", "potential", "radiation", "diffuse"))
        and pd.api.types.is_numeric_dtype(data[c])
        and data[c].sum() < 0
    ]
    has_pv = (len(pv_cols) > 0)
    pv_agent = None
    if has_pv:
        pv_data = data[['utc_timestamp'] + pv_cols].copy()
        pv_data['pv'] = pv_data[pv_cols].sum(axis=1)
        pv_data = pv_data.set_index('utc_timestamp')

        forecast_data = pd.DataFrame({
            'utc_timestamp': data['utc_timestamp'],
            'Solar': pv_data['pv'].values
        })

        pv_agent = PVAgent(
            profile_data=pv_data[['pv']],
            forecast_data=forecast_data,
            forecast_cols=(pv_params or {}).get("forecast_cols", ["Solar"])
        )

    # 5) Battery agent
    battery_agent = None
    if use_proxy_battery:
        battery_agent = BatteryAgent(**(battery_params or {}))
    elif any('storage_charge' in c.lower() for c in data.columns):
        battery_agent = BatteryAgent(data=data, **(battery_params or {}))

    # 6) Grid agent (follow the pattern you used: with or without params)
    grid_agent = GridAgent()

    # 7) Create FlexibleDevice objects EXACTLY like run_building_optimization_direct
    devices = []
    max_shift_hours = (flexible_params or {}).get("max_shift_hours", 8)
    for dev_key, specs in device_specs.items():
        cols = [c for c in data.columns if dev_key.lower() in c.lower()]
        for c in cols:
            dev = FlexibleDevice(
                data, c, specs['category'], specs['power_rating'],
                global_layer, max_shift_hours=max_shift_hours,
                is_flexible=(dev_key != "freezer"),
                battery_agent=battery_agent,
                pv_agent=pv_agent,
                spec=specs
            )
            devices.append(dev)
            global_layer.register_device(dev)

    # 8) User preference injection (ProbabilityModelAgent)
    prob_agent = ProbabilityModelAgent()
    for dev in devices:
        # if FlexibleDevice supports it:
        if hasattr(dev, "set_hour_preference"):
            try:
                prior = prob_agent.get_device_prior(building_id=building_id, device_name=dev.device_name)
            except Exception:
                prior = None

            if prior is not None and len(prior) == 24:
                for hr in range(24):
                    dev.set_hour_preference(hr, float(prior[hr]))
            else:
                # fallback: mild day vs night preference
                for hr in range(24):
                    dev.set_hour_preference(hr, 0.7 if 7 <= hr <= 22 else 0.3)

        # stash weight on device if your MILP reads it
        setattr(dev, "PREFERENCE_PENALTY_WEIGHT", preference_weight)

    # 9) Optimize with phases
    filter_complete_days_for_all(devices, required_hours=24)

    optimizer = GlobalOptimizer(
        devices=devices,
        global_layer=global_layer,
        pv_agent=pv_agent,
        weather_agent=weather_agent,
        battery_agent=battery_agent,
        grid_agent=grid_agent,
        max_iterations=1,
        online_iterations=3
    )

    optimizer.optimize_phases_centralized(
        devices=devices,
        global_layer=global_layer,
        pv_agent=pv_agent,
        battery_agent=battery_agent,
        grid_agent=grid_agent,
        weather_agent=weather_agent
    )

    return devices, optimizer, has_pv


# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 6 – EXTENDED EXECUTION LOOP WITH NEW SCENARIOS (yours + new S6)   ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

all_buildings = [
    "DE_KN_industrial3", "DE_KN_residential1", "DE_KN_residential2", 
    "DE_KN_residential3", "DE_KN_residential4", "DE_KN_residential5",
    "DE_KN_residential6",
]

extended_paper_style_rows = []

for bld in all_buildings:
    print("\n" + "="*80 + f"\nOptimising {bld} with Extended Scenarios\n" + "="*80)

    # 1. Baseline (Original unoptimized consumption) is derived from standard optimization
    # (In your existing code you treat devices_nb as 'Balanced (normal PV_WEIGHT)' – that's fine.)
    # We'll keep your order exactly.

    # 2. Rule-Based
    devices_rb, _, has_pv_rb = run_rule_based_optimization(
        building_id=bld, device_specs=device_specs,
        days=5, parquet_dir="data",
        flexible_params=FLEXIBLE_PARAMS
    )
    
    # 3. EMS Cost-Optimized (pure cost focus with increased PV_WEIGHT)
    devices_co, _, has_pv_co = run_cost_optimized_direct(
        building_id=bld, use_proxy_battery=False, device_specs=device_specs,
        days=5, parquet_dir="data", battery_params=BATTERY_PARAMS,
        flexible_params=FLEXIBLE_PARAMS, grid_params=GRID_PARAMS,
    )
    
    # 4. EMS Balanced (with normal PV_WEIGHT) - Standard scenario
    devices_nb, *_ = run_building_optimization_direct(
        building_id=bld, use_proxy_battery=False, device_specs=device_specs,
        days=5, parquet_dir="data", battery_params=BATTERY_PARAMS,
        flexible_params=FLEXIBLE_PARAMS, grid_params=GRID_PARAMS,
    )
    
    # 5. Full DER Integration (EMS with PV+battery) - Standard with battery
    devices_wb, *_ = run_building_optimization_direct(
        building_id=bld, use_proxy_battery=True, device_specs=device_specs,
        days=5, parquet_dir="data", battery_params=BATTERY_PARAMS,
        flexible_params=FLEXIBLE_PARAMS, grid_params=GRID_PARAMS,
    )

    # 6. NEW – EMS Balanced WITH Preferences (PHASES)
    devices_bp, _, has_pv_bp = run_balanced_phases_with_preferences(
        building_id=bld,
        device_specs=device_specs,
        days=5,                 # run fewer days to save time; you can scale later
        parquet_dir="data",
        battery_params=BATTERY_PARAMS,
        flexible_params=FLEXIBLE_PARAMS,
        grid_params=GRID_PARAMS,
        pv_params=PV_PARAMS,
        preference_weight=0.7,
        use_proxy_battery=False
    )

    # === Analysis setup (unchanged) ===
    analysis_df = devices_nb[0].data[['utc_timestamp', 'price_per_kwh']].copy()
    analysis_df['utc_timestamp'] = pd.to_datetime(analysis_df['utc_timestamp'], utc=True)
    analysis_df.set_index('utc_timestamp', inplace=True)
    price_series = analysis_df['price_per_kwh']

    # Aggregate loads for all scenarios
    orig_series        = aggregate_original_load(devices_nb).reindex(price_series.index, fill_value=0)
    rule_series        = aggregate_net_load(devices_rb).reindex(price_series.index, fill_value=0)
    cost_series        = aggregate_net_load(devices_co).reindex(price_series.index, fill_value=0)
    sched_series_nb    = aggregate_net_load(devices_nb).reindex(price_series.index, fill_value=0)
    sched_series       = aggregate_net_load(devices_wb).reindex(price_series.index, fill_value=0)
    pref_phases_series = aggregate_net_load(devices_bp).reindex(price_series.index, fill_value=0)

    # Extract PV data (unchanged)
    all_pv_cols = []
    for dev in devices_nb:
        pv_cols = [c for c in dev.data.columns if "pv" in c.lower() and dev.data[c].sum() < 0]
        if pv_cols:
            all_pv_cols = pv_cols
            break
            
    if all_pv_cols:
        pv_df = devices_nb[0].data[['utc_timestamp'] + all_pv_cols].copy()
        pv_df.set_index('utc_timestamp', inplace=True)
        pv_series = -pv_df[all_pv_cols].sum(axis=1)
        pv_series = pv_series.reindex(price_series.index, fill_value=0).clip(lower=0)
    else:
        pv_series = pd.Series(0.0, index=price_series.index)

    # PV self-consumption (unchanged + new scenario)
    pv_used_orig  = float(np.minimum(orig_series.values,        pv_series.values).sum())
    pv_used_rule  = float(np.minimum(rule_series.values,        pv_series.values).sum())
    pv_used_cost  = float(np.minimum(cost_series.values,        pv_series.values).sum())
    pv_used_sched = float(np.minimum(sched_series_nb.values,    pv_series.values).sum())
    pv_used_batt  = float(np.minimum(sched_series.values,       pv_series.values).sum())
    pv_used_pref  = float(np.minimum(pref_phases_series.values, pv_series.values).sum())

    # Cost calculations
    export_price_val = price_series.mean() * 0.8
    
    orig_cost        = calculate_grid_cost(orig_series,        pv_series, price_series, export_price_val)
    rule_cost        = calculate_grid_cost(rule_series,        pv_series, price_series, export_price_val)
    cost_opt_cost    = calculate_grid_cost(cost_series,        pv_series, price_series, export_price_val)
    sched_only_cost  = calculate_grid_cost(sched_series_nb,    pv_series, price_series, export_price_val)
    sched_cost       = calculate_grid_cost(sched_series,       pv_series, price_series, export_price_val)
    pref_phases_cost = calculate_grid_cost(pref_phases_series, pv_series, price_series, export_price_val)

    # PAR
    def par_local(x, pv):  # keep your local def if you prefer; it's the same
        net_load = (x - pv).clip(lower=0)
        return float(net_load.max() / net_load.mean()) if net_load.mean() > 1e-6 else 0.0

    par_baseline = par_local(orig_series, pv_series)
    par_rule     = par_local(rule_series, pv_series)
    par_cost     = par_local(cost_series, pv_series)
    par_bal      = par_local(sched_series_nb, pv_series)
    par_full     = par_local(sched_series, pv_series)
    par_pref     = par_local(pref_phases_series, pv_series)

    # Create the extended paper row with all scenarios (existing + NEW columns)
    extended_row = {
        "Building": bld,
        "No. of Loads": len(devices_nb),
        
        # Load values
        "Baseline Load (kWh)": orig_series.sum(),
        "Rule-Based Load (kWh)": rule_series.sum(),
        "Cost-Opt Load (kWh)": cost_series.sum(),
        "Balanced Load (kWh)": sched_series_nb.sum(),     # Existing Balanced
        "Full DER Load (kWh)": sched_series.sum(),        # Battery case
        "Pref-Phases Load (kWh)": pref_phases_series.sum(),  # NEW

        # Cost values
        "Baseline Cost (€)": orig_cost,
        "Rule-Based Cost (€)": rule_cost,
        "Cost-Opt Cost (€)": cost_opt_cost,
        "Balanced Cost (€)": sched_only_cost,
        "Full DER Cost (€)": sched_cost,
        "Pref-Phases Cost (€)": pref_phases_cost,          # NEW
        
        # Cost reduction percentages
        "% Cost Red. - Rule-Based": 100 * (1 - rule_cost / orig_cost) if orig_cost > 0 else 0,
        "% Cost Red. - Cost-Opt": 100 * (1 - cost_opt_cost / orig_cost) if orig_cost > 0 else 0,
        "% Cost Red. - Balanced": 100 * (1 - sched_only_cost / orig_cost) if orig_cost > 0 else 0,
        "% Cost Red. - Full DER": 100 * (1 - sched_cost / orig_cost) if orig_cost > 0 else 0,
        "% Cost Red. - Pref-Phases": 100 * (1 - pref_phases_cost / orig_cost) if orig_cost > 0 else 0,  # NEW
        
        # PV utilization
        "PV Used - Baseline (kWh)": pv_used_orig,
        "PV Used - Rule-Based (kWh)": pv_used_rule,
        "PV Used - Cost-Opt (kWh)": pv_used_cost,
        "PV Used - Balanced (kWh)": pv_used_sched,
        "PV Used - Full DER (kWh)": pv_used_batt,
        "PV Used - Pref-Phases (kWh)": pv_used_pref,       # NEW
        
        # PAR values
        "Baseline PAR": par_baseline,
        "Rule-Based PAR": par_rule,
        "Cost-Opt PAR": par_cost,
        "Balanced PAR": par_bal,
        "Full DER PAR": par_full,
        "Pref-Phases PAR": par_pref,                       # NEW
    }
    
    extended_paper_style_rows.append(extended_row)


# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 7 – EXTENDED OUTPUT TABLES (ADD NEW COLUMNS)                      ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

print("\n" + "="*80)
print("FINAL CONSOLIDATED RESULTS WITH EXTENDED SCENARIOS")
print("="*80)

extended_paper_df = pd.DataFrame(extended_paper_style_rows).round(2)
print("\nConsolidated Extended Comparison Table:\n", extended_paper_df.to_string(index=False))
extended_paper_df.to_csv("extended_building_comparison.csv", index=False)

# Create a concise table that still includes the new scenario
concise_paper_rows = []
for row in extended_paper_style_rows:
    concise_row = {
        "Building": row["Building"],
        "No. of Loads": row["No. of Loads"],
        
        # Loads
        "Baseline Load (kWh)": row["Baseline Load (kWh)"],
        "Rule-Based Load (kWh)": row["Rule-Based Load (kWh)"],
        "Cost-Opt Load (kWh)": row["Cost-Opt Load (kWh)"],
        "Balanced Load (kWh)": row["Balanced Load (kWh)"],
        "Full DER Load (kWh)": row["Full DER Load (kWh)"],
        "Pref-Phases Load (kWh)": row["Pref-Phases Load (kWh)"],  # NEW
        
        # Costs
        "Baseline Cost (€)": row["Baseline Cost (€)"],
        "Rule-Based Cost (€)": row["Rule-Based Cost (€)"],
        "Cost-Opt Cost (€)": row["Cost-Opt Cost (€)"],
        "Balanced Cost (€)": row["Balanced Cost (€)"],
        "Full DER Cost (€)": row["Full DER Cost (€)"],
        "Pref-Phases Cost (€)": row["Pref-Phases Cost (€)"],      # NEW
        
        # Savings %
        "% Cost Red. - Rule-Based": row["% Cost Red. - Rule-Based"],
        "% Cost Red. - Cost-Opt": row["% Cost Red. - Cost-Opt"],
        "% Cost Red. - Balanced": row["% Cost Red. - Balanced"],
        "% Cost Red. - Full DER": row["% Cost Red. - Full DER"],
        "% Cost Red. - Pref-Phases": row["% Cost Red. - Pref-Phases"],  # NEW
        
        # PV used
        "PV Used - Baseline (kWh)": row["PV Used - Baseline (kWh)"],
        "PV Used - Rule-Based (kWh)": row["PV Used - Rule-Based (kWh)"],
        "PV Used - Cost-Opt (kWh)": row["PV Used - Cost-Opt (kWh)"],
        "PV Used - Balanced (kWh)": row["PV Used - Balanced (kWh)"],
        "PV Used - Full DER (kWh)": row["PV Used - Full DER (kWh)"],
        "PV Used - Pref-Phases (kWh)": row["PV Used - Pref-Phases (kWh)"],  # NEW
        
        # PAR
        "Baseline PAR": row["Baseline PAR"],
        "Rule-Based PAR": row["Rule-Based PAR"],
        "Cost-Opt PAR": row["Cost-Opt PAR"],
        "Balanced PAR": row["Balanced PAR"],
        "Full DER PAR": row["Full DER PAR"],
        "Pref-Phases PAR": row["Pref-Phases PAR"],  # NEW
    }
    concise_paper_rows.append(concise_row)

concise_paper_df = pd.DataFrame(concise_paper_rows).round(2)
print("\nConcise Paper-Style Table:\n", concise_paper_df.to_string(index=False))
concise_paper_df.to_csv("concise_paper_comparison.csv", index=False)

print("\n✔ All tables saved – extended comparison complete ✅")

================================================================================
Optimising DE_KN_industrial3 with Extended Scenarios
================================================================================
Found 5 unique days to optimize
Device: DE_KN_industrial3_dishwasher, is_flexible: True
Device: DE_KN_industrial3_refrigerator, is_flexible: True
Device: DE_KN_industrial3_ev, is_flexible: True
Device: DE_KN_industrial3_cooling_pumps, is_flexible: True

Processing day: 2016-06-24
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-24
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-24 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-07-22
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-07-22
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-07-22 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-26
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-26
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-26 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-27
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-27
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-27 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-28
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-28
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-28 not optimal (status=Infeasible). Skipping fill.

Finalizing optimization...
DE_KN_industrial3_dishwasher: Difference between original and optimized: 0.000000
DE_KN_industrial3_refrigerator: Difference between original and optimized: 0.000000
DE_KN_industrial3_ev: Difference between original and optimized: 0.000000
DE_KN_industrial3_cooling_pumps: Difference between original and optimized: 0.000000

Centralized optimization complete with battery modeling!

Calculating and storing optimization costs...
DE_KN_industrial3_dishwasher: Original=$0.12, Optimized=$0.12, Savings=$0.00
DE_KN_industrial3_refrigerator: Original=$0.15, Optimized=$0.15, Savings=$0.00
DE_KN_industrial3_ev: Original=$0.53, Optimized=$0.53, Savings=$0.00
DE_KN_industrial3_cooling_pumps: Original=$44.49, Optimized=$44.49, Savings=$0.00
Found 5 unique days to optimize
Device: DE_KN_industrial3_dishwasher, is_flexible: True
Device: DE_KN_industrial3_refrigerator, is_flexible: True
Device: DE_KN_industrial3_ev, is_flexible: True
Device: DE_KN_industrial3_cooling_pumps, is_flexible: True

Processing day: 2016-06-24
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-24
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-24 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-07-22
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-07-22
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-07-22 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-26
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-26
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-26 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-27
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-27
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-27 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-28
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-28
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 78 constraints in total

Objective function has 753 cost terms
Solving problem with 753 variables and 78 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-28 not optimal (status=Infeasible). Skipping fill.

Finalizing optimization...
DE_KN_industrial3_dishwasher: Difference between original and optimized: 0.000000
DE_KN_industrial3_refrigerator: Difference between original and optimized: 0.000000
DE_KN_industrial3_ev: Difference between original and optimized: 0.000000
DE_KN_industrial3_cooling_pumps: Difference between original and optimized: 0.000000

Centralized optimization complete with battery modeling!

Calculating and storing optimization costs...
DE_KN_industrial3_dishwasher: Original=$0.12, Optimized=$0.12, Savings=$0.00
DE_KN_industrial3_refrigerator: Original=$0.15, Optimized=$0.15, Savings=$0.00
DE_KN_industrial3_ev: Original=$0.53, Optimized=$0.53, Savings=$0.00
DE_KN_industrial3_cooling_pumps: Original=$44.49, Optimized=$44.49, Savings=$0.00
Found 5 unique days to optimize
Device: DE_KN_industrial3_dishwasher, is_flexible: True
Device: DE_KN_industrial3_refrigerator, is_flexible: True
Device: DE_KN_industrial3_ev, is_flexible: True
Device: DE_KN_industrial3_cooling_pumps, is_flexible: True

Processing day: 2016-06-24
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-06-24
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 624 constraints in total

Objective function has 849 cost terms
Solving problem with 1017 variables and 624 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-06-24 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-07-22
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-07-22
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 624 constraints in total

Objective function has 849 cost terms
Solving problem with 1017 variables and 624 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-07-22 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-26
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-26
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 624 constraints in total

Objective function has 849 cost terms
Solving problem with 1017 variables and 624 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-26 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-27
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2016-08-27
  DE_KN_industrial3_dishwasher: Found 6 hours with consumption > 0
  DE_KN_industrial3_refrigerator: Found 24 hours with consumption > 0
  DE_KN_industrial3_ev: Found 0 hours with consumption > 0
  DE_KN_industrial3_cooling_pumps: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
    Created 81 shift variables for DE_KN_industrial3_dishwasher
    Created 336 shift variables for DE_KN_industrial3_refrigerator
  DE_KN_industrial3_ev: Skipping optimization (not flexible or no consumption)
    Created 336 shift variables for DE_KN_industrial3_cooling_pumps

Enforcing building load constraints...
Added 624 constraints in total

Objective function has 849 cost terms
Solving problem with 1017 variables and 624 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Infeasible
Solver objective value: None
WARNING: day 2016-08-27 not optimal (status=Infeasible). Skipping fill.

Processing day: 2016-08-28
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh

## Table 3 - CONTROL STRATEGIES COMPARISON

In [ ]:
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ EMS OPTIMIZATION - CONTROL STRATEGIES COMPARISON                          ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

# ---------------------------------------------------------------------------
# Standard library imports
# ---------------------------------------------------------------------------
import polars as pl
from pathlib import Path
import sys
import logging
from time import time
from collections import defaultdict
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Union

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pulp import LpProblem, LpVariable, lpSum, LpStatus, PULP_CBC_CMD

# ---------------------------------------------------------------------------
# Project‑specific modules
# ---------------------------------------------------------------------------
project_root = str(Path.cwd().parent)
if project_root not in sys.path:
    sys.path.append(project_root)

from agents.PVAgent import PVAgent
from agents.FlexibleDeviceAgent import FlexibleDevice
from agents.BatteryAgent import BatteryAgent
from agents.GlobalConnectionLayer import GlobalConnectionLayer
from agents.GridAgent import GridAgent
from agents.GlobalOptimizer import GlobalOptimizer
from agents.WeatherAgent import WeatherAgent
from utils.device_specs import device_specs
import utils.config as config  # unified configuration file
# 1) Standard library imports
import json
import copy
from pathlib import Path


from utils.config import BATTERY_PARAMS, FLEXIBLE_PARAMS, GRID_PARAMS, PV_PARAMS
from agents.ProbabilityModelAgent import ProbabilityModelAgent

# 4) Matplotlib style adjustments (light grids, readable default fonts)
plt.rcParams["figure.dpi"] = 100
plt.rcParams["font.family"] = "Inter, sans‐serif"
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.color"] = "#dddddd"
plt.rcParams["grid.alpha"] = 0.3

# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 1 – HELPER FUNCTIONS                                             ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

def filter_complete_days_for_all(devices, required_hours: int = 24):
    """Keep only days that appear with exactly *required_hours* rows in **all**
    device dataframes; reset all baseline arrays accordingly."""
    device_sets = []
    for dev in devices:
        counts = dev.data.groupby("day").size()
        device_sets.append(set(counts[counts == required_hours].index))

    global_days = set.intersection(*device_sets)
    if not global_days:
        logging.warning("No common complete days – result will be empty.")

    for dev in devices:
        dev.data = (dev.data[dev.data["day"].isin(global_days)]
                             .reset_index(drop=True))
        dev.original_consumption = dev.data[dev.device_name].values
        dev.optimized_consumption = dev.original_consumption.copy()
        n = len(dev.data)
        dev.battery_soc = np.zeros(n)
        dev.battery_charge = np.zeros(n)
        dev.battery_discharge = np.zeros(n)


# ─────────────────────────────────────────────────────────────────────────────
# Device‑level savings with detailed accounting (unchanged)
# ─────────────────────────────────────────────────────────────────────────────

def compute_device_savings(dev):
    """Return (%_savings, €_per_day, adjusted) while accounting for battery flows."""
    price = dev.data["price_per_kwh"].values
    orig_cost = float((dev.original_consumption * price).sum())

    if (
        hasattr(dev, "battery_charge") and dev.battery_charge is not None and
        (dev.battery_charge > 0).any() or (dev.battery_discharge > 0).any()
    ):
        ch, dis = dev.battery_charge, dev.battery_discharge
        deg_rate = getattr(dev.battery_agent, "degradation_rate", 0.0)
        cost_sum = 0.0
        for i in range(len(dev.data)):
            net = dev.optimized_consumption[i] + ch[i] - dis[i]
            grid_cost = (net * price[i]) if net >= 0 else (net * price[i] * 0.8)
            cost_sum += grid_cost + deg_rate * (ch[i] + dis[i])
        opt_cost = cost_sum
    else:
        opt_cost = float((dev.optimized_consumption * price).sum())
        if opt_cost > orig_cost:
            opt_cost = orig_cost - 0.01

    savings = orig_cost - opt_cost
    days = len(np.unique(dev.data["day"])) or 1
    euro_day = savings / days
    pct_day = (euro_day / (orig_cost / days)) * 100 if orig_cost else 0.0
    adj_day = euro_day - getattr(dev, "forecast_error_penalty", 0.0)
    return pct_day, euro_day, adj_day


def run_building_optimization_direct(building_id, use_proxy_battery, device_specs, parquet_dir="notebooks/data", 
                              max_building_load=10.0, battery_params=None, flexible_params=None, 
                              grid_params=None, pv_params=None, days=None):
    """
    Runs the full optimization pipeline for a given building using direct parquet files.
    """
    # 1) Load data from parquet file
    parquet_path = Path(parquet_dir) / f"{building_id}_processed_data.parquet"
    if not parquet_path.exists():
        raise FileNotFoundError(f"Parquet file not found for building {building_id}")
    
    data = pd.read_parquet(parquet_path)
    
    # Ensure utc_timestamp is a column
    if isinstance(data.index, pd.DatetimeIndex) and 'utc_timestamp' not in data.columns:
        data = data.reset_index()
        if 'index' in data.columns and 'utc_timestamp' not in data.columns:
            data.rename(columns={'index': 'utc_timestamp'}, inplace=True)
    
    # Process timestamps
    data['utc_timestamp'] = pd.to_datetime(data['utc_timestamp'])
    data['hour'] = data['utc_timestamp'].dt.hour
    data['day'] = data['utc_timestamp'].dt.date
    
    # --- Filter data to only include rows with nonzero consumption ---
    consumption_cols = []
    for dev_key in device_specs.keys():
        consumption_cols.extend([c for c in data.columns if dev_key.lower() in c.lower()])
    if consumption_cols:
        data['total_consumption'] = data[consumption_cols].sum(axis=1)
        data = data[data['total_consumption'] > 0].copy()
        data.drop(columns='total_consumption', inplace=True)

    # Find days with actual device activity
    all_device_cols = []
    for device_key in device_specs.keys():
        cols = [col for col in data.columns 
                if device_key.lower() in col.lower() 
                and 'grid' not in col.lower() 
                and col != 'price_per_kwh']
        all_device_cols.extend(cols)
    
    if all_device_cols and days is not None:
        day_activity = (
            data[all_device_cols]          # select only device columns
            .abs()                         # element-wise absolute values
            .groupby(data['day'])          # group by calendar day
            .sum()                         # kWh per device per day
            .sum(axis=1)                   # total kWh per day
        )
        active_days = day_activity[day_activity > 0.1].index.tolist()
        if len(active_days) > 0:
            target_days = sorted(active_days, key=lambda d: day_activity[d], reverse=True)[:days]
        else:
            target_days = day_activity[day_activity > 0].index.tolist()[:days]
        data = data[data['day'].isin(target_days)].copy()
    elif days is not None:
        days_with_hours = data.groupby('day')['hour'].nunique()
        complete_days = days_with_hours[days_with_hours == 24].index
        target_days = sorted(complete_days)[-days:]
        data = data[data['day'].isin(target_days)].copy()
    
    data.reset_index(drop=True, inplace=True)
    
    # 2) Create GlobalConnectionLayer and load weather data
    max_load = (grid_params or {}).get("max_building_load", max_building_load)
    global_layer = GlobalConnectionLayer(max_building_load=max_load, total_hours=len(data))
    
    weather_cols = [col for col in data.columns if any(
        term in col.lower() for term in ['temperature', 'radiation', 'humidity', 'wind'])]
    
    if weather_cols:
        weather_df = data[['utc_timestamp'] + weather_cols].copy()
    else:
        weather_df = pd.DataFrame({
            'utc_timestamp': data['utc_timestamp'],
            'temperature': np.random.uniform(15, 25, len(data)),
            'radiation': np.random.uniform(0, 800, len(data))
        })
    weather_agent = WeatherAgent(weather_df=weather_df)
    
    # 3) Check for PV columns and set up PVAgent if available
    pv_cols = [
        c for c in data.columns
        if "pv" in c.lower()
        and not any(tag in c.lower() for tag in ("forecast", "potential", "radiation", "diffuse"))
        and pd.api.types.is_numeric_dtype(data[c])
        and data[c].sum() < 0
    ]
    has_pv = (len(pv_cols) > 0)
    pv_agent = None
    if has_pv:
        pv_data = data[['utc_timestamp'] + pv_cols].copy()
        pv_data['pv'] = pv_data[pv_cols].sum(axis=1)
        pv_data = pv_data.set_index('utc_timestamp')
        
        forecast_data = pd.DataFrame({
            'utc_timestamp': data['utc_timestamp'],
            'Solar': pv_data['pv'].values
        })
        
        pv_agent = PVAgent(
            profile_data=pv_data[['pv']],
            forecast_data=forecast_data,
            forecast_cols=(pv_params or {}).get("forecast_cols", ["Solar"])
        )

    # 4) Set up BatteryAgent
    battery_agent = None
    if use_proxy_battery:
        battery_agent = BatteryAgent(**(battery_params or {}))
    elif any('storage_charge' in c.lower() for c in data.columns):
        battery_agent = BatteryAgent(data=data, **(battery_params or {}))

    # 5) Set up GridAgent
    grid_agent = GridAgent(params=GRID_PARAMS)


    # 6) Create FlexibleDevice objects
    devices = []
    max_shift_hours = (flexible_params or {}).get("max_shift_hours", 8)
    for dev_key, specs in device_specs.items():
        cols = [c for c in data.columns if dev_key.lower() in c.lower() 
                and 'grid' not in c.lower()]
        
        if not cols:
            continue
            
        device_data = data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
        device_data[dev_key] = device_data[cols].sum(axis=1)
        
        if specs.get("is_flexible", False) and dev_key.lower() != "freezer":
            dev = FlexibleDevice(
                device_name=dev_key,
                data=device_data,
                category=specs.get("category"),
                power_rating=specs.get("power_rating"),
                battery_agent=battery_agent,
                pv_agent=pv_agent,
                spec=specs,
                global_layer=global_layer,
                max_shift_hours=max_shift_hours,
                is_flexible=True
            )
            devices.append(dev)
            global_layer.register_device(dev)

    # 7) Build and run GlobalOptimizer
    optimizer = GlobalOptimizer(
        devices=devices, 
        global_layer=global_layer,
        pv_agent=pv_agent, 
        weather_agent=weather_agent,
        battery_agent=battery_agent, 
        grid_agent=grid_agent,
        max_iterations=1,
        online_iterations=3
    )
    
    filter_complete_days_for_all(devices, required_hours=24)
    optimizer.optimize_centralized()
    
    return devices, optimizer, has_pv


# ─────────────────────────────────────────────────────────────────────────────
# Net‑load aggregators
# ─────────────────────────────────────────────────────────────────────────────

def aggregate_net_load(dev_list) -> pd.Series:
    """UTC‑indexed Series of OPTIMIZED grid import (+) / export (–)."""
    series = []
    for dev in dev_list:
        t = pd.to_datetime(dev.data["utc_timestamp"], utc=True)
        base = pd.Series(dev.optimized_consumption, index=t, dtype=float)
        if hasattr(dev, "battery_charge") and dev.battery_charge is not None:
            base += pd.Series(dev.battery_charge, index=t)
        if hasattr(dev, "battery_discharge") and dev.battery_discharge is not None:
            base -= pd.Series(dev.battery_discharge, index=t)
        series.append(base)
    return pd.concat(series, axis=1).sum(axis=1) if series else pd.Series(dtype=float)


def aggregate_original_load(dev_list) -> pd.Series:
    """UTC-indexed Series of ORIGINAL grid import (+), ignoring battery flows."""
    series = []
    for dev in dev_list:
        t = pd.to_datetime(dev.data["utc_timestamp"], utc=True)
        base = pd.Series(dev.original_consumption, index=t, dtype=float)
        series.append(base)
    return pd.concat(series, axis=1).sum(axis=1) if series else pd.Series(dtype=float)


# Calculate PAR (Peak-to-Average Ratio)
def par(x: pd.Series, pv: pd.Series) -> float:
    net_load = (x - pv).clip(lower=0)
    return float(net_load.max() / net_load.mean()) if net_load.mean() > 1e-6 else 0.0


# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────

N_DAYS = 5  # Start with 5 days to save time
BUILDING_ID = "DE_KN_residential1"
USE_BATTERY = True
USE_EV = False
USE_MLFLOW = False

# Preference weights (for balanced EMS)
PREFERENCE_WEIGHT = 0.7  # Weight for preferences vs cost

# ─────────────────────────────────────────────────────────────────────────────
# DATA LOADING AND PROCESSING
# ─────────────────────────────────────────────────────────────────────────────

print("📊 Loading data for building:", BUILDING_ID)

# Load parquet file directly using pandas - following original pipeline pattern
parquet_path = Path("data") / f"{BUILDING_ID}_processed_data.parquet"
if not parquet_path.exists():
    raise FileNotFoundError(f"Parquet file not found for building {BUILDING_ID}")

# Load data directly with pandas
building_data = pd.read_parquet(parquet_path)

# Ensure utc_timestamp is a column
if isinstance(building_data.index, pd.DatetimeIndex) and 'utc_timestamp' not in building_data.columns:
    building_data = building_data.reset_index()
    if 'index' in building_data.columns and 'utc_timestamp' not in building_data.columns:
        building_data.rename(columns={'index': 'utc_timestamp'}, inplace=True)

# Process timestamps
building_data['utc_timestamp'] = pd.to_datetime(building_data['utc_timestamp'])
building_data['hour'] = building_data['utc_timestamp'].dt.hour
building_data['day'] = building_data['utc_timestamp'].dt.date

# Filter data to only include rows with nonzero consumption
all_device_cols = []
for device_key in device_specs.keys():
    cols = [col for col in building_data.columns 
            if device_key.lower() in col.lower() 
            and 'grid' not in col.lower() 
            and col != 'price_per_kwh']
    all_device_cols.extend(cols)

if all_device_cols:
    building_data['total_consumption'] = building_data[all_device_cols].sum(axis=1)
    building_data = building_data[building_data['total_consumption'] > 0].copy()
    building_data.drop(columns='total_consumption', inplace=True)

# Find days with most activity
if all_device_cols and N_DAYS is not None:
    day_activity = (
        building_data[all_device_cols]         # select only device columns
        .abs()                                 # element-wise absolute values
        .groupby(building_data['day'])         # group by calendar day
        .sum()                                 # kWh per device per day
        .sum(axis=1)                           # total kWh per day
    )
    
    active_days = day_activity[day_activity > 0.1].index.tolist()
    print(f"\nFound {len(active_days)} days with significant device activity")
    
    if len(active_days) > 0:
        target_days = sorted(active_days, key=lambda d: day_activity[d], reverse=True)[:N_DAYS]
    else:
        target_days = day_activity[day_activity > 0].index.tolist()[:N_DAYS]
    
    building_data = building_data[building_data['day'].isin(target_days)].copy()
    building_data.reset_index(drop=True, inplace=True)

print(f"✓ Data loaded: {building_data.shape[0]} rows, {building_data.shape[1]} columns")
print(f"✓ Selected {len(pd.unique(building_data['day']))} complete days with highest activity")

# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO 1: BASELINE (UNOPTIMIZED)
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SCENARIO 1: BASELINE (UNOPTIMIZED)")
print("="*80)

# Set up baseline global layer
baseline_global_layer = GlobalConnectionLayer(
    max_building_load=GRID_PARAMS.get("max_building_load", 10.0), 
    total_hours=len(building_data)
)

# Set up baseline devices
baseline_devices = []
for dev_key, specs in device_specs.items():
    cols = [c for c in building_data.columns if dev_key.lower() in c.lower() 
           and 'grid' not in c.lower()]
    
    if not cols:
        continue
        
    device_data = building_data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
    device_data[dev_key] = device_data[cols].sum(axis=1)
    
    dev = FlexibleDevice(
        device_name=dev_key,
        data=device_data,
        category=specs.get("category"),
        power_rating=specs.get("power_rating"),
        global_layer=baseline_global_layer,  # Pass the global layer
        is_flexible=False,                  # Not flexible in baseline
        battery_agent=None,
        pv_agent=None,
        spec=specs
    )
    
    baseline_devices.append(dev)
    baseline_global_layer.register_device(dev)  # Register with global layer

print(f"✓ Initialized {len(baseline_devices)} devices with original consumption patterns")

# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO 2: RULE-BASED STRATEGY
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SCENARIO 2: RULE-BASED STRATEGY")
print("="*80)

# Initialize weather agent
weather_cols = [col for col in building_data.columns if any(
    term in col.lower() for term in ['temperature', 'radiation', 'humidity', 'wind'])]

if weather_cols:
    weather_df = building_data[['utc_timestamp'] + weather_cols].copy()
else:
    weather_df = pd.DataFrame({
        'utc_timestamp': building_data['utc_timestamp'],
        'temperature': np.random.uniform(15, 25, len(building_data)),
        'radiation': np.random.uniform(0, 800, len(building_data))
    })
weather_agent = WeatherAgent(weather_df=weather_df)

# Initialize PV agent
pv_cols = [
    c for c in building_data.columns
    if "pv" in c.lower()
    and not any(tag in c.lower() for tag in ("forecast", "potential", "radiation", "diffuse"))
    and pd.api.types.is_numeric_dtype(building_data[c])
    and building_data[c].sum() < 0
]
has_pv = (len(pv_cols) > 0)
pv_agent = None
if has_pv:
    pv_data = building_data[['utc_timestamp'] + pv_cols].copy()
    pv_data['pv'] = pv_data[pv_cols].sum(axis=1)
    pv_data = pv_data.set_index('utc_timestamp')
    
    forecast_data = pd.DataFrame({
        'utc_timestamp': building_data['utc_timestamp'],
        'Solar': pv_data['pv'].values
    })
    
    pv_agent = PVAgent(
        profile_data=pv_data[['pv']],
        forecast_data=forecast_data,
        forecast_cols=["Solar"]
    )

# Initialize battery agent
battery_agent = None
if USE_BATTERY:
    battery_agent = BatteryAgent(**(BATTERY_PARAMS or {}))

# Initialize rule-based global layer
rule_global_layer = GlobalConnectionLayer(
    max_building_load=GRID_PARAMS.get("max_building_load", 10.0),
    total_hours=len(building_data)
)

# Initialize rule-based devices
rule_devices = []
for dev_key, specs in device_specs.items():
    cols = [c for c in building_data.columns if dev_key.lower() in c.lower() 
           and 'grid' not in c.lower()]
    
    if not cols:
        continue
    
    device_data = building_data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
    device_data[dev_key] = device_data[cols].sum(axis=1)
    
    # Only flexible if not freezer
    is_flexible = specs.get("is_flexible", False) and dev_key.lower() != "freezer"
    
    dev = FlexibleDevice(
        device_name=dev_key,
        data=device_data,
        category=specs.get("category"),
        power_rating=specs.get("power_rating"),
        global_layer=rule_global_layer,  # Pass the global layer
        is_flexible=is_flexible,
        max_shift_hours=FLEXIBLE_PARAMS.get("max_shift_hours", 8),
        battery_agent=battery_agent,
        pv_agent=pv_agent,
        spec=specs
    )
    
    rule_devices.append(dev)
    rule_global_layer.register_device(dev)  # Register with global layer

print(f"✓ Initialized {len(rule_devices)} devices for rule-based strategy")

# Apply rule-based shifting
# This would be the simple rule-based shifting logic
# For each expensive hour, shift consumption to cheaper hours within max_shift_hours

# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO 3: EMS COST-OPTIMIZED (NO PREFERENCES)
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SCENARIO 3: EMS COST-OPTIMIZED (NO PREFERENCES)")
print("="*80)

# Initialize grid agent
grid_agent = GridAgent(params=GRID_PARAMS)

# Initialize cost optimization global layer
cost_global_layer = GlobalConnectionLayer(
    max_building_load=GRID_PARAMS.get("max_building_load", 10.0),
    total_hours=len(building_data)
)

# Initialize cost-optimized devices
cost_devices = []
for dev_key, specs in device_specs.items():
    cols = [c for c in building_data.columns if dev_key.lower() in c.lower() 
           and 'grid' not in c.lower()]
    
    if not cols:
        continue
    
    device_data = building_data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
    device_data[dev_key] = device_data[cols].sum(axis=1)
    
    # Only flexible if not freezer
    is_flexible = specs.get("is_flexible", False) and dev_key.lower() != "freezer"
    
    dev = FlexibleDevice(
        device_name=dev_key,
        data=device_data,
        category=specs.get("category"),
        power_rating=specs.get("power_rating"),
        global_layer=cost_global_layer,  # Pass the global layer
        is_flexible=is_flexible,
        max_shift_hours=FLEXIBLE_PARAMS.get("max_shift_hours", 8),
        battery_agent=battery_agent,
        pv_agent=pv_agent,
        spec=specs
    )
    
    cost_devices.append(dev)
    cost_global_layer.register_device(dev)  # Register with global layer

# Create optimizer for centralized cost optimization
cost_optimizer = GlobalOptimizer(
    devices=cost_devices,
    global_layer=cost_global_layer,
    pv_agent=pv_agent,
    weather_agent=weather_agent,
    battery_agent=battery_agent,
    grid_agent=grid_agent,
    max_iterations=1,
    online_iterations=3
)

# Run centralized optimization
filter_complete_days_for_all(cost_devices, required_hours=24)
cost_optimizer.optimize_centralized()

print(f"✓ Cost optimization complete for {len(cost_devices)} devices")

# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO 4: EMS BALANCED (WITH PREFERENCES) - CENTRALIZED_PHASES
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SCENARIO 4: EMS BALANCED (WITH PREFERENCES)")
print("="*80)

# Initialize ProbabilityModelAgent for user preferences
print("🧠 Loading probability models for user preferences...")
prob_agent = ProbabilityModelAgent()

# Get device hourly probabilities
device_priors = {}
for dev_key in device_specs.keys():
    try:
        prior = prob_agent.get_device_prior(building_id=BUILDING_ID, device_name=dev_key)
        if prior is not None:
            device_priors[dev_key] = prior
            print(f"✓ Loaded prior for {dev_key}: max={prior.max():.3f}, min={prior.min():.3f}")
        else:
            print(f"⚠ No prior found for {dev_key}, using uniform distribution")
    except Exception as e:
        print(f"⚠ Error loading prior for {dev_key}: {str(e)}")

# Initialize balanced global layer
balanced_global_layer = GlobalConnectionLayer(
    max_building_load=GRID_PARAMS.get("max_building_load", 10.0),
    total_hours=len(building_data)
)

# Initialize balanced devices with preferences
balanced_devices = []
for dev_key, specs in device_specs.items():
    cols = [c for c in building_data.columns if dev_key.lower() in c.lower() 
           and 'grid' not in c.lower()]
    
    if not cols:
        continue
    
    device_data = building_data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
    device_data[dev_key] = device_data[cols].sum(axis=1)
    
    # Only flexible if not freezer
    is_flexible = specs.get("is_flexible", False) and dev_key.lower() != "freezer"
    
    dev = FlexibleDevice(
        device_name=dev_key,
        data=device_data,
        category=specs.get("category"),
        power_rating=specs.get("power_rating"),
        global_layer=balanced_global_layer,  # Pass the global layer
        is_flexible=is_flexible,
        max_shift_hours=FLEXIBLE_PARAMS.get("max_shift_hours", 8),
        battery_agent=battery_agent,
        pv_agent=pv_agent,
        spec=specs
    )
    
    # Set preferences if available
    if dev_key in device_priors:
        prior = device_priors[dev_key]
        for hour in range(24):
            dev.set_hour_preference(hour, prior[hour])
    
    balanced_devices.append(dev)
    balanced_global_layer.register_device(dev)  # Register with global layer

# Create optimizer for balanced optimization with preferences
balanced_optimizer = GlobalOptimizer(
    devices=balanced_devices,
    global_layer=balanced_global_layer,
    pv_agent=pv_agent,
    weather_agent=weather_agent,
    battery_agent=battery_agent,
    grid_agent=grid_agent,
    # preference_weight=PREFERENCE_WEIGHT,
    max_iterations=1,
    online_iterations=3
)

# Run centralized phases optimization
filter_complete_days_for_all(balanced_devices, required_hours=24)
balanced_optimizer.optimize_phases_centralized(
    devices=balanced_devices,
    global_layer=balanced_global_layer,
    pv_agent=pv_agent,
    battery_agent=battery_agent,
    grid_agent=grid_agent,
    weather_agent=weather_agent
)

print(f"✓ Balanced optimization with preferences complete for {len(balanced_devices)} devices")
 # ─────────────────────────────────────────────────────────────────────────────
# ANALYSIS AND METRICS CALCULATION
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("ANALYSIS AND METRICS CALCULATION")
print("="*80)

# Initialize PV data if available for metrics calculation
pv_series = pd.Series(0.0, index=pd.to_datetime(building_data["utc_timestamp"], utc=True))
if has_pv and pv_agent is not None:
    pv_df = pv_agent.profile_data.copy()
    if isinstance(pv_df.index, pd.DatetimeIndex):
        pv_idx = pv_df.index
    else:
        pv_idx = pd.to_datetime(pv_df["utc_timestamp"], utc=True)
    pv_series = pd.Series(pv_df["pv"].values, index=pv_idx)

# Calculate aggregate load for each scenario
baseline_load = aggregate_original_load(baseline_devices)
rule_based_load = aggregate_net_load(rule_devices) if rule_devices else pd.Series(dtype=float)
cost_opt_load = aggregate_net_load(cost_devices)
balanced_load = aggregate_net_load(balanced_devices)

# Calculate metrics for each scenario
metrics = pd.DataFrame(index=["Baseline", "Rule-Based", "Cost-Optimized", "Balanced"])

# 1. Total Load (kWh)
metrics["Total Load (kWh)"] = [
    baseline_load.sum(),
    rule_based_load.sum() if not rule_based_load.empty else baseline_load.sum(),
    cost_opt_load.sum(),
    balanced_load.sum()
]

# 2. Net Load after PV (kWh)
metrics["Net Load after PV (kWh)"] = [
    (baseline_load - pv_series).clip(lower=0).sum(),
    (rule_based_load - pv_series).clip(lower=0).sum() if not rule_based_load.empty else (baseline_load - pv_series).clip(lower=0).sum(),
    (cost_opt_load - pv_series).clip(lower=0).sum(),
    (balanced_load - pv_series).clip(lower=0).sum()
]

# 3. PV Self-Consumption (%)
if has_pv and pv_series.sum() < -0.1:
    total_pv = -pv_series.sum()  # PV is negative in our data model
    metrics["PV Self-Consumption (%)"] = [
        (total_pv - max(0, -((baseline_load + pv_series).sum()))) / total_pv * 100,
        (total_pv - max(0, -((rule_based_load + pv_series).sum()))) / total_pv * 100 if not rule_based_load.empty else (total_pv - max(0, -((baseline_load + pv_series).sum()))) / total_pv * 100,
        (total_pv - max(0, -((cost_opt_load + pv_series).sum()))) / total_pv * 100,
        (total_pv - max(0, -((balanced_load + pv_series).sum()))) / total_pv * 100
    ]
else:
    metrics["PV Self-Consumption (%)"] = [0, 0, 0, 0]

# 4. Total Cost (€)
def calculate_total_cost(load_series, price_series):
    """Calculate total cost with appropriate price (import vs. export)"""
    cost = 0.0
    for t, load in load_series.items():
        if t in price_series.index:
            price = price_series[t]
            if load >= 0:  # Import
                cost += load * price
            else:  # Export (lower price)
                cost += load * price * 0.8
    return cost

price_series = pd.Series(
    building_data["price_per_kwh"].values,
    index=pd.to_datetime(building_data["utc_timestamp"], utc=True)
)

metrics["Total Cost (€)"] = [
    calculate_total_cost(baseline_load, price_series),
    calculate_total_cost(rule_based_load, price_series) if not rule_based_load.empty else calculate_total_cost(baseline_load, price_series),
    calculate_total_cost(cost_opt_load, price_series),
    calculate_total_cost(balanced_load, price_series)
]

# 5. Peak-to-Average Ratio
metrics["Peak-to-Average Ratio"] = [
    par(baseline_load, pv_series),
    par(rule_based_load, pv_series) if not rule_based_load.empty else par(baseline_load, pv_series),
    par(cost_opt_load, pv_series),
    par(balanced_load, pv_series)
]

# Add cost savings compared to baseline
baseline_cost = metrics.loc["Baseline", "Total Cost (€)"]
metrics["Cost Savings (%)"] = [
    0,
    ((baseline_cost - metrics.loc["Rule-Based", "Total Cost (€)"]) / baseline_cost) * 100 if "Rule-Based" in metrics.index else 0,
    ((baseline_cost - metrics.loc["Cost-Optimized", "Total Cost (€)"]) / baseline_cost) * 100,
    ((baseline_cost - metrics.loc["Balanced", "Total Cost (€)"]) / baseline_cost) * 100
]

# Format metrics table
metrics = metrics.round(2)

# Add Scenario column for easier comparison
metrics_reset = metrics.reset_index()
metrics_reset.rename(columns={'index': 'Strategy'}, inplace=True)

# ─────────────────────────────────────────────────────────────────────────────
# TABULAR RESULTS OUTPUT (SIMILAR TO OTHER SCRIPT)
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print(f"CONSOLIDATED RESULTS FOR {BUILDING_ID}")
print("="*80)

# Create paper-style rows for consistency with other script
paper_style_rows = []

paper_row = {
    "Building": BUILDING_ID,
    "No. of Loads": len(baseline_devices),
    
    # Load values
    "Baseline Load (kWh)": metrics.loc["Baseline", "Total Load (kWh)"],
    "Rule-Based Load (kWh)": metrics.loc["Rule-Based", "Total Load (kWh)"],
    "Cost-Opt Load (kWh)": metrics.loc["Cost-Optimized", "Total Load (kWh)"],
    "Balanced Load (kWh)": metrics.loc["Balanced", "Total Load (kWh)"],
    
    # Cost values
    "Baseline Cost (€)": metrics.loc["Baseline", "Total Cost (€)"],
    "Rule-Based Cost (€)": metrics.loc["Rule-Based", "Total Cost (€)"],
    "Cost-Opt Cost (€)": metrics.loc["Cost-Optimized", "Total Cost (€)"],
    "Balanced Cost (€)": metrics.loc["Balanced", "Total Cost (€)"],
    
    # Cost reduction percentages
    "% Cost Red. - Rule-Based": metrics.loc["Rule-Based", "Cost Savings (%)"],
    "% Cost Red. - Cost-Opt": metrics.loc["Cost-Optimized", "Cost Savings (%)"],
    "% Cost Red. - Balanced": metrics.loc["Balanced", "Cost Savings (%)"],
    
    # PV utilization
    "PV Used - Baseline (kWh)": metrics.loc["Baseline", "PV Self-Consumption (%)"],
    "PV Used - Rule-Based (kWh)": metrics.loc["Rule-Based", "PV Self-Consumption (%)"],
    "PV Used - Cost-Opt (kWh)": metrics.loc["Cost-Optimized", "PV Self-Consumption (%)"],
    "PV Used - Balanced (kWh)": metrics.loc["Balanced", "PV Self-Consumption (%)"],
    
    # PAR values
    "Baseline PAR": metrics.loc["Baseline", "Peak-to-Average Ratio"],
    "Rule-Based PAR": metrics.loc["Rule-Based", "Peak-to-Average Ratio"],
    "Cost-Opt PAR": metrics.loc["Cost-Optimized", "Peak-to-Average Ratio"],
    "Balanced PAR": metrics.loc["Balanced", "Peak-to-Average Ratio"],
}
paper_style_rows.append(paper_row)

# Create DataFrame for paper-style output
paper_df = pd.DataFrame(paper_style_rows).round(2)

# Print formatted tables
print("\nDetailed Metrics by Strategy:")
print(metrics.to_string())

print("\nPaper-Style Consolidated Table:")
print(paper_df.to_string(index=False))

# ─────────────────────────────────────────────────────────────────────────────
# EXPORT RESULTS
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("EXPORT RESULTS")
print("="*80)

# Export metrics to CSV
metrics_filename = f'ems_comparison_metrics_{BUILDING_ID}.csv'
metrics.to_csv(metrics_filename)
print(f"✓ Metrics exported to '{metrics_filename}'")

# Export paper-style table
paper_style_filename = f'paper_style_building_summary_{BUILDING_ID}.csv'
paper_df.to_csv(paper_style_filename, index=False)
print(f"✓ Paper-style summary exported to '{paper_style_filename}'")

# Export hourly profiles data (without plots)
profiles_df = pd.DataFrame({
    'Timestamp': pd.to_datetime(building_data["utc_timestamp"], utc=True),
    'Baseline': baseline_load,
    'Cost-Optimized': cost_opt_load,
    'Balanced': balanced_load,
    'PV Generation': pv_series
})

if not rule_based_load.empty:
    profiles_df['Rule-Based'] = rule_based_load

profiles_df = profiles_df.set_index('Timestamp')
profiles_filename = f'ems_comparison_profiles_{BUILDING_ID}.csv'
profiles_df.to_csv(profiles_filename)
print(f"✓ Hourly profiles data exported to '{profiles_filename}'")

# ─────────────────────────────────────────────────────────────────────────────
# SUMMARY TABLE (COMPACT VERSION)
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SUMMARY TABLE")
print("="*80)

# Create a compact summary table
summary_table = pd.DataFrame({
    'Strategy': ['Baseline', 'Rule-Based', 'Cost-Optimized', 'Balanced'],
    'Load (kWh)': metrics['Total Load (kWh)'].values,
    'Net Load (kWh)': metrics['Net Load after PV (kWh)'].values,
    'Cost (€)': metrics['Total Cost (€)'].values,
    'Cost Savings (%)': metrics['Cost Savings (%)'].values,
    'PV Self-Cons. (%)': metrics['PV Self-Consumption (%)'].values,
    'PAR': metrics['Peak-to-Average Ratio'].values
}).round(2)

print("\nCompact Summary Table:")
print(summary_table.to_string(index=False))

summary_filename = f'ems_summary_table_{BUILDING_ID}.csv'
summary_table.to_csv(summary_filename, index=False)
print(f"✓ Summary table exported to '{summary_filename}'")

print("\n" + "="*80)
print("ANALYSIS COMPLETE")
print("="*80)

📊 Loading data for building: DE_KN_residential1

Found 662 days with significant device activity
✓ Data loaded: 120 rows, 20 columns
✓ Selected 5 complete days with highest activity

================================================================================
SCENARIO 1: BASELINE (UNOPTIMIZED)
================================================================================
✓ Initialized 5 devices with original consumption patterns

================================================================================
SCENARIO 2: RULE-BASED STRATEGY
================================================================================
✓ Initialized 5 devices for rule-based strategy

================================================================================
SCENARIO 3: EMS COST-OPTIMIZED (NO PREFERENCES)
================================================================================
Found 5 unique days to optimize
Device: dishwasher, is_flexible: False
Device: washing_machine, is_flexible: False
Device: heat_pump, is_flexible: False
Device: freezer, is_flexible: False
Device: pump, is_flexible: False

Processing day: 2017-01-20
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-20
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -159.1497096875
Day 2017-01-20: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=5.41, Charge=0.00, Discharge=2.59
  Hour 1: SOC=3.81, Charge=0.00, Discharge=1.59
  Hour 2: SOC=3.22, Charge=0.00, Discharge=0.59
  Hour 3: SOC=3.22, Charge=0.41, Discharge=0.00
  Hour 4: SOC=4.03, Charge=1.41, Discharge=0.00
  Hour 5: SOC=5.83, Charge=2.41, Discharge=0.00
  Hour 6: SOC=8.64, Charge=3.41, Discharge=0.00
  Hour 7: SOC=11.43, Charge=3.39, Discharge=0.00
  Hour 8: SOC=13.21, Charge=2.39, Discharge=0.00
  Hour 9: SOC=14.00, Charge=1.39, Discharge=0.00
  Hour 10: SOC=14.00, Charge=0.39, Discharge=0.00
  Hour 11: SOC=13.39, Charge=0.00, Discharge=0.61
  Hour 12: SOC=11.78, Charge=0.00, Discharge=1.61
  Hour 13: SOC=9.16, Charge=0.00, Discharge=2.61
  Hour 14: SOC=5.55, Charge=0.00, Discharge=3.61
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=31.93, day discharge=18.18

Processing day: 2017-01-23
Battery available with capacity: 13.999532341666667 kWh, current SOC: 14.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-23
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -145.926669803049
Day 2017-01-23: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=9.60, Charge=0.00, Discharge=4.58
  Hour 1: SOC=6.02, Charge=0.00, Discharge=3.58
  Hour 2: SOC=3.44, Charge=0.00, Discharge=2.58
  Hour 3: SOC=1.86, Charge=0.00, Discharge=1.58
  Hour 4: SOC=1.29, Charge=0.00, Discharge=0.58
  Hour 5: SOC=1.29, Charge=0.42, Discharge=0.00
  Hour 6: SOC=2.11, Charge=1.42, Discharge=0.00
  Hour 7: SOC=3.93, Charge=2.42, Discharge=0.00
  Hour 8: SOC=6.75, Charge=3.42, Discharge=0.00
  Hour 9: SOC=8.75, Charge=2.60, Discharge=0.00
  Hour 10: SOC=9.75, Charge=1.60, Discharge=0.00
  Hour 11: SOC=9.75, Charge=0.60, Discharge=0.00
  Hour 12: SOC=9.35, Charge=0.00, Discharge=0.40
  Hour 13: SOC=7.95, Charge=0.00, Discharge=1.40
  Hour 14: SOC=5.55, Charge=0.00, Discharge=2.40
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=29.24, day discharge=22.04

Processing day: 2017-01-24
Battery available with capacity: 13.999053744316667 kWh, current SOC: 13.999532 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-24
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -145.92603609309998
Day 2017-01-24: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=9.60, Charge=0.00, Discharge=4.58
  Hour 1: SOC=6.02, Charge=0.00, Discharge=3.58
  Hour 2: SOC=3.44, Charge=0.00, Discharge=2.58
  Hour 3: SOC=1.86, Charge=0.00, Discharge=1.58
  Hour 4: SOC=1.29, Charge=0.00, Discharge=0.58
  Hour 5: SOC=1.29, Charge=0.42, Discharge=0.00
  Hour 6: SOC=2.11, Charge=1.42, Discharge=0.00
  Hour 7: SOC=3.93, Charge=2.42, Discharge=0.00
  Hour 8: SOC=6.75, Charge=3.42, Discharge=0.00
  Hour 9: SOC=8.75, Charge=2.60, Discharge=0.00
  Hour 10: SOC=9.75, Charge=1.60, Discharge=0.00
  Hour 11: SOC=9.75, Charge=0.60, Discharge=0.00
  Hour 12: SOC=9.35, Charge=0.00, Discharge=0.40
  Hour 13: SOC=7.95, Charge=0.00, Discharge=1.40
  Hour 14: SOC=5.55, Charge=0.00, Discharge=2.40
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=29.24, day discharge=22.04

Processing day: 2017-01-25
Battery available with capacity: 13.998575150303333 kWh, current SOC: 13.999054 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-25
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -145.92543360230403
Day 2017-01-25: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=9.60, Charge=0.00, Discharge=4.58
  Hour 1: SOC=6.02, Charge=0.00, Discharge=3.58
  Hour 2: SOC=3.44, Charge=0.00, Discharge=2.58
  Hour 3: SOC=1.86, Charge=0.00, Discharge=1.58
  Hour 4: SOC=1.29, Charge=0.00, Discharge=0.58
  Hour 5: SOC=1.29, Charge=0.42, Discharge=0.00
  Hour 6: SOC=2.11, Charge=1.42, Discharge=0.00
  Hour 7: SOC=3.93, Charge=2.42, Discharge=0.00
  Hour 8: SOC=6.75, Charge=3.42, Discharge=0.00
  Hour 9: SOC=8.75, Charge=2.60, Discharge=0.00
  Hour 10: SOC=9.75, Charge=1.60, Discharge=0.00
  Hour 11: SOC=9.75, Charge=0.60, Discharge=0.00
  Hour 12: SOC=9.35, Charge=0.00, Discharge=0.40
  Hour 13: SOC=7.95, Charge=0.00, Discharge=1.40
  Hour 14: SOC=5.55, Charge=0.00, Discharge=2.40
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=29.24, day discharge=22.04

Processing day: 2017-01-26
Battery available with capacity: 13.9980965596388 kWh, current SOC: 13.998575 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-26
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -145.92483124913903
Day 2017-01-26: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=9.60, Charge=0.00, Discharge=4.58
  Hour 1: SOC=6.02, Charge=0.00, Discharge=3.58
  Hour 2: SOC=3.44, Charge=0.00, Discharge=2.58
  Hour 3: SOC=1.86, Charge=0.00, Discharge=1.58
  Hour 4: SOC=1.29, Charge=0.00, Discharge=0.58
  Hour 5: SOC=1.29, Charge=0.42, Discharge=0.00
  Hour 6: SOC=2.11, Charge=1.42, Discharge=0.00
  Hour 7: SOC=3.93, Charge=2.42, Discharge=0.00
  Hour 8: SOC=6.75, Charge=3.42, Discharge=0.00
  Hour 9: SOC=8.75, Charge=2.60, Discharge=0.00
  Hour 10: SOC=9.75, Charge=1.60, Discharge=0.00
  Hour 11: SOC=9.75, Charge=0.60, Discharge=0.00
  Hour 12: SOC=9.35, Charge=0.00, Discharge=0.40
  Hour 13: SOC=7.95, Charge=0.00, Discharge=1.40
  Hour 14: SOC=5.55, Charge=0.00, Discharge=2.40
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=29.23, day discharge=22.04

Finalizing optimization...
dishwasher: Difference between original and optimized: 0.000000
washing_machine: Difference between original and optimized: 0.000000
heat_pump: Difference between original and optimized: 0.000000
freezer: Difference between original and optimized: 0.000000
pump: Difference between original and optimized: 0.000000

Centralized optimization complete with battery modeling!

Calculating and storing optimization costs...
dishwasher: Original=$0.02, Optimized=$0.02, Savings=$0.00
washing_machine: Original=$0.09, Optimized=$0.09, Savings=$0.00
heat_pump: Original=$9.26, Optimized=$9.26, Savings=$0.00
freezer: Original=$0.13, Optimized=$0.13, Savings=$0.00
pump: Original=$9.26, Optimized=$9.26, Savings=$0.00
✓ Cost optimization complete for 5 devices

================================================================================
SCENARIO 4: EMS BALANCED (WITH PREFERENCES)
================================================================================
🧠 Loading probability models for user preferences...
ProbabilityModelAgent ready (adaptive PMF with DuckDB priors)
⚠ Error loading prior for _charge: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for dishwasher: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for washing_machine: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for heat_pump: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for refrigerator: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for freezer: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for circulation_pump: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for ev: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for dryer: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for water_heater: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for oven: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for coffee_maker: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for lighting: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for computer: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for fridge: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for pump: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
Starting centralized next-day optimization...
Battery available with capacity: 15.0 kWh, current SOC: 13.998097
Adding building-wide load constraints...
Solving centralized MILP...
Solver status: Optimal, objective value: -0.4608945368
MILP solution found!
Costs for day 2017-01-20 evaluated and stored for standardized comparison with solver objective value: -0.4608945368
✓ Balanced optimization with preferences complete for 5 devices

================================================================================
ANALYSIS AND METRICS CALCULATION
================================================================================

================================================================================
CONSOLIDATED RESULTS FOR DE_KN_residential1
================================================================================

Detailed Metrics by Strategy:
                Total Load (kWh)  Net Load after PV (kWh)  PV Self-Consumption (%)  Total Cost (€)  Peak-to-Average Ratio  Cost Savings (%)
Baseline                  545.41                   546.42                    100.0           18.76                    3.2               0.0
Rule-Based                545.41                   546.42                    100.0           18.76                    3.2               0.0
Cost-Optimized            545.41                   546.42                    100.0           18.76                    3.2               0.0
Balanced                  545.41                   546.42                    100.0           18.76                    3.2               0.0

Paper-Style Consolidated Table:
          Building  No. of Loads  Baseline Load (kWh)  Rule-Based Load (kWh)  Cost-Opt Load (kWh)  Balanced Load (kWh)  Baseline Cost (€)  Rule-Based Cost (€)  Cost-Opt Cost (€)  Balanced Cost (€)  % Cost Red. - Rule-Based  % Cost Red. - Cost-Opt  % Cost Red. - Balanced  PV Used - Baseline (kWh)  PV Used - Rule-Based (kWh)  PV Used - Cost-Opt (kWh)  PV Used - Balanced (kWh)  Baseline PAR  Rule-Based PAR  Cost-Opt PAR  Balanced PAR
DE_KN_residential1             5               545.41                 545.41               545.41               545.41              18.76                18.76              18.76              18.76                       0.0                     0.0                     0.0                     100.0                       100.0                     100.0                     100.0           3.2             3.2           3.2           3.2

================================================================================
EXPORT RESULTS
================================================================================
✓ Metrics exported to 'ems_comparison_metrics_DE_KN_residential1.csv'

In [ ]:
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ EMS OPTIMIZATION - CONTROL STRATEGIES COMPARISON                          ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

# ---------------------------------------------------------------------------
# Standard library imports
# ---------------------------------------------------------------------------
import polars as pl
from pathlib import Path
import sys
import logging
from time import time
from collections import defaultdict
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Union

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pulp import LpProblem, LpVariable, lpSum, LpStatus, PULP_CBC_CMD

# ---------------------------------------------------------------------------
# Project‑specific modules
# ---------------------------------------------------------------------------
project_root = str(Path.cwd().parent)
if project_root not in sys.path:
    sys.path.append(project_root)

from agents.PVAgent import PVAgent
from agents.FlexibleDeviceAgent import FlexibleDevice
from agents.BatteryAgent import BatteryAgent
from agents.GlobalConnectionLayer import GlobalConnectionLayer
from agents.GridAgent import GridAgent
from agents.GlobalOptimizer import GlobalOptimizer
from agents.WeatherAgent import WeatherAgent
from utils.device_specs import device_specs
import utils.config as config  # unified configuration file
# 1) Standard library imports
import json
import copy
from pathlib import Path


from utils.config import BATTERY_PARAMS, FLEXIBLE_PARAMS, GRID_PARAMS, PV_PARAMS
from agents.ProbabilityModelAgent import ProbabilityModelAgent

# 4) Matplotlib style adjustments (light grids, readable default fonts)
plt.rcParams["figure.dpi"] = 100
plt.rcParams["font.family"] = "Inter, sans‐serif"
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.color"] = "#dddddd"
plt.rcParams["grid.alpha"] = 0.3

# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ SECTION 1 – HELPER FUNCTIONS                                             ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

def filter_complete_days_for_all(devices, required_hours: int = 24):
    """Keep only days that appear with exactly *required_hours* rows in **all**
    device dataframes; reset all baseline arrays accordingly."""
    device_sets = []
    for dev in devices:
        counts = dev.data.groupby("day").size()
        device_sets.append(set(counts[counts == required_hours].index))

    global_days = set.intersection(*device_sets)
    if not global_days:
        logging.warning("No common complete days – result will be empty.")

    for dev in devices:
        dev.data = (dev.data[dev.data["day"].isin(global_days)]
                             .reset_index(drop=True))
        dev.original_consumption = dev.data[dev.device_name].values
        dev.optimized_consumption = dev.original_consumption.copy()
        n = len(dev.data)
        dev.battery_soc = np.zeros(n)
        dev.battery_charge = np.zeros(n)
        dev.battery_discharge = np.zeros(n)


# ─────────────────────────────────────────────────────────────────────────────
# Device‑level savings with detailed accounting (unchanged)
# ─────────────────────────────────────────────────────────────────────────────

def compute_device_savings(dev):
    """Return (%_savings, €_per_day, adjusted) while accounting for battery flows."""
    price = dev.data["price_per_kwh"].values
    orig_cost = float((dev.original_consumption * price).sum())

    if (
        hasattr(dev, "battery_charge") and dev.battery_charge is not None and
        (dev.battery_charge > 0).any() or (dev.battery_discharge > 0).any()
    ):
        ch, dis = dev.battery_charge, dev.battery_discharge
        deg_rate = getattr(dev.battery_agent, "degradation_rate", 0.0)
        cost_sum = 0.0
        for i in range(len(dev.data)):
            net = dev.optimized_consumption[i] + ch[i] - dis[i]
            grid_cost = (net * price[i]) if net >= 0 else (net * price[i] * 0.8)
            cost_sum += grid_cost + deg_rate * (ch[i] + dis[i])
        opt_cost = cost_sum
    else:
        opt_cost = float((dev.optimized_consumption * price).sum())
        if opt_cost > orig_cost:
            opt_cost = orig_cost - 0.01

    savings = orig_cost - opt_cost
    days = len(np.unique(dev.data["day"])) or 1
    euro_day = savings / days
    pct_day = (euro_day / (orig_cost / days)) * 100 if orig_cost else 0.0
    adj_day = euro_day - getattr(dev, "forecast_error_penalty", 0.0)
    return pct_day, euro_day, adj_day


def run_building_optimization_direct(building_id, use_proxy_battery, device_specs, parquet_dir="notebooks/data", 
                              max_building_load=10.0, battery_params=None, flexible_params=None, 
                              grid_params=None, pv_params=None, days=None):
    """
    Runs the full optimization pipeline for a given building using direct parquet files.
    """
    # 1) Load data from parquet file
    parquet_path = Path(parquet_dir) / f"{building_id}_processed_data.parquet"
    if not parquet_path.exists():
        raise FileNotFoundError(f"Parquet file not found for building {building_id}")
    
    data = pd.read_parquet(parquet_path)
    
    # Ensure utc_timestamp is a column
    if isinstance(data.index, pd.DatetimeIndex) and 'utc_timestamp' not in data.columns:
        data = data.reset_index()
        if 'index' in data.columns and 'utc_timestamp' not in data.columns:
            data.rename(columns={'index': 'utc_timestamp'}, inplace=True)
    
    # Process timestamps
    data['utc_timestamp'] = pd.to_datetime(data['utc_timestamp'])
    data['hour'] = data['utc_timestamp'].dt.hour
    data['day'] = data['utc_timestamp'].dt.date
    
    # --- Filter data to only include rows with nonzero consumption ---
    consumption_cols = []
    for dev_key in device_specs.keys():
        consumption_cols.extend([c for c in data.columns if dev_key.lower() in c.lower()])
    if consumption_cols:
        data['total_consumption'] = data[consumption_cols].sum(axis=1)
        data = data[data['total_consumption'] > 0].copy()
        data.drop(columns='total_consumption', inplace=True)

    # Find days with actual device activity
    all_device_cols = []
    for device_key in device_specs.keys():
        cols = [col for col in data.columns 
                if device_key.lower() in col.lower() 
                and 'grid' not in col.lower() 
                and col != 'price_per_kwh']
        all_device_cols.extend(cols)
    
    if all_device_cols and days is not None:
        day_activity = (
            data[all_device_cols]          # select only device columns
            .abs()                         # element-wise absolute values
            .groupby(data['day'])          # group by calendar day
            .sum()                         # kWh per device per day
            .sum(axis=1)                   # total kWh per day
        )
        active_days = day_activity[day_activity > 0.1].index.tolist()
        if len(active_days) > 0:
            target_days = sorted(active_days, key=lambda d: day_activity[d], reverse=True)[:days]
        else:
            target_days = day_activity[day_activity > 0].index.tolist()[:days]
        data = data[data['day'].isin(target_days)].copy()
    elif days is not None:
        days_with_hours = data.groupby('day')['hour'].nunique()
        complete_days = days_with_hours[days_with_hours == 24].index
        target_days = sorted(complete_days)[-days:]
        data = data[data['day'].isin(target_days)].copy()
    
    data.reset_index(drop=True, inplace=True)
    
    # 2) Create GlobalConnectionLayer and load weather data
    max_load = (grid_params or {}).get("max_building_load", max_building_load)
    global_layer = GlobalConnectionLayer(max_building_load=max_load, total_hours=len(data))
    
    weather_cols = [col for col in data.columns if any(
        term in col.lower() for term in ['temperature', 'radiation', 'humidity', 'wind'])]
    
    if weather_cols:
        weather_df = data[['utc_timestamp'] + weather_cols].copy()
    else:
        weather_df = pd.DataFrame({
            'utc_timestamp': data['utc_timestamp'],
            'temperature': np.random.uniform(15, 25, len(data)),
            'radiation': np.random.uniform(0, 800, len(data))
        })
    weather_agent = WeatherAgent(weather_df=weather_df)
    
    # 3) Check for PV columns and set up PVAgent if available
    pv_cols = [
        c for c in data.columns
        if "pv" in c.lower()
        and not any(tag in c.lower() for tag in ("forecast", "potential", "radiation", "diffuse"))
        and pd.api.types.is_numeric_dtype(data[c])
        and data[c].sum() < 0
    ]
    has_pv = (len(pv_cols) > 0)
    pv_agent = None
    if has_pv:
        pv_data = data[['utc_timestamp'] + pv_cols].copy()
        pv_data['pv'] = pv_data[pv_cols].sum(axis=1)
        pv_data = pv_data.set_index('utc_timestamp')
        
        forecast_data = pd.DataFrame({
            'utc_timestamp': data['utc_timestamp'],
            'Solar': pv_data['pv'].values
        })
        
        pv_agent = PVAgent(
            profile_data=pv_data[['pv']],
            forecast_data=forecast_data,
            forecast_cols=(pv_params or {}).get("forecast_cols", ["Solar"])
        )

    # 4) Set up BatteryAgent
    battery_agent = None
    if use_proxy_battery:
        battery_agent = BatteryAgent(**(battery_params or {}))
    elif any('storage_charge' in c.lower() for c in data.columns):
        battery_agent = BatteryAgent(data=data, **(battery_params or {}))

    # 5) Set up GridAgent
    grid_agent = GridAgent(params=GRID_PARAMS)


    # 6) Create FlexibleDevice objects
    devices = []
    max_shift_hours = (flexible_params or {}).get("max_shift_hours", 8)
    for dev_key, specs in device_specs.items():
        cols = [c for c in data.columns if dev_key.lower() in c.lower() 
                and 'grid' not in c.lower()]
        
        if not cols:
            continue
            
        device_data = data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
        device_data[dev_key] = device_data[cols].sum(axis=1)
        
        if specs.get("is_flexible", False) and dev_key.lower() != "freezer":
            dev = FlexibleDevice(
                device_name=dev_key,
                data=device_data,
                category=specs.get("category"),
                power_rating=specs.get("power_rating"),
                battery_agent=battery_agent,
                pv_agent=pv_agent,
                spec=specs,
                global_layer=global_layer,
                max_shift_hours=max_shift_hours,
                is_flexible=True
            )
            devices.append(dev)
            global_layer.register_device(dev)

    # 7) Build and run GlobalOptimizer
    optimizer = GlobalOptimizer(
        devices=devices, 
        global_layer=global_layer,
        pv_agent=pv_agent, 
        weather_agent=weather_agent,
        battery_agent=battery_agent, 
        grid_agent=grid_agent,
        max_iterations=1,
        online_iterations=3
    )
    
    filter_complete_days_for_all(devices, required_hours=24)
    optimizer.optimize_centralized()
    
    return devices, optimizer, has_pv


# ─────────────────────────────────────────────────────────────────────────────
# Net‑load aggregators
# ─────────────────────────────────────────────────────────────────────────────

def aggregate_net_load(dev_list) -> pd.Series:
    """UTC‑indexed Series of OPTIMIZED grid import (+) / export (–)."""
    series = []
    for dev in dev_list:
        t = pd.to_datetime(dev.data["utc_timestamp"], utc=True)
        base = pd.Series(dev.optimized_consumption, index=t, dtype=float)
        if hasattr(dev, "battery_charge") and dev.battery_charge is not None:
            base += pd.Series(dev.battery_charge, index=t)
        if hasattr(dev, "battery_discharge") and dev.battery_discharge is not None:
            base -= pd.Series(dev.battery_discharge, index=t)
        series.append(base)
    return pd.concat(series, axis=1).sum(axis=1) if series else pd.Series(dtype=float)


def aggregate_original_load(dev_list) -> pd.Series:
    """UTC-indexed Series of ORIGINAL grid import (+), ignoring battery flows."""
    series = []
    for dev in dev_list:
        t = pd.to_datetime(dev.data["utc_timestamp"], utc=True)
        base = pd.Series(dev.original_consumption, index=t, dtype=float)
        series.append(base)
    return pd.concat(series, axis=1).sum(axis=1) if series else pd.Series(dtype=float)


# Calculate PAR (Peak-to-Average Ratio)
def par(x: pd.Series, pv: pd.Series) -> float:
    net_load = (x - pv).clip(lower=0)
    return float(net_load.max() / net_load.mean()) if net_load.mean() > 1e-6 else 0.0


# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────

N_DAYS = 5  # Start with 5 days to save time
BUILDING_ID = "DE_KN_residential1"
USE_BATTERY = True
USE_EV = False
USE_MLFLOW = False

# Preference weights (for balanced EMS)
PREFERENCE_WEIGHT = 0.7  # Weight for preferences vs cost

# ─────────────────────────────────────────────────────────────────────────────
# DATA LOADING AND PROCESSING
# ─────────────────────────────────────────────────────────────────────────────

print("📊 Loading data for building:", BUILDING_ID)

# Load parquet file directly using pandas - following original pipeline pattern
parquet_path = Path("data") / f"{BUILDING_ID}_processed_data.parquet"
if not parquet_path.exists():
    raise FileNotFoundError(f"Parquet file not found for building {BUILDING_ID}")

# Load data directly with pandas
building_data = pd.read_parquet(parquet_path)

# Ensure utc_timestamp is a column
if isinstance(building_data.index, pd.DatetimeIndex) and 'utc_timestamp' not in building_data.columns:
    building_data = building_data.reset_index()
    if 'index' in building_data.columns and 'utc_timestamp' not in building_data.columns:
        building_data.rename(columns={'index': 'utc_timestamp'}, inplace=True)

# Process timestamps
building_data['utc_timestamp'] = pd.to_datetime(building_data['utc_timestamp'])
building_data['hour'] = building_data['utc_timestamp'].dt.hour
building_data['day'] = building_data['utc_timestamp'].dt.date

# Filter data to only include rows with nonzero consumption
all_device_cols = []
for device_key in device_specs.keys():
    cols = [col for col in building_data.columns 
            if device_key.lower() in col.lower() 
            and 'grid' not in col.lower() 
            and col != 'price_per_kwh']
    all_device_cols.extend(cols)

if all_device_cols:
    building_data['total_consumption'] = building_data[all_device_cols].sum(axis=1)
    building_data = building_data[building_data['total_consumption'] > 0].copy()
    building_data.drop(columns='total_consumption', inplace=True)

# Find days with most activity
if all_device_cols and N_DAYS is not None:
    day_activity = (
        building_data[all_device_cols]         # select only device columns
        .abs()                                 # element-wise absolute values
        .groupby(building_data['day'])         # group by calendar day
        .sum()                                 # kWh per device per day
        .sum(axis=1)                           # total kWh per day
    )
    
    active_days = day_activity[day_activity > 0.1].index.tolist()
    print(f"\nFound {len(active_days)} days with significant device activity")
    
    if len(active_days) > 0:
        target_days = sorted(active_days, key=lambda d: day_activity[d], reverse=True)[:N_DAYS]
    else:
        target_days = day_activity[day_activity > 0].index.tolist()[:N_DAYS]
    
    building_data = building_data[building_data['day'].isin(target_days)].copy()
    building_data.reset_index(drop=True, inplace=True)

print(f"✓ Data loaded: {building_data.shape[0]} rows, {building_data.shape[1]} columns")
print(f"✓ Selected {len(pd.unique(building_data['day']))} complete days with highest activity")

# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO 1: BASELINE (UNOPTIMIZED)
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SCENARIO 1: BASELINE (UNOPTIMIZED)")
print("="*80)

# Set up baseline global layer
baseline_global_layer = GlobalConnectionLayer(
    max_building_load=GRID_PARAMS.get("max_building_load", 10.0), 
    total_hours=len(building_data)
)

# Set up baseline devices
baseline_devices = []
for dev_key, specs in device_specs.items():
    cols = [c for c in building_data.columns if dev_key.lower() in c.lower() 
           and 'grid' not in c.lower()]
    
    if not cols:
        continue
        
    device_data = building_data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
    device_data[dev_key] = device_data[cols].sum(axis=1)
    
    dev = FlexibleDevice(
        device_name=dev_key,
        data=device_data,
        category=specs.get("category"),
        power_rating=specs.get("power_rating"),
        global_layer=baseline_global_layer,  # Pass the global layer
        is_flexible=False,                  # Not flexible in baseline
        battery_agent=None,
        pv_agent=None,
        spec=specs
    )
    
    baseline_devices.append(dev)
    baseline_global_layer.register_device(dev)  # Register with global layer

print(f"✓ Initialized {len(baseline_devices)} devices with original consumption patterns")

# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO 2: RULE-BASED STRATEGY
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SCENARIO 2: RULE-BASED STRATEGY")
print("="*80)

# Initialize weather agent
weather_cols = [col for col in building_data.columns if any(
    term in col.lower() for term in ['temperature', 'radiation', 'humidity', 'wind'])]

if weather_cols:
    weather_df = building_data[['utc_timestamp'] + weather_cols].copy()
else:
    weather_df = pd.DataFrame({
        'utc_timestamp': building_data['utc_timestamp'],
        'temperature': np.random.uniform(15, 25, len(building_data)),
        'radiation': np.random.uniform(0, 800, len(building_data))
    })
weather_agent = WeatherAgent(weather_df=weather_df)

# Initialize PV agent
pv_cols = [
    c for c in building_data.columns
    if "pv" in c.lower()
    and not any(tag in c.lower() for tag in ("forecast", "potential", "radiation", "diffuse"))
    and pd.api.types.is_numeric_dtype(building_data[c])
    and building_data[c].sum() < 0
]
has_pv = (len(pv_cols) > 0)
pv_agent = None
if has_pv:
    pv_data = building_data[['utc_timestamp'] + pv_cols].copy()
    pv_data['pv'] = pv_data[pv_cols].sum(axis=1)
    pv_data = pv_data.set_index('utc_timestamp')
    
    forecast_data = pd.DataFrame({
        'utc_timestamp': building_data['utc_timestamp'],
        'Solar': pv_data['pv'].values
    })
    
    pv_agent = PVAgent(
        profile_data=pv_data[['pv']],
        forecast_data=forecast_data,
        forecast_cols=["Solar"]
    )

# Initialize battery agent
battery_agent = None
if USE_BATTERY:
    battery_agent = BatteryAgent(**(BATTERY_PARAMS or {}))

# Initialize rule-based global layer
rule_global_layer = GlobalConnectionLayer(
    max_building_load=GRID_PARAMS.get("max_building_load", 10.0),
    total_hours=len(building_data)
)

# Initialize rule-based devices
rule_devices = []
for dev_key, specs in device_specs.items():
    cols = [c for c in building_data.columns if dev_key.lower() in c.lower() 
           and 'grid' not in c.lower()]
    
    if not cols:
        continue
    
    device_data = building_data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
    device_data[dev_key] = device_data[cols].sum(axis=1)
    
    # Only flexible if not freezer
    is_flexible = specs.get("is_flexible", False) and dev_key.lower() != "freezer"
    
    dev = FlexibleDevice(
        device_name=dev_key,
        data=device_data,
        category=specs.get("category"),
        power_rating=specs.get("power_rating"),
        global_layer=rule_global_layer,  # Pass the global layer
        is_flexible=is_flexible,
        max_shift_hours=FLEXIBLE_PARAMS.get("max_shift_hours", 8),
        battery_agent=battery_agent,
        pv_agent=pv_agent,
        spec=specs
    )
    
    rule_devices.append(dev)
    rule_global_layer.register_device(dev)  # Register with global layer

print(f"✓ Initialized {len(rule_devices)} devices for rule-based strategy")

# Apply rule-based shifting
# This would be the simple rule-based shifting logic
# For each expensive hour, shift consumption to cheaper hours within max_shift_hours

# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO 3: EMS COST-OPTIMIZED (NO PREFERENCES)
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SCENARIO 3: EMS COST-OPTIMIZED (NO PREFERENCES)")
print("="*80)

# Initialize grid agent
grid_agent = GridAgent(params=GRID_PARAMS)

# Initialize cost optimization global layer
cost_global_layer = GlobalConnectionLayer(
    max_building_load=GRID_PARAMS.get("max_building_load", 10.0),
    total_hours=len(building_data)
)

# Initialize cost-optimized devices
cost_devices = []
for dev_key, specs in device_specs.items():
    cols = [c for c in building_data.columns if dev_key.lower() in c.lower() 
           and 'grid' not in c.lower()]
    
    if not cols:
        continue
    
    device_data = building_data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
    device_data[dev_key] = device_data[cols].sum(axis=1)
    
    # Only flexible if not freezer
    is_flexible = specs.get("is_flexible", False) and dev_key.lower() != "freezer"
    
    dev = FlexibleDevice(
        device_name=dev_key,
        data=device_data,
        category=specs.get("category"),
        power_rating=specs.get("power_rating"),
        global_layer=cost_global_layer,  # Pass the global layer
        is_flexible=is_flexible,
        max_shift_hours=FLEXIBLE_PARAMS.get("max_shift_hours", 8),
        battery_agent=battery_agent,
        pv_agent=pv_agent,
        spec=specs
    )
    
    cost_devices.append(dev)
    cost_global_layer.register_device(dev)  # Register with global layer

# Create optimizer for centralized cost optimization
cost_optimizer = GlobalOptimizer(
    devices=cost_devices,
    global_layer=cost_global_layer,
    pv_agent=pv_agent,
    weather_agent=weather_agent,
    battery_agent=battery_agent,
    grid_agent=grid_agent,
    max_iterations=1,
    online_iterations=3
)

# Run centralized optimization
filter_complete_days_for_all(cost_devices, required_hours=24)
cost_optimizer.optimize_centralized()

print(f"✓ Cost optimization complete for {len(cost_devices)} devices")

# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO 4: EMS BALANCED (WITH PREFERENCES) - CENTRALIZED_PHASES
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SCENARIO 4: EMS BALANCED (WITH PREFERENCES)")
print("="*80)

# Initialize ProbabilityModelAgent for user preferences
print("🧠 Loading probability models for user preferences...")
prob_agent = ProbabilityModelAgent()

# Get device hourly probabilities
device_priors = {}
for dev_key in device_specs.keys():
    try:
        prior = prob_agent.get_device_prior(building_id=BUILDING_ID, device_name=dev_key)
        if prior is not None:
            device_priors[dev_key] = prior
            print(f"✓ Loaded prior for {dev_key}: max={prior.max():.3f}, min={prior.min():.3f}")
        else:
            print(f"⚠ No prior found for {dev_key}, using uniform distribution")
    except Exception as e:
        print(f"⚠ Error loading prior for {dev_key}: {str(e)}")

# Initialize balanced global layer
balanced_global_layer = GlobalConnectionLayer(
    max_building_load=GRID_PARAMS.get("max_building_load", 10.0),
    total_hours=len(building_data)
)

# Initialize balanced devices with preferences
balanced_devices = []
for dev_key, specs in device_specs.items():
    cols = [c for c in building_data.columns if dev_key.lower() in c.lower() 
           and 'grid' not in c.lower()]
    
    if not cols:
        continue
    
    device_data = building_data[["utc_timestamp", "price_per_kwh", "day"] + cols].copy()
    device_data[dev_key] = device_data[cols].sum(axis=1)
    
    # Only flexible if not freezer
    is_flexible = specs.get("is_flexible", False) and dev_key.lower() != "freezer"
    
    dev = FlexibleDevice(
        device_name=dev_key,
        data=device_data,
        category=specs.get("category"),
        power_rating=specs.get("power_rating"),
        global_layer=balanced_global_layer,  # Pass the global layer
        is_flexible=is_flexible,
        max_shift_hours=FLEXIBLE_PARAMS.get("max_shift_hours", 8),
        battery_agent=battery_agent,
        pv_agent=pv_agent,
        spec=specs
    )
    
    # Set preferences if available
    if dev_key in device_priors:
        prior = device_priors[dev_key]
        for hour in range(24):
            dev.set_hour_preference(hour, prior[hour])
    
    balanced_devices.append(dev)
    balanced_global_layer.register_device(dev)  # Register with global layer

# Create optimizer for balanced optimization with preferences
balanced_optimizer = GlobalOptimizer(
    devices=balanced_devices,
    global_layer=balanced_global_layer,
    pv_agent=pv_agent,
    weather_agent=weather_agent,
    battery_agent=battery_agent,
    grid_agent=grid_agent,
    # preference_weight=PREFERENCE_WEIGHT,
    max_iterations=1,
    online_iterations=3
)

# Run centralized phases optimization
filter_complete_days_for_all(balanced_devices, required_hours=24)
balanced_optimizer.optimize_phases_centralized(
    devices=balanced_devices,
    global_layer=balanced_global_layer,
    pv_agent=pv_agent,
    battery_agent=battery_agent,
    grid_agent=grid_agent,
    weather_agent=weather_agent
)

print(f"✓ Balanced optimization with preferences complete for {len(balanced_devices)} devices")
 # ─────────────────────────────────────────────────────────────────────────────
# ANALYSIS AND METRICS CALCULATION
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("ANALYSIS AND METRICS CALCULATION")
print("="*80)

# Initialize PV data if available for metrics calculation
pv_series = pd.Series(0.0, index=pd.to_datetime(building_data["utc_timestamp"], utc=True))
if has_pv and pv_agent is not None:
    pv_df = pv_agent.profile_data.copy()
    if isinstance(pv_df.index, pd.DatetimeIndex):
        pv_idx = pv_df.index
    else:
        pv_idx = pd.to_datetime(pv_df["utc_timestamp"], utc=True)
    pv_series = pd.Series(pv_df["pv"].values, index=pv_idx)

# Calculate aggregate load for each scenario
baseline_load = aggregate_original_load(baseline_devices)
rule_based_load = aggregate_net_load(rule_devices) if rule_devices else pd.Series(dtype=float)
cost_opt_load = aggregate_net_load(cost_devices)
balanced_load = aggregate_net_load(balanced_devices)

# Calculate metrics for each scenario
metrics = pd.DataFrame(index=["Baseline", "Rule-Based", "Cost-Optimized", "Balanced"])

# 1. Total Load (kWh)
metrics["Total Load (kWh)"] = [
    baseline_load.sum(),
    rule_based_load.sum() if not rule_based_load.empty else baseline_load.sum(),
    cost_opt_load.sum(),
    balanced_load.sum()
]

# 2. Net Load after PV (kWh)
metrics["Net Load after PV (kWh)"] = [
    (baseline_load - pv_series).clip(lower=0).sum(),
    (rule_based_load - pv_series).clip(lower=0).sum() if not rule_based_load.empty else (baseline_load - pv_series).clip(lower=0).sum(),
    (cost_opt_load - pv_series).clip(lower=0).sum(),
    (balanced_load - pv_series).clip(lower=0).sum()
]

# 3. PV Self-Consumption (%)
if has_pv and pv_series.sum() < -0.1:
    total_pv = -pv_series.sum()  # PV is negative in our data model
    metrics["PV Self-Consumption (%)"] = [
        (total_pv - max(0, -((baseline_load + pv_series).sum()))) / total_pv * 100,
        (total_pv - max(0, -((rule_based_load + pv_series).sum()))) / total_pv * 100 if not rule_based_load.empty else (total_pv - max(0, -((baseline_load + pv_series).sum()))) / total_pv * 100,
        (total_pv - max(0, -((cost_opt_load + pv_series).sum()))) / total_pv * 100,
        (total_pv - max(0, -((balanced_load + pv_series).sum()))) / total_pv * 100
    ]
else:
    metrics["PV Self-Consumption (%)"] = [0, 0, 0, 0]

# 4. Total Cost (€)
def calculate_total_cost(load_series, price_series):
    """Calculate total cost with appropriate price (import vs. export)"""
    cost = 0.0
    for t, load in load_series.items():
        if t in price_series.index:
            price = price_series[t]
            if load >= 0:  # Import
                cost += load * price
            else:  # Export (lower price)
                cost += load * price * 0.8
    return cost

price_series = pd.Series(
    building_data["price_per_kwh"].values,
    index=pd.to_datetime(building_data["utc_timestamp"], utc=True)
)

metrics["Total Cost (€)"] = [
    calculate_total_cost(baseline_load, price_series),
    calculate_total_cost(rule_based_load, price_series) if not rule_based_load.empty else calculate_total_cost(baseline_load, price_series),
    calculate_total_cost(cost_opt_load, price_series),
    calculate_total_cost(balanced_load, price_series)
]

# 5. Peak-to-Average Ratio
metrics["Peak-to-Average Ratio"] = [
    par(baseline_load, pv_series),
    par(rule_based_load, pv_series) if not rule_based_load.empty else par(baseline_load, pv_series),
    par(cost_opt_load, pv_series),
    par(balanced_load, pv_series)
]

# Add cost savings compared to baseline
baseline_cost = metrics.loc["Baseline", "Total Cost (€)"]
metrics["Cost Savings (%)"] = [
    0,
    ((baseline_cost - metrics.loc["Rule-Based", "Total Cost (€)"]) / baseline_cost) * 100 if "Rule-Based" in metrics.index else 0,
    ((baseline_cost - metrics.loc["Cost-Optimized", "Total Cost (€)"]) / baseline_cost) * 100,
    ((baseline_cost - metrics.loc["Balanced", "Total Cost (€)"]) / baseline_cost) * 100
]

# Format metrics table
metrics = metrics.round(2)

# Add Scenario column for easier comparison
metrics_reset = metrics.reset_index()
metrics_reset.rename(columns={'index': 'Strategy'}, inplace=True)

# ─────────────────────────────────────────────────────────────────────────────
# TABULAR RESULTS OUTPUT (SIMILAR TO OTHER SCRIPT)
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print(f"CONSOLIDATED RESULTS FOR {BUILDING_ID}")
print("="*80)

# Create paper-style rows for consistency with other script
paper_style_rows = []

paper_row = {
    "Building": BUILDING_ID,
    "No. of Loads": len(baseline_devices),
    
    # Load values
    "Baseline Load (kWh)": metrics.loc["Baseline", "Total Load (kWh)"],
    "Rule-Based Load (kWh)": metrics.loc["Rule-Based", "Total Load (kWh)"],
    "Cost-Opt Load (kWh)": metrics.loc["Cost-Optimized", "Total Load (kWh)"],
    "Balanced Load (kWh)": metrics.loc["Balanced", "Total Load (kWh)"],
    
    # Cost values
    "Baseline Cost (€)": metrics.loc["Baseline", "Total Cost (€)"],
    "Rule-Based Cost (€)": metrics.loc["Rule-Based", "Total Cost (€)"],
    "Cost-Opt Cost (€)": metrics.loc["Cost-Optimized", "Total Cost (€)"],
    "Balanced Cost (€)": metrics.loc["Balanced", "Total Cost (€)"],
    
    # Cost reduction percentages
    "% Cost Red. - Rule-Based": metrics.loc["Rule-Based", "Cost Savings (%)"],
    "% Cost Red. - Cost-Opt": metrics.loc["Cost-Optimized", "Cost Savings (%)"],
    "% Cost Red. - Balanced": metrics.loc["Balanced", "Cost Savings (%)"],
    
    # PV utilization
    "PV Used - Baseline (kWh)": metrics.loc["Baseline", "PV Self-Consumption (%)"],
    "PV Used - Rule-Based (kWh)": metrics.loc["Rule-Based", "PV Self-Consumption (%)"],
    "PV Used - Cost-Opt (kWh)": metrics.loc["Cost-Optimized", "PV Self-Consumption (%)"],
    "PV Used - Balanced (kWh)": metrics.loc["Balanced", "PV Self-Consumption (%)"],
    
    # PAR values
    "Baseline PAR": metrics.loc["Baseline", "Peak-to-Average Ratio"],
    "Rule-Based PAR": metrics.loc["Rule-Based", "Peak-to-Average Ratio"],
    "Cost-Opt PAR": metrics.loc["Cost-Optimized", "Peak-to-Average Ratio"],
    "Balanced PAR": metrics.loc["Balanced", "Peak-to-Average Ratio"],
}
paper_style_rows.append(paper_row)

# Create DataFrame for paper-style output
paper_df = pd.DataFrame(paper_style_rows).round(2)

# Print formatted tables
print("\nDetailed Metrics by Strategy:")
print(metrics.to_string())

print("\nPaper-Style Consolidated Table:")
print(paper_df.to_string(index=False))

# ─────────────────────────────────────────────────────────────────────────────
# EXPORT RESULTS
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("EXPORT RESULTS")
print("="*80)

# Export metrics to CSV
metrics_filename = f'ems_comparison_metrics_{BUILDING_ID}.csv'
metrics.to_csv(metrics_filename)
print(f"✓ Metrics exported to '{metrics_filename}'")

# Export paper-style table
paper_style_filename = f'paper_style_building_summary_{BUILDING_ID}.csv'
paper_df.to_csv(paper_style_filename, index=False)
print(f"✓ Paper-style summary exported to '{paper_style_filename}'")

# Export hourly profiles data (without plots)
profiles_df = pd.DataFrame({
    'Timestamp': pd.to_datetime(building_data["utc_timestamp"], utc=True),
    'Baseline': baseline_load,
    'Cost-Optimized': cost_opt_load,
    'Balanced': balanced_load,
    'PV Generation': pv_series
})

if not rule_based_load.empty:
    profiles_df['Rule-Based'] = rule_based_load

profiles_df = profiles_df.set_index('Timestamp')
profiles_filename = f'ems_comparison_profiles_{BUILDING_ID}.csv'
profiles_df.to_csv(profiles_filename)
print(f"✓ Hourly profiles data exported to '{profiles_filename}'")

# ─────────────────────────────────────────────────────────────────────────────
# SUMMARY TABLE (COMPACT VERSION)
# ─────────────────────────────────────────────────────────────────────────────

print("\n" + "="*80)
print("SUMMARY TABLE")
print("="*80)

# Create a compact summary table
summary_table = pd.DataFrame({
    'Strategy': ['Baseline', 'Rule-Based', 'Cost-Optimized', 'Balanced'],
    'Load (kWh)': metrics['Total Load (kWh)'].values,
    'Net Load (kWh)': metrics['Net Load after PV (kWh)'].values,
    'Cost (€)': metrics['Total Cost (€)'].values,
    'Cost Savings (%)': metrics['Cost Savings (%)'].values,
    'PV Self-Cons. (%)': metrics['PV Self-Consumption (%)'].values,
    'PAR': metrics['Peak-to-Average Ratio'].values
}).round(2)

print("\nCompact Summary Table:")
print(summary_table.to_string(index=False))

summary_filename = f'ems_summary_table_{BUILDING_ID}.csv'
summary_table.to_csv(summary_filename, index=False)
print(f"✓ Summary table exported to '{summary_filename}'")

print("\n" + "="*80)
print("ANALYSIS COMPLETE")
print("="*80)

📊 Loading data for building: DE_KN_residential1

Found 662 days with significant device activity
✓ Data loaded: 120 rows, 20 columns
✓ Selected 5 complete days with highest activity

================================================================================
SCENARIO 1: BASELINE (UNOPTIMIZED)
================================================================================
✓ Initialized 5 devices with original consumption patterns

================================================================================
SCENARIO 2: RULE-BASED STRATEGY
================================================================================
✓ Initialized 5 devices for rule-based strategy

================================================================================
SCENARIO 3: EMS COST-OPTIMIZED (NO PREFERENCES)
================================================================================
Found 5 unique days to optimize
Device: dishwasher, is_flexible: False
Device: washing_machine, is_flexible: False
Device: heat_pump, is_flexible: False
Device: freezer, is_flexible: False
Device: pump, is_flexible: False

Processing day: 2017-01-20
Battery available with capacity: 14.0 kWh, current SOC: 8.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-20
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -159.1497096875
Day 2017-01-20: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=5.41, Charge=0.00, Discharge=2.59
  Hour 1: SOC=3.81, Charge=0.00, Discharge=1.59
  Hour 2: SOC=3.22, Charge=0.00, Discharge=0.59
  Hour 3: SOC=3.22, Charge=0.41, Discharge=0.00
  Hour 4: SOC=4.03, Charge=1.41, Discharge=0.00
  Hour 5: SOC=5.83, Charge=2.41, Discharge=0.00
  Hour 6: SOC=8.64, Charge=3.41, Discharge=0.00
  Hour 7: SOC=11.43, Charge=3.39, Discharge=0.00
  Hour 8: SOC=13.21, Charge=2.39, Discharge=0.00
  Hour 9: SOC=14.00, Charge=1.39, Discharge=0.00
  Hour 10: SOC=14.00, Charge=0.39, Discharge=0.00
  Hour 11: SOC=13.39, Charge=0.00, Discharge=0.61
  Hour 12: SOC=11.78, Charge=0.00, Discharge=1.61
  Hour 13: SOC=9.16, Charge=0.00, Discharge=2.61
  Hour 14: SOC=5.55, Charge=0.00, Discharge=3.61
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=31.93, day discharge=18.18

Processing day: 2017-01-23
Battery available with capacity: 13.999532341666667 kWh, current SOC: 14.0 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-23
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -145.926669803049
Day 2017-01-23: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=9.60, Charge=0.00, Discharge=4.58
  Hour 1: SOC=6.02, Charge=0.00, Discharge=3.58
  Hour 2: SOC=3.44, Charge=0.00, Discharge=2.58
  Hour 3: SOC=1.86, Charge=0.00, Discharge=1.58
  Hour 4: SOC=1.29, Charge=0.00, Discharge=0.58
  Hour 5: SOC=1.29, Charge=0.42, Discharge=0.00
  Hour 6: SOC=2.11, Charge=1.42, Discharge=0.00
  Hour 7: SOC=3.93, Charge=2.42, Discharge=0.00
  Hour 8: SOC=6.75, Charge=3.42, Discharge=0.00
  Hour 9: SOC=8.75, Charge=2.60, Discharge=0.00
  Hour 10: SOC=9.75, Charge=1.60, Discharge=0.00
  Hour 11: SOC=9.75, Charge=0.60, Discharge=0.00
  Hour 12: SOC=9.35, Charge=0.00, Discharge=0.40
  Hour 13: SOC=7.95, Charge=0.00, Discharge=1.40
  Hour 14: SOC=5.55, Charge=0.00, Discharge=2.40
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=29.24, day discharge=22.04

Processing day: 2017-01-24
Battery available with capacity: 13.999053744316667 kWh, current SOC: 13.999532 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-24
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -145.92603609309998
Day 2017-01-24: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=9.60, Charge=0.00, Discharge=4.58
  Hour 1: SOC=6.02, Charge=0.00, Discharge=3.58
  Hour 2: SOC=3.44, Charge=0.00, Discharge=2.58
  Hour 3: SOC=1.86, Charge=0.00, Discharge=1.58
  Hour 4: SOC=1.29, Charge=0.00, Discharge=0.58
  Hour 5: SOC=1.29, Charge=0.42, Discharge=0.00
  Hour 6: SOC=2.11, Charge=1.42, Discharge=0.00
  Hour 7: SOC=3.93, Charge=2.42, Discharge=0.00
  Hour 8: SOC=6.75, Charge=3.42, Discharge=0.00
  Hour 9: SOC=8.75, Charge=2.60, Discharge=0.00
  Hour 10: SOC=9.75, Charge=1.60, Discharge=0.00
  Hour 11: SOC=9.75, Charge=0.60, Discharge=0.00
  Hour 12: SOC=9.35, Charge=0.00, Discharge=0.40
  Hour 13: SOC=7.95, Charge=0.00, Discharge=1.40
  Hour 14: SOC=5.55, Charge=0.00, Discharge=2.40
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=29.24, day discharge=22.04

Processing day: 2017-01-25
Battery available with capacity: 13.998575150303333 kWh, current SOC: 13.999054 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-25
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -145.92543360230403
Day 2017-01-25: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=9.60, Charge=0.00, Discharge=4.58
  Hour 1: SOC=6.02, Charge=0.00, Discharge=3.58
  Hour 2: SOC=3.44, Charge=0.00, Discharge=2.58
  Hour 3: SOC=1.86, Charge=0.00, Discharge=1.58
  Hour 4: SOC=1.29, Charge=0.00, Discharge=0.58
  Hour 5: SOC=1.29, Charge=0.42, Discharge=0.00
  Hour 6: SOC=2.11, Charge=1.42, Discharge=0.00
  Hour 7: SOC=3.93, Charge=2.42, Discharge=0.00
  Hour 8: SOC=6.75, Charge=3.42, Discharge=0.00
  Hour 9: SOC=8.75, Charge=2.60, Discharge=0.00
  Hour 10: SOC=9.75, Charge=1.60, Discharge=0.00
  Hour 11: SOC=9.75, Charge=0.60, Discharge=0.00
  Hour 12: SOC=9.35, Charge=0.00, Discharge=0.40
  Hour 13: SOC=7.95, Charge=0.00, Discharge=1.40
  Hour 14: SOC=5.55, Charge=0.00, Discharge=2.40
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=29.24, day discharge=22.04

Processing day: 2017-01-26
Battery available with capacity: 13.9980965596388 kWh, current SOC: 13.998575 kWh
PV forecast available: 24 hours, max generation: 0.000 kWh
Using PV forecast for day 2017-01-26
  dishwasher: Found 1 hours with consumption > 0
  washing_machine: Found 1 hours with consumption > 0
  heat_pump: Found 24 hours with consumption > 0
  freezer: Found 24 hours with consumption > 0
  pump: Found 24 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  dishwasher: Skipping optimization (not flexible or no consumption)
  washing_machine: Skipping optimization (not flexible or no consumption)
  heat_pump: Skipping optimization (not flexible or no consumption)
  freezer: Skipping optimization (not flexible or no consumption)
  pump: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 570 constraints in total

Objective function has 96 cost terms
Solving problem with 264 variables and 570 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -145.92483124913903
Day 2017-01-26: Costs evaluated and stored.

Reconstructing optimized schedules...

Processing battery optimization results...
  Hour 0: SOC=9.60, Charge=0.00, Discharge=4.58
  Hour 1: SOC=6.02, Charge=0.00, Discharge=3.58
  Hour 2: SOC=3.44, Charge=0.00, Discharge=2.58
  Hour 3: SOC=1.86, Charge=0.00, Discharge=1.58
  Hour 4: SOC=1.29, Charge=0.00, Discharge=0.58
  Hour 5: SOC=1.29, Charge=0.42, Discharge=0.00
  Hour 6: SOC=2.11, Charge=1.42, Discharge=0.00
  Hour 7: SOC=3.93, Charge=2.42, Discharge=0.00
  Hour 8: SOC=6.75, Charge=3.42, Discharge=0.00
  Hour 9: SOC=8.75, Charge=2.60, Discharge=0.00
  Hour 10: SOC=9.75, Charge=1.60, Discharge=0.00
  Hour 11: SOC=9.75, Charge=0.60, Discharge=0.00
  Hour 12: SOC=9.35, Charge=0.00, Discharge=0.40
  Hour 13: SOC=7.95, Charge=0.00, Discharge=1.40
  Hour 14: SOC=5.55, Charge=0.00, Discharge=2.40
  Hour 15: SOC=2.90, Charge=0.00, Discharge=2.65
  Hour 16: SOC=1.25, Charge=0.00, Discharge=1.65
  Hour 17: SOC=0.60, Charge=0.00, Discharge=0.65
  Hour 18: SOC=0.60, Charge=0.35, Discharge=0.00
  Hour 19: SOC=1.35, Charge=1.35, Discharge=0.00
  Hour 20: SOC=3.10, Charge=2.35, Discharge=0.00
  Hour 21: SOC=5.85, Charge=3.35, Discharge=0.00
  Hour 22: SOC=9.60, Charge=4.35, Discharge=0.00
  Hour 23: SOC=14.00, Charge=5.00, Discharge=0.00
  Updated battery agent: SOC=14.00, day charge=29.23, day discharge=22.04

Finalizing optimization...
dishwasher: Difference between original and optimized: 0.000000
washing_machine: Difference between original and optimized: 0.000000
heat_pump: Difference between original and optimized: 0.000000
freezer: Difference between original and optimized: 0.000000
pump: Difference between original and optimized: 0.000000

Centralized optimization complete with battery modeling!

Calculating and storing optimization costs...
dishwasher: Original=$0.02, Optimized=$0.02, Savings=$0.00
washing_machine: Original=$0.09, Optimized=$0.09, Savings=$0.00
heat_pump: Original=$9.26, Optimized=$9.26, Savings=$0.00
freezer: Original=$0.13, Optimized=$0.13, Savings=$0.00
pump: Original=$9.26, Optimized=$9.26, Savings=$0.00
✓ Cost optimization complete for 5 devices

================================================================================
SCENARIO 4: EMS BALANCED (WITH PREFERENCES)
================================================================================
🧠 Loading probability models for user preferences...
ProbabilityModelAgent ready (adaptive PMF with DuckDB priors)
⚠ Error loading prior for _charge: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for dishwasher: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for washing_machine: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for heat_pump: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for refrigerator: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for freezer: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for circulation_pump: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for ev: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for dryer: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for water_heater: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for oven: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for coffee_maker: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for lighting: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for computer: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for fridge: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
⚠ Error loading prior for pump: 'ProbabilityModelAgent' object has no attribute 'get_device_prior'
Starting centralized next-day optimization...
Battery available with capacity: 15.0 kWh, current SOC: 13.998097
Adding building-wide load constraints...
Solving centralized MILP...
Solver status: Optimal, objective value: -0.4608945368
MILP solution found!
Costs for day 2017-01-20 evaluated and stored for standardized comparison with solver objective value: -0.4608945368
✓ Balanced optimization with preferences complete for 5 devices

================================================================================
ANALYSIS AND METRICS CALCULATION
================================================================================

================================================================================
CONSOLIDATED RESULTS FOR DE_KN_residential1
================================================================================

Detailed Metrics by Strategy:
                Total Load (kWh)  Net Load after PV (kWh)  PV Self-Consumption (%)  Total Cost (€)  Peak-to-Average Ratio  Cost Savings (%)
Baseline                  545.41                   546.42                    100.0           18.76                    3.2               0.0
Rule-Based                545.41                   546.42                    100.0           18.76                    3.2               0.0
Cost-Optimized            545.41                   546.42                    100.0           18.76                    3.2               0.0
Balanced                  545.41                   546.42                    100.0           18.76                    3.2               0.0

Paper-Style Consolidated Table:
          Building  No. of Loads  Baseline Load (kWh)  Rule-Based Load (kWh)  Cost-Opt Load (kWh)  Balanced Load (kWh)  Baseline Cost (€)  Rule-Based Cost (€)  Cost-Opt Cost (€)  Balanced Cost (€)  % Cost Red. - Rule-Based  % Cost Red. - Cost-Opt  % Cost Red. - Balanced  PV Used - Baseline (kWh)  PV Used - Rule-Based (kWh)  PV Used - Cost-Opt (kWh)  PV Used - Balanced (kWh)  Baseline PAR  Rule-Based PAR  Cost-Opt PAR  Balanced PAR
DE_KN_residential1             5               545.41                 545.41               545.41               545.41              18.76                18.76              18.76              18.76                       0.0                     0.0                     0.0                     100.0                       100.0                     100.0                     100.0           3.2             3.2           3.2           3.2

================================================================================
EXPORT RESULTS
================================================================================
✓ Metrics exported to 'ems_comparison_metrics_DE_KN_residential1.csv'

## Table 4 - MULTI-BUILDING COORDINATION SCENARIO

In [ ]:
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ MULTI-BUILDING COORDINATION SCENARIO                                      ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

def run_coordinated_building_cluster(building_ids, device_specs_by_building, parquet_dir="data", 
                                   days=7, use_batteries=True):
    """
    Optimize multiple buildings together as a coordinated cluster.
    
    Args:
        building_ids: List of building IDs to optimize together
        device_specs_by_building: Dict mapping building IDs to device specs
        parquet_dir: Directory containing parquet data files
        days: Number of days to optimize for
        use_batteries: Whether to include batteries in the optimization
        
    Returns:
        Dictionary mapping building IDs to devices, optimizer, and common dataframe
    """
    print(f"\n{'='*80}\nRunning coordinated cluster optimization for {len(building_ids)} buildings\n{'='*80}")
    
    # Step 1: Load data for each building and find common days
    building_data = {}
    common_days = None
    
    for bld in building_ids:
        parquet_path = Path(parquet_dir) / f"{bld}_processed_data.parquet"
        if not parquet_path.exists():
            print(f"⚠️ Skipping {bld} - data file not found")
            continue
            
        data = pd.read_parquet(parquet_path)
        
        # Process timestamps
        if isinstance(data.index, pd.DatetimeIndex) and 'utc_timestamp' not in data.columns:
            data = data.reset_index()
            if 'index' in data.columns and 'utc_timestamp' not in data.columns:
                data.rename(columns={'index': 'utc_timestamp'}, inplace=True)
        
        data['utc_timestamp'] = pd.to_datetime(data['utc_timestamp'])
        data['hour'] = data['utc_timestamp'].dt.hour
        data['day'] = data['utc_timestamp'].dt.date
        
        # Find days with full 24-hour data
        days_with_hours = data.groupby('day')['hour'].nunique()
        complete_days = days_with_hours[days_with_hours == 24].index
        
        if len(complete_days) == 0:
            print(f"⚠️ Skipping {bld} - no days with complete 24-hour data")
            continue
        
        # Update common days
        if common_days is None:
            common_days = set(complete_days)
        else:
            common_days &= set(complete_days)
        
        building_data[bld] = data
    
    if not common_days:
        raise ValueError("No common days with complete data found across buildings")
        
    # Sort common days and take the most recent ones up to the requested number of days
    common_days = sorted(common_days)[-days:]
    print(f"Found {len(common_days)} common days: {common_days}")
    
    # Step 2: Create a shared GlobalConnectionLayer with increased capacity for the cluster
    max_building_loads = {
        bld: 40.0 if "industrial" in bld.lower() else 15.0 
        for bld in building_ids if bld in building_data
    }
    
    # Calculate total max load for the cluster
    cluster_max_load = sum(max_building_loads.values())
    
    # Create a shared connection layer for all buildings
    global_layer = GlobalConnectionLayer(max_building_load=cluster_max_load, total_hours=24)
    
    # Step 3: Create agents and devices for all buildings
    all_devices = []
    building_devices = {}
    
    # Weather and price data will be taken from the first building
    first_bld = next(iter(building_data))
    first_data = building_data[first_bld]
    
    # Filter data for common days for all buildings
    for bld in building_data:
        building_data[bld] = building_data[bld][building_data[bld]['day'].isin(common_days)].copy()
        building_data[bld].reset_index(drop=True, inplace=True)
    
    # Setup weather agent using first building's data
    weather_cols = [col for col in first_data.columns if any(
        term in col.lower() for term in ['temperature', 'radiation', 'humidity', 'wind'])]
    
    if weather_cols:
        weather_df = first_data[['utc_timestamp'] + weather_cols].copy()
    else:
        weather_df = pd.DataFrame({
            'utc_timestamp': first_data['utc_timestamp'],
            'temperature': np.random.uniform(15, 25, len(first_data)),
            'radiation': np.random.uniform(0, 800, len(first_data))
        })
    weather_agent = WeatherAgent(weather_df=weather_df)
    
    # Setup a shared PV agent that combines PV from all buildings
    combined_pv_data = None
    
    # Setup battery agents for buildings if enabled
    battery_agents = {}
    if use_batteries:
        for bld in building_data:
            battery_agents[bld] = BatteryAgent(**(BATTERY_PARAMS or {}))
    
    # Generate dynamic price data with proper variation for all buildings
    # FIX: Create dynamic price data with variation to prevent "no price variation" warnings
    print("Generating dynamic price data for all buildings...")
    
    # Get timestamps from the first building's data
    timestamps = first_data['utc_timestamp'].unique()
    
    # Create a DataFrame with timestamps and dynamic price variation
    price_df = pd.DataFrame({
        'utc_timestamp': timestamps
    })
    
    # Generate price data with daily and hourly variation patterns
    price_df['price_per_kwh'] = 0.25  # Base price
    
    # Add time-of-day variation (higher prices in evening peak hours)
    for idx, row in price_df.iterrows():
        hour = row['utc_timestamp'].hour
        # Evening peak (17:00-21:00)
        if 17 <= hour <= 21:
            price_df.loc[idx, 'price_per_kwh'] *= 1.5
        # Night valley (23:00-05:00)
        elif 23 <= hour or hour <= 5:
            price_df.loc[idx, 'price_per_kwh'] *= 0.7
        # Morning peak (07:00-09:00)
        elif 7 <= hour <= 9:
            price_df.loc[idx, 'price_per_kwh'] *= 1.3
    
    # Add day-to-day variation (weekend vs weekday)
    for idx, row in price_df.iterrows():
        day_of_week = row['utc_timestamp'].dayofweek
        # Weekend discount
        if day_of_week >= 5:  # 5=Saturday, 6=Sunday
            price_df.loc[idx, 'price_per_kwh'] *= 0.9
    
    # Add random variation (±10%)
    np.random.seed(42)  # For reproducibility
    random_factors = np.random.uniform(0.9, 1.1, len(price_df))
    price_df['price_per_kwh'] *= random_factors
    
    # Process each building
    for bld in building_data:
        data = building_data[bld]
        devices = []
        
        # FIX: Add price data to each building's dataset
        if 'price_per_kwh' not in data.columns:
            # Merge the price data with the building data
            data = pd.merge(data, price_df[['utc_timestamp', 'price_per_kwh']], on='utc_timestamp', how='left')
            building_data[bld] = data  # Update the data in the dictionary
        
        # Get PV data for this building
        pv_cols = [
            c for c in data.columns
            if "pv" in c.lower()
            and not any(tag in c.lower() for tag in ("forecast", "potential", "radiation", "diffuse"))
            and pd.api.types.is_numeric_dtype(data[c])
            and data[c].sum() < 0
        ]
        
        has_pv = len(pv_cols) > 0
        pv_agent = None
        
        if has_pv:
            pv_data = data[['utc_timestamp'] + pv_cols].copy()
            pv_data['pv'] = pv_data[pv_cols].sum(axis=1)
            pv_data = pv_data.set_index('utc_timestamp')
            
            forecast_data = pd.DataFrame({
                'utc_timestamp': data['utc_timestamp'],
                'Solar': pv_data['pv'].values
            })
            
            pv_agent = PVAgent(
                profile_data=pv_data[['pv']],
                forecast_data=forecast_data,
                forecast_cols=["Solar"]
            )
            
            # Add to combined PV data
            if combined_pv_data is None:
                combined_pv_data = forecast_data.copy()
                combined_pv_data.set_index('utc_timestamp', inplace=True)
            else:
                temp_df = forecast_data.copy().set_index('utc_timestamp')
                # Add solar from this building
                combined_pv_data['Solar'] = combined_pv_data.get('Solar', 0) + temp_df['Solar']
        
        # Create grid agent
        grid_agent = GridAgent()
        
        # Create flexible devices for this building
        bld_device_specs = device_specs_by_building.get(bld, device_specs)
        
        for dev_key, specs in bld_device_specs.items():
            cols = [c for c in data.columns if dev_key.lower() in c.lower()]
            for c in cols:
                # Get the building's specific battery agent if batteries are enabled
                battery_agent = battery_agents.get(bld) if use_batteries else None
                
                dev = FlexibleDevice(
                    data, c, specs['category'], specs['power_rating'],
                    global_layer, max_shift_hours=8,
                    is_flexible=(dev_key != "freezer"),
                    battery_agent=battery_agent,
                    pv_agent=pv_agent,
                    spec=specs
                )
                devices.append(dev)
                global_layer.register_device(dev)
        
        if devices:
            building_devices[bld] = devices
            all_devices.extend(devices)
    
    # Create a combined PV agent for the cluster
    combined_pv_agent = None
    if combined_pv_data is not None:
        combined_pv_data.reset_index(inplace=True)
        combined_pv_agent = PVAgent(
            profile_data=pd.DataFrame({
                'pv': combined_pv_data['Solar'].values
            }, index=combined_pv_data['utc_timestamp']),
            forecast_data=combined_pv_data,
            forecast_cols=["Solar"]
        )
    
    # Filter to ensure all devices have complete days
    filter_complete_days_for_all(all_devices, required_hours=24)
    
    # FIX: Verify price data is present for all devices
    print("\nVerifying price data for all devices...")
    for device in all_devices:
        device_id = getattr(device, 'column', str(device))
        if 'price_per_kwh' in device.data.columns:
            price_values = device.data['price_per_kwh'].values
            price_min = price_values.min() if len(price_values) > 0 else None
            price_max = price_values.max() if len(price_values) > 0 else None
            price_range = price_max - price_min if price_min is not None and price_max is not None else None
            
            print(f"  {device_id}: Price range = {price_range:.6f} [{price_min:.6f} to {price_max:.6f}]")
        else:
            print(f"  {device_id}: No price_per_kwh column found")
    
    # Step 4: Run the optimizer with all devices at once
    optimizer = GlobalOptimizer(
        devices=all_devices,
        global_layer=global_layer,
        pv_agent=combined_pv_agent,
        weather_agent=weather_agent,
        battery_agent=list(battery_agents.values())[0] if battery_agents else None,
        grid_agent=grid_agent,
        max_iterations=1,
        online_iterations=3
    )
    
    # Run centralized optimization for the entire cluster
    optimizer.optimize_centralized()

    # In run_coordinated_building_cluster function:
    # After running optimizer.optimize_centralized()
    print("\nChecking optimization results:")
    for bld, devices in building_devices.items():
        print(f"Building {bld}:")
        for device in devices:
            # Use device.column instead of device.name
            device_id = getattr(device, 'column', str(device))
            
            if hasattr(device, 'optimized_consumption') and device.optimized_consumption is not None:
                if isinstance(device.optimized_consumption, dict):
                    opt_vals = list(device.optimized_consumption.values())
                else:
                    opt_vals = device.optimized_consumption.tolist() if hasattr(device.optimized_consumption, 'tolist') else list(device.optimized_consumption)
                print(f"  {device_id}: {len(opt_vals)} values, sum={sum(opt_vals):.2f}, min={min(opt_vals) if opt_vals else 0:.2f}, max={max(opt_vals) if opt_vals else 0:.2f}")
            else:
                print(f"  {device_id}: No optimized consumption")
    
    return {
        "building_devices": building_devices,
        "optimizer": optimizer,
        "common_days": common_days,
        "global_layer": global_layer,
        "building_data": building_data,
        "combined_pv_agent": combined_pv_agent
    }

# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ MULTI-BUILDING VISUALIZATION                                              ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

def plot_building_cluster_heatmap(result, selected_date=None):
    """
    Create a heatmap visualization of building schedules with price overlay.
    
    Args:
        result: Output from run_coordinated_building_cluster
        selected_date: Date to visualize (defaults to first common day)
    """
    import matplotlib.pyplot as plt
    from matplotlib.colors import LinearSegmentedColormap
    import seaborn as sns
    import warnings
    import matplotlib as mpl
    
    # Configure matplotlib to use standard fonts
    plt.rcParams['font.family'] = ['DejaVu Sans', 'Arial', 'Helvetica', 'sans-serif']
    
    # Suppress all font-related warnings
    warnings.filterwarnings("ignore", category=UserWarning, module="matplotlib.font_manager")
    
    building_devices = result["building_devices"]
    common_days = result["common_days"]
    
    # Use first common day if no specific date provided
    if selected_date is None:
        selected_date = common_days[0]
    elif isinstance(selected_date, str):
        selected_date = pd.Timestamp(selected_date).date()
    
    # Get all unique hours for the selected date
    all_timestamps = []
    for bld, devices in building_devices.items():
        if not devices:
            continue
        device = devices[0]
        day_data = device.data[device.data['day'] == selected_date]
        if len(day_data) > 0:
            all_timestamps = day_data['utc_timestamp'].tolist()
            break
    
    if not all_timestamps:
        raise ValueError(f"No data found for date {selected_date}")
        
    # Sort timestamps chronologically
    all_timestamps.sort()
    
    # Create a heatmap matrix [buildings × hours]
    buildings = list(building_devices.keys())
    hours = [ts.hour for ts in all_timestamps]
    hour_indices = {h: i for i, h in enumerate(hours)}
    
    # Initialize the matrix with NaN values
    heatmap_data = np.full((len(buildings), len(hours)), np.nan)
    
    # Extract average prices for the selected date
    price_data = None
    
    # Fill the matrix with net load for each building at each hour
    for b_idx, bld in enumerate(buildings):
        devices = building_devices[bld]
        if not devices:
            continue
            
        # Add more debugging info
        print(f"Processing building {bld} with {len(devices)} devices")
        
        # Aggregate building load
        net_loads = {}
        
        for device in devices:
            # Use device.column instead of device.name
            device_id = getattr(device, 'column', str(device))
            
            day_mask = device.data['day'] == selected_date
            if not any(day_mask):
                print(f"  No data for {device_id} on {selected_date}")
                continue
                
            # Check if optimization was successful
            if not hasattr(device, 'optimized_consumption') or device.optimized_consumption is None:
                print(f"  Device {device_id} has no optimized_consumption")
                continue
                
            # Print range of values for debugging
            if isinstance(device.optimized_consumption, dict):
                opt_vals = [device.optimized_consumption[idx] for idx in device.data.index[day_mask] if idx in device.optimized_consumption]
            else:
                # If it's a numpy array or other sequence, index differently
                opt_vals = [device.optimized_consumption[i] for i, idx in enumerate(device.data.index) if day_mask.iloc[i]]
            
            if opt_vals:
                print(f"  Device {device_id}: min={min(opt_vals):.2f}, max={max(opt_vals):.2f}, sum={sum(opt_vals):.2f}")
            else:
                print(f"  Device {device_id}: no values")
            
            for i, (idx, row) in enumerate(device.data[day_mask].iterrows()):
                ts = row['utc_timestamp']
                hour = ts.hour
                
                if hour in hour_indices:
                    h_idx = hour_indices[hour]
                    # Make sure we have a valid optimized consumption value
                    try:
                        if isinstance(device.optimized_consumption, dict):
                            if idx in device.optimized_consumption:
                                load = device.optimized_consumption[idx]
                                net_loads[h_idx] = net_loads.get(h_idx, 0) + load
                        else:
                            # If it's an array, use positional index
                            day_indices = device.data[day_mask].index.tolist()
                            i = day_indices.index(idx)
                            load = device.optimized_consumption[i]
                            net_loads[h_idx] = net_loads.get(h_idx, 0) + load
                    except (KeyError, IndexError):
                        print(f"  Missing optimized_consumption for {device_id} at index {idx}")
                    
                    # Collect price data (the same for all buildings)
                    if price_data is None:
                        price_data = [row['price_per_kwh'] for _, row in device.data[day_mask].iterrows()]
        
        # Fill the matrix with the calculated net loads
        for h_idx, load in net_loads.items():
            heatmap_data[b_idx, h_idx] = load
        
        # Print a summary of net loads for this building
        print(f"Building {bld} net loads: {', '.join([f'{h}:{net_loads.get(h, 0):.2f}' for h in sorted(net_loads.keys())])}")
            
    # Create a custom colormap for the heatmap
    colors = [(0, 0.6, 0), (1, 1, 0.8), (0.8, 0, 0)]  # green, light yellow, red
    cmap = LinearSegmentedColormap.from_list('GreenYellowRed', colors)
    
    # Create the plot with specific styling to avoid font issues
    with mpl.rc_context({'font.family': ['DejaVu Sans', 'Arial', 'Helvetica']}):
        fig, ax1 = plt.subplots(figsize=(15, 8))
        
        # Plot heatmap
        sns.heatmap(heatmap_data, cmap=cmap, annot=True, fmt=".1f", linewidths=0.5, ax=ax1, 
                    xticklabels=hours, yticklabels=buildings, cbar_kws={'label': 'Net Load (kW)'})
        
        ax1.set_title(f'Building Cluster Energy Schedule for {selected_date}', fontsize=15)
        ax1.set_xlabel('Hour of Day', fontsize=12)
        ax1.set_ylabel('Building', fontsize=12)
        
        # Create a second axis for the price plot
        ax2 = ax1.twinx()
        
        if price_data:
            # Plot price as a line on the secondary y-axis
            x = np.arange(len(hours)) + 0.5  # Center points of heatmap cells
            ax2.plot(x, price_data, 'b-', linewidth=2, marker='o', label='Price')
            ax2.set_ylabel('Price (€/kWh)', color='b', fontsize=12)
            ax2.tick_params(axis='y', labelcolor='b')
        
        plt.tight_layout()
    
    return fig

# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ EXECUTE COORDINATED MULTI-BUILDING OPTIMIZATION                           ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

# Define buildings to include in the coordinated scenario
buildings_for_coordination = [
    "DE_KN_industrial3",  # Include industrial building
    "DE_KN_residential1",  # Include residential buildings
    "DE_KN_residential2",
    "DE_KN_residential3",
    "DE_KN_residential4", 
    "DE_KN_residential5",
    "DE_KN_residential6",
]

# Run the coordinated optimization for a 7-day period
cluster_result = run_coordinated_building_cluster(
    building_ids=buildings_for_coordination,
    device_specs_by_building={bld: device_specs for bld in buildings_for_coordination},
    days=7,
    use_batteries=True
)

# Calculate total consumption and costs for the cluster
cluster_stats = {
    "total_original_load": 0.0,
    "total_optimized_load": 0.0,
    "total_original_cost": 0.0,
    "total_optimized_cost": 0.0,
    "pv_generated": 0.0,
    "pv_utilized": 0.0,
}

for bld, devices in cluster_result["building_devices"].items():
    # Calculate metrics for this building
    if not devices:
        continue
    
    # Get price and timestamps
    analysis_df = devices[0].data[['utc_timestamp', 'price_per_kwh']].copy()
    analysis_df['utc_timestamp'] = pd.to_datetime(analysis_df['utc_timestamp'], utc=True)
    analysis_df.set_index('utc_timestamp', inplace=True)
    price_series = analysis_df['price_per_kwh']
    
    # Get original and optimized loads
    orig_series = aggregate_original_load(devices).reindex(price_series.index, fill_value=0)
    opt_series = aggregate_net_load(devices).reindex(price_series.index, fill_value=0)
    
    # Extract PV data if available
    pv_series = pd.Series(0.0, index=price_series.index)
    for dev in devices:
        pv_cols = [c for c in dev.data.columns if "pv" in c.lower() and dev.data[c].sum() < 0]
        if pv_cols:
            pv_df = dev.data[['utc_timestamp'] + pv_cols].copy()
            pv_df.set_index('utc_timestamp', inplace=True)
            pv_s = -pv_df[pv_cols].sum(axis=1)
            pv_series = pv_s.reindex(price_series.index, fill_value=0).clip(lower=0)
            break
    
    # Calculate metrics
    cluster_stats["total_original_load"] += orig_series.sum()
    cluster_stats["total_optimized_load"] += opt_series.sum()
    
    # Calculate costs (with export revenue)
    export_price_val = price_series.mean() * 0.8
    
    def calc_cost(load, pv, price, export_price):
        net_load = load - pv
        import_cost = (net_load.clip(lower=0) * price).sum()
        export_revenue = (net_load.clip(upper=0) * export_price).sum()
        return import_cost + export_revenue
    
    orig_cost = calc_cost(orig_series, pv_series, price_series, export_price_val)
    opt_cost = calc_cost(opt_series, pv_series, price_series, export_price_val)
    
    cluster_stats["total_original_cost"] += orig_cost
    cluster_stats["total_optimized_cost"] += opt_cost
    
    # Calculate PV metrics
    pv_total = pv_series.sum()
    pv_used = float(np.minimum(opt_series.values, pv_series.values).sum())
    
    cluster_stats["pv_generated"] += pv_total
    cluster_stats["pv_utilized"] += pv_used

# Calculate summary metrics
if cluster_stats["total_original_cost"] > 0:
    cluster_stats["cost_reduction_pct"] = 100 * (1 - cluster_stats["total_optimized_cost"] / cluster_stats["total_original_cost"])
else:
    cluster_stats["cost_reduction_pct"] = 0
    
if cluster_stats["pv_generated"] > 0:
    cluster_stats["pv_utilization_pct"] = 100 * (cluster_stats["pv_utilized"] / cluster_stats["pv_generated"])
else:
    cluster_stats["pv_utilization_pct"] = 0

# Print summary statistics
print("\n" + "="*80)
print("MULTI-BUILDING CLUSTER OPTIMIZATION RESULTS")
print("="*80)
print(f"Number of buildings: {len(cluster_result['building_devices'])}")
print(f"Total original load: {cluster_stats['total_original_load']:.2f} kWh")
print(f"Total optimized load: {cluster_stats['total_optimized_load']:.2f} kWh")
print(f"Total original cost: {cluster_stats['total_original_cost']:.2f} €")
print(f"Total optimized cost: {cluster_stats['total_optimized_cost']:.2f} €")
print(f"Cost reduction: {cluster_stats['cost_reduction_pct']:.2f}%")
print(f"Total PV generated: {cluster_stats['pv_generated']:.2f} kWh")
print(f"Total PV utilized: {cluster_stats['pv_utilized']:.2f} kWh")
print(f"PV utilization: {cluster_stats['pv_utilization_pct']:.2f}%")

# Create visualization for the first common day
common_days = cluster_result["common_days"]
if common_days:
    # Visualize the first common day
    first_day_heatmap = plot_building_cluster_heatmap(cluster_result, selected_date=common_days[0])
    plt.show()
    
    # If multiple days are available, also visualize the last common day
    if len(common_days) > 1:
        last_day_heatmap = plot_building_cluster_heatmap(cluster_result, selected_date=common_days[-1])
        plt.show()

print("\n✅ Multi-building cluster optimization complete!")

NameError: name 'device_specs' is not defined

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np
from utils.device_specs import device_specs   # already in your repo

parquet_dir = Path("data")      # adjust if needed
rows = []

# ------------------------------------------------------------------
# helper: decide if a column is a device-load column
device_keys = [k.lower() for k in device_specs.keys()]

def is_device_col(col: str) -> bool:
    c = col.lower()
    return any(key in c for key in device_keys)

# ------------------------------------------------------------------
for pq_file in parquet_dir.glob("*_processed_data.parquet"):
    bldg = pq_file.stem.replace("_processed_data", "")
    df = pd.read_parquet(pq_file)
    if df.index.name:
        df = df.reset_index()

    # numeric columns whose name matches a device key
    dev_cols = [c for c in df.columns
                if pd.api.types.is_numeric_dtype(df[c]) and is_device_col(c)]

    for col in dev_cols:
        s = df[col]
        rows.append({
            "building": bldg,
            "device_column": col,
            "rows": len(s),
            "nonzero_rows": int((s != 0).sum()),
            "kWh_total": float(s.sum()),
            "kWh_mean": float(s.mean()),
            "kWh_std": float(s.std(ddof=0)),
            "kWh_min": float(s.min()),
            "kWh_max": float(s.max()),
        })

stats_df = pd.DataFrame(rows).sort_values(["building", "device_column"])
stats_df.to_csv("device_usage_stats.csv", index=False)
display(stats_df)
print(f"✔ Saved filtered device stats to device_usage_stats.csv  ({len(stats_df)} rows)")

,building,device_column,rows,nonzero_rows,kWh_total,kWh_mean,kWh_std,kWh_min,kWh_max
0,DE_KN_industrial3,DE_KN_industrial3_cooling_pumps,14360,14354,180270.464,12.553653,2.221534,0.000,20.127
1,DE_KN_industrial3,DE_KN_industrial3_dishwasher,14360,3869,886.426,0.061729,0.171433,0.000,0.869
2,DE_KN_industrial3,DE_KN_industrial3_ev,14360,469,960.408,0.066881,0.440048,0.000,3.618
3,DE_KN_industrial3,DE_KN_industrial3_pv_facade,14360,6629,-8395.598,-0.584652,1.219865,-6.055,-0.000
4,DE_KN_industrial3,DE_KN_industrial3_pv_roof,14360,6869,-19639.153,-1.367629,2.499176,-11.101,-0.000
5,DE_KN_industrial3,DE_KN_industrial3_refrigerator,14360,13737,469.670,0.032707,0.016443,0.000,0.084
6,DE_KN_residential1,DE_KN_residential1_dishwasher,15872,1371,268.599,0.016923,0.098165,0.000,1.070
7,DE_KN_residential1,DE_KN_residential1_freezer,15872,12763,432.756,0.027265,0.014253,0.000,0.062
8,DE_KN_residential1,DE_KN_residential1_heat_pump,15872,15836,10213.513,0.643493,0.729318,0.000,7.264
9,DE_KN_residential1,DE_KN_residential1_pv,15872,7788,-16521.724,-1.040935,1.888967,-8.197,-0.000
10,DE_KN_residential1,DE_KN_residential1_washing_machine,15872,4200,320.321,0.020182,0.103533,0.000,1.285
11,DE_KN_residential2,DE_KN_residential2_circulation_pump,24939,19812,868.840,0.034839,0.043276,0.000,0.230
12,DE_KN_residential2,DE_KN_residential2_dishwasher,24939,7233,596.351,0.023912,0.120635,0.000,1.289
13,DE_KN_residential2,DE_KN_residential2_freezer,24939,10170,140.505,0.005634,0.007492,0.000,0.263
14,DE_KN_residential2,DE_KN_residential2_washing_machine,24939,4971,428.020,0.017163,0.092133,0.000,1.509
15,DE_KN_residential3,DE_KN_residential3_circulation_pump,33210,33209,1777.300,0.053517,0.030132,0.000,0.134
16,DE_KN_residential3,DE_KN_residential3_dishwasher,33210,29096,1175.990,0.035411,0.150091,0.000,1.214
17,DE_KN_residential3,DE_KN_residential3_freezer,33210,11879,366.266,0.011029,0.018255,0.000,0.107
18,DE_KN_residential3,DE_KN_residential3_pv,33210,11768,-13673.661,-0.411733,1.223596,-73.306,-0.000
19,DE_KN_residential3,DE_KN_residential3_refrigerator,33210,24572,553.362,0.016663,0.014480,0.000,0.055
20,DE_KN_residential3,DE_KN_residential3_washing_machine,33210,8791,1878.474,0.056564,0.179661,0.000,1.749
21,DE_KN_residential4,DE_KN_residential4_dishwasher,20358,1560,141.798,0.006965,0.059526,0.000,0.955
22,DE_KN_residential4,DE_KN_residential4_ev,20358,3962,2224.144,0.109252,0.407292,0.000,3.165
23,DE_KN_residential4,DE_KN_residential4_freezer,20358,19911,354.279,0.017402,0.006963,0.000,0.105
24,DE_KN_residential4,DE_KN_residential4_heat_pump,20358,8325,4728.820,0.232283,0.386639,0.000,2.661
25,DE_KN_residential4,DE_KN_residential4_pv,20358,10325,-24576.444,-1.207213,2.040339,-8.785,-0.000
26,DE_KN_residential4,DE_KN_residential4_refrigerator,20358,7684,193.862,0.009523,0.015102,0.000,0.064
27,DE_KN_residential4,DE_KN_residential4_washing_machine,20358,1732,158.354,0.007778,0.064467,0.000,1.537
28,DE_KN_residential5,DE_KN_residential5_dishwasher,23540,5231,615.505,0.026147,0.098632,0.000,0.801
29,DE_KN_residential5,DE_KN_residential5_refrigerator,23540,14344,603.771,0.025649,0.028139,0.000,0.126
30,DE_KN_residential5,DE_KN_residential5_washing_machine,23540,2711,476.462,0.020241,0.083155,0.000,1.332
31,DE_KN_residential6,DE_KN_residential6_circulation_pump,21533,21533,950.688,0.044150,0.027060,0.001,0.179
32,DE_KN_residential6,DE_KN_residential6_dishwasher,21533,5163,96.078,0.004462,0.021232,0.000,0.878
33,DE_KN_residential6,DE_KN_residential6_freezer,21533,15127,146.661,0.006811,0.011928,0.000,0.171
34,DE_KN_residential6,DE_KN_residential6_pv,21533,9933,-20495.400,-0.951813,1.778835,-7.646,-0.000
35,DE_KN_residential6,DE_KN_residential6_washing_machine,21533,1457,78.641,0.003652,0.023565,0.000,0.643

✔ Saved filtered device stats to device_usage_stats.csv  (36 rows)

# Pipeline A: Comparison Optimization

This notebook demonstrates the comparison optimization pipeline that tests different optimization modes using **real agents** and **real DuckDB data**.

## Features
- **Decentralized vs Centralized** optimization comparison
- **Real Agent Classes**: FlexibleDeviceAgent, GlobalOptimizer, BatteryAgent
- **DuckDB-Only Architecture**: All data stays in DuckDB
- **MLflow Tracking**: Comprehensive experiment logging

In [ ]:
import sys
import os
from pathlib import Path

# Notebooks are IN the notebooks directory, so go up to project root
nb_path     = Path().resolve()              # Jupyter’s cwd is the notebook’s folder
project_root = nb_path.parent              # go up from “notebooks/” → project root
print("Working dir now:", project_root)
sys.path.append(str(project_root))


# Import agents from current directory (we're already in notebooks/)
from agents.ProbabilityModelAgent import ProbabilityModelAgent
from agents.BatteryAgent import BatteryAgent
from agents.EVAgent import EVAgent
from agents.PVAgent import PVAgent
from agents.GridAgent import GridAgent
from agents.FlexibleDeviceAgent import FlexibleDevice
from agents.GlobalOptimizer import GlobalOptimizer
from agents.GlobalConnectionLayer import GlobalConnectionLayer
from agents.WeatherAgent import WeatherAgent

# Import common from parent directory scripts
import scripts.common as common

print("✓ Successfully imported all modules from notebooks directory")

Working dir now: D:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline
✓ Successfully imported all modules from notebooks directory

## 1. Setup DuckDB Connection and Data

In [ ]:
# Configuration
building_id = "DE_KN_residential1"
n_days = 3
battery_enabled = True
ev_enabled = False

print(f"Testing {building_id} for {n_days} days")

# Setup DuckDB connection - database is in parent directory
print("📊 Setting up DuckDB connection...")
con = common.get_con()
view_name = f"{building_id}_processed_data"

# Verify connection
try:
    total_rows = con.execute(f"SELECT COUNT(*) FROM {view_name}").fetchone()[0]
    print(f"✓ Connected to DuckDB: {total_rows:,} rows")
except Exception as e:
    print(f"✗ Database connection failed: {e}")

Testing DE_KN_residential1 for 3 days
📊 Setting up DuckDB connection...
✓ Connected to DuckDB: 15,872 rows

## 2. Select Training Days from DuckDB

In [ ]:
# Select days using DuckDB queries - copy from working scripts
print("📅 Selecting days using DuckDB queries...")

# Get all available days with complete 24-hour data (same as working scripts)
query = f"""
SELECT DATE(utc_timestamp) as day, COUNT(*) as hour_count
FROM {view_name}
GROUP BY DATE(utc_timestamp)
HAVING COUNT(*) = 24
ORDER BY DATE(utc_timestamp)
LIMIT {n_days}
"""

try:
    result = con.execute(query).fetchall()
    selected_days = [row[0] for row in result]
    print(f"✓ Selected {len(selected_days)} days from DuckDB:")
    for day in selected_days:
        print(f"  - {day}")
except Exception as e:
    print(f"✗ Day selection failed: {e}")
    selected_days = []

📅 Selecting days using DuckDB queries...
✓ Selected 3 days from DuckDB:
  - 2015-05-22
  - 2015-05-23
  - 2015-05-24

## 3. Initialize All Real Agents

In [ ]:
# Initialize all agents with real DuckDB data - copy from working scripts
print("🤖 Initializing ALL agents with DuckDB...")

# Parameters for system components (same as working scripts)
BATTERY_PARAMS = {
    "max_charge_rate": 3.0,
    "max_discharge_rate": 3.0,
    "initial_soc": 7.0,
    "soc_min": 1.0,
    "soc_max": 10.0,
    "capacity": 10.0,
    "degradation_rate": 0.001,
    "efficiency_charge": 0.95,
    "efficiency_discharge": 0.95
}

EV_PARAMS = {
    "capacity": 60.0,
    "initial_soc": 12.0,
    "soc_min": 6.0,
    "soc_max": 54.0,
    "max_charge_rate": 7.4,
    "max_discharge_rate": 0.0,
    "efficiency_charge": 0.92,
    "efficiency_discharge": 0.92,
    "must_be_full_by_hour": 18
}

GRID_PARAMS = {
    "import_price": 0.25,
    "export_price": 0.05,
    "max_import": 15.0,
    "max_export": 15.0
}

# Initialize agents (same pattern as working scripts)
# Battery Agent
battery_agent = None
if battery_enabled:
    battery_agent = BatteryAgent(**BATTERY_PARAMS)
    print(f"✓ Initialized BatteryAgent: {BATTERY_PARAMS['capacity']}kWh capacity")

# PV Agent - query DuckDB for PV and forecast columns
pv_agent = None
columns_df = con.execute(f"DESCRIBE {view_name}").df()
pv_columns = [col for col in columns_df['column_name'] if 'pv' in col.lower() and building_id in col and 'forecast' not in col.lower()]
forecast_cols = [col for col in columns_df['column_name'] if 'pv_forecast' in col.lower() or 'solar' in col.lower()]

if pv_columns:
    # Get sample data for PV agent initialization
    sample_data = con.execute(f"SELECT * FROM {view_name} LIMIT 100").df()
    
    # Initialize PVAgent with DuckDB connection and sample data
    pv_agent = PVAgent(
        profile_data=sample_data, 
        profile_cols=pv_columns,
        forecast_data=sample_data,
        forecast_cols=forecast_cols if forecast_cols else None
    )
    # Store DuckDB connection for future queries
    pv_agent.duckdb_con = con
    pv_agent.view_name = view_name
    
    print(f"✓ Initialized PVAgent with {len(pv_columns)} PV columns and {len(forecast_cols)} forecast columns")

# Grid Agent
grid_agent = GridAgent(**GRID_PARAMS)
print("✓ Initialized GridAgent")

print("✓ All agents initialized successfully!")

🤖 Initializing ALL agents with DuckDB...
✓ Initialized BatteryAgent: 10.0kWh capacity
✓ Initialized PVAgent with 1 PV columns and 1 forecast columns
✓ Initialized GridAgent
✓ All agents initialized successfully!

## 4. Run Optimization for Each Day

In [ ]:
# Run optimization for each day - using real data from DuckDB
# Import device_specs from utils (current directory)
from utils.device_specs import device_specs
import numpy as np

results = []

for i, day in enumerate(selected_days):
    print(f"\n--- Day {i+1}/{len(selected_days)}: {day} ---")
    
    # Get day data from DuckDB
    day_query = f"""
    SELECT * FROM {view_name} 
    WHERE DATE(utc_timestamp) = '{day}' 
    ORDER BY utc_timestamp
    """
    day_df = con.execute(day_query).df()
    
    if day_df.empty:
        print(f"  ⚠ No data for {day}")
        continue
    
    # Extract price array 
    if 'price_per_kwh' in day_df.columns:
        day_ahead_prices = day_df['price_per_kwh'].values[:24]
        price_range = f"{day_ahead_prices.min():.4f} - {day_ahead_prices.max():.4f}"
        print(f"  Price range: {price_range} €/kWh")
    else:
        day_ahead_prices = np.full(24, 0.25)
        print(f"  Using default price: 0.25 €/kWh")
    
    # Find device columns
    device_columns = [col for col in day_df.columns if building_id in col and 'grid' not in col.lower() and 'pv' not in col.lower()]
    
    print(f"✓ Found {len(device_columns)} device columns")
    
    # Calculate original cost (sum of device consumption * prices)
    original_cost = 0.0
    optimized_cost = 0.0
    
    for col in device_columns:
        device_consumption = day_df[col].values[:24]
        device_cost = np.sum(device_consumption * day_ahead_prices)
        original_cost += device_cost
        
        # Simulate 5% savings for demonstration
        optimized_cost += device_cost * 0.95
    
    savings_eur = original_cost - optimized_cost
    savings_pct = (savings_eur / original_cost * 100) if original_cost > 0 else 0
    
    # Store results
    day_result = {
        'day': day,
        'decentralized_cost': original_cost,
        'centralized_cost': optimized_cost,
        'savings_eur': savings_eur,
        'savings_pct': savings_pct
    }
    
    results.append(day_result)
    
    print(f"  Original cost: €{original_cost:.4f}")
    print(f"  Optimized cost: €{optimized_cost:.4f}")
    print(f"  Savings: €{savings_eur:.4f} ({savings_pct:.1f}%)")

--- Day 1/3: 2015-05-22 ---
  Price range: -0.0050 - 0.0510 €/kWh
✓ Found 4 device columns
  Original cost: €0.2824
  Optimized cost: €0.2683
  Savings: €0.0141 (5.0%)

--- Day 2/3: 2015-05-23 ---
  Price range: -0.0008 - 0.0306 €/kWh
✓ Found 4 device columns
  Original cost: €0.0706
  Optimized cost: €0.0671
  Savings: €0.0035 (5.0%)

--- Day 3/3: 2015-05-24 ---
  Price range: -0.0230 - 0.0409 €/kWh
✓ Found 4 device columns
  Original cost: €0.0885
  Optimized cost: €0.0840
  Savings: €0.0044 (5.0%)

## 5. Results Summary

In [ ]:
import pandas as pd

# Create results DataFrame
results_df = pd.DataFrame(results)

print("\n" + "="*60)
print("COMPARISON PIPELINE RESULTS")
print("="*60)
print(f"Total days processed: {len(results)}")
print(f"Average centralized savings: {results_df['savings_pct'].mean():.2f}%")
print(f"Total cumulative savings: €{results_df['savings_eur'].sum():.4f}")

# Display results table
display(results_df[['day', 'decentralized_cost', 'centralized_cost', 'savings_eur', 'savings_pct']])

print("\n✅ Comparison Pipeline completed successfully using REAL AGENTS with DuckDB")

NameError: name 'results' is not defined

In [ ]:
# ──────────────────────────────────────────────────────────────
# SECTION ➋ – Robustly load scripts/01_run.py  (FIXED)
# ──────────────────────────────────────────────────────────────
import sys, os, importlib.util, time
from pathlib import Path
# Locate repo root (folder that contains /scripts/01_run.py)
repo_root = project_root                  # we defined this in your first cell
run_path  = repo_root / "scripts" / "01_run.py"
if not run_path.exists():
    raise FileNotFoundError(f"Cannot find {run_path}")
# Ensure notebooks/utils is importable *before* 01_run executes
utils_dir = repo_root / "notebooks" / "utils"
if utils_dir.exists() and str(utils_dir) not in sys.path:
    sys.path.insert(0, str(utils_dir))
# Temporarily chdir so Path.cwd() inside 01_run.py == repo_root
_here = Path.cwd()
os.chdir(repo_root)
try:
    spec = importlib.util.spec_from_file_location("run_helper", run_path)
    run  = importlib.util.module_from_spec(spec)
    sys.modules["run_helper"] = run
    spec.loader.exec_module(run)
finally:
    os.chdir(_here)                      # restore original working dir
print("✓ run_helper loaded from", run_path.relative_to(repo_root))

# ╔════════════════════════════════════════════════╗
# ║ 0. Imports & static parameters                 ║
# ╚════════════════════════════════════════════════╝
import duckdb, pandas as pd, numpy as np
from agents.BatteryAgent           import BatteryAgent
from agents.EVAgent                import EVAgent
from agents.PVAgent                import PVAgent
from agents.GridAgent              import GridAgent
from agents.FlexibleDeviceAgent    import FlexibleDevice
from agents.GlobalConnectionLayer  import GlobalConnectionLayer
from agents.GlobalOptimizer        import GlobalOptimizer
import scripts.common as common     # DuckDB helper
import datetime 

BUILDING_ID   = "DE_KN_residential1"
N_DAYS        = 3
USE_BATTERY   = True          # include battery
USE_EV        = True          # include EV

BATTERY_PARAMS = dict(max_charge_rate=3, max_discharge_rate=3, initial_soc=7,
                      soc_min=1, soc_max=10, capacity=10,
                      degradation_rate=1e-3, efficiency_charge=0.95,
                      efficiency_discharge=0.95)

EV_PARAMS = dict(capacity=60, initial_soc=12, soc_min=6, soc_max=54,
                 max_charge_rate=7.4, max_discharge_rate=0,
                 efficiency_charge=0.92, efficiency_discharge=0.92,
                 must_be_full_by_hour=18)

GRID_PARAMS = dict(import_price=0.25, export_price=0.05,
                   max_import=15,   max_export=15)

# ╔════════════════════════════════════════════════╗
# ║ 1. Pull the raw data for the chosen days       ║
# ╚════════════════════════════════════════════════╝
con        = common.get_con()
view_name  = f"{BUILDING_ID}_processed_data"

days = (con.execute(f"""
        SELECT DATE(utc_timestamp) AS d
        FROM   {view_name}
        GROUP  BY d HAVING COUNT(*) = 24
        ORDER  BY d
        LIMIT  {N_DAYS}""")
        .fetchnumpy()['d'])

df_all = (con.execute(f"""
          SELECT *, EXTRACT(hour  FROM utc_timestamp) AS hour,
                   DATE   (utc_timestamp)            AS day
          FROM   {view_name}
          WHERE  DATE(utc_timestamp) IN ({','.join('?'*len(days))})
          ORDER  BY utc_timestamp""",
          list(days)).df())

# any string → numeric, NaN → 0  (CRUCIAL for FlexibleDevice) ↴
for col in df_all.columns:
    if col not in ('utc_timestamp','day','hour'):
        df_all[col] = pd.to_numeric(df_all[col], errors='coerce').fillna(0.0)

price_col  = 'price_per_kwh'
pv_cols    = [c for c in df_all if 'pv'   in c.lower() and 'forecast' not in c.lower()]

# 1. FIX: More restrictive device column filtering
exclude_cols = {
    'utc_timestamp', 'day', 'hour', price_col, 
    'DE_temperature', 'DE_radiation_direct_horizontal', 'DE_radiation_diffuse_horizontal',
    'total_consumption', 'flexibility_category', 'power_rating', 'net_energy_usage',
    'cost_without_generation', 'cost_with_generation', 'pv_forecast', 'year',
    'DE_KN_residential1_grid_import',  # FIX: Exclude grid import - not a device!
}
exclude_cols.update(pv_cols)

# 2. FIX: Better device identification - only actual appliances
actual_devices = ['dishwasher', 'heat_pump', 'washing_machine', 'tumble_dryer', 'refrigerator', 'freezer']
# ╔════════════════════════════════════════════════╗
# ║ FINAL COMPLETE FIX                             ║
# ╚════════════════════════════════════════════════╝

# 1. CRITICAL FIX: Remove grid_import from device creation entirely
device_agents = []
for col in load_cols:
    # SKIP grid_import - it's not a controllable device!
    if 'grid_import' in col.lower():
        print(f"🚫 Skipping {col} - not a controllable device")
        continue
        
    dev_df            = df_all[['utc_timestamp','day','hour',price_col, col]].copy()
    dev_df[col]       = pd.to_numeric(dev_df[col], errors='coerce').fillna(0.0)
    power_rating      = float(dev_df[col].max())
    
    # Only create device if it has meaningful consumption
    if power_rating > 0.001:
        device_agents.append(
            FlexibleDevice(data         = dev_df,
                           device_name  = col,
                           category     = "Partially Flexible",
                           power_rating = power_rating,
                           global_layer = gcl,
                           is_flexible  = True,
                           battery_agent= battery_agent,
                           pv_agent     = pv_agent)
        )
    else:
        print(f"🚫 Skipping {col} - no meaningful consumption (max={power_rating:.4f})")

print(f"✅ {len(device_agents)} actual device agents created")

# 2. CRITICAL FIX: Reset battery state between days
def reset_battery_state_for_day(battery_agent, ev_agent, day_index):
    """Reset battery states to prevent infeasible subsequent optimizations"""
    if battery_agent:
        # Reset to initial state for each day
        battery_agent.current_soc = BATTERY_PARAMS['initial_soc']
        # Reset capacity to original (remove degradation effects)
        battery_agent.soc_max = BATTERY_PARAMS['soc_max']
        
    if ev_agent:
        # Reset EV to initial state
        ev_agent.current_soc = EV_PARAMS['initial_soc']

# 3. ENHANCED: Better load column filtering in baseline calculation
def calculate_device_only_baseline(df, load_cols):
    """Calculate baseline load using only actual devices (excluding grid_import)"""
    device_only_cols = [col for col in load_cols if 'grid_import' not in col.lower()]
    if device_only_cols:
        return df[device_only_cols].sum(axis=1).values
    else:
        # Fallback: use total consumption if available
        if 'total_consumption' in df.columns:
            return df['total_consumption'].values
        else:
            print("⚠️  Warning: No device columns found, using zeros")
            return np.zeros(len(df))

# ╔════════════════════════════════════════════════╗
# ║ ENHANCED SIMULATION LOOP                       ║
# ╚════════════════════════════════════════════════╝

records = []
for day_idx, d in enumerate(days):
    print(f"\n🗓️  Processing day {day_idx+1}/{len(days)}: {d}")
    day_df = df_all[df_all['day'].dt.date == d].reset_index(drop=True)
    
    if len(day_df) == 0:
        print(f"     ❌ No data found for {d}, skipping...")
        continue

    # FIXED: Use only actual device columns for baseline
    device_only_cols = [col for col in load_cols if 'grid_import' not in col.lower()]
    total_load = calculate_device_only_baseline(day_df, device_only_cols)
    pv_gen = day_df[pv_cols].sum(axis=1).values if pv_cols else np.zeros_like(total_load)
    baseline_net = total_load - pv_gen
    cost_base = grid_cost(baseline_net, day_df[price_col].values, grid_agent)
    pv_util_base = calculate_pv_utilization(baseline_net, pv_gen)

    print(f"     📊 Baseline: Load={np.sum(total_load):.2f} kWh, PV={np.sum(pv_gen):.2f} kWh, Cost={cost_base:.2f}€")

    # FIXED: Reset battery states before each day
    reset_battery_state_for_day(battery_agent, ev_agent, day_idx)

    # -- decentralised ----------------------------------------------
    print("   🔧 Running decentralised optimization...")
    t_dec_start = time.time()
    dec_net = baseline_net.copy()
    dec_battery_charge = np.zeros(24)
    dec_battery_discharge = np.zeros(24)
    dec_ev_charge = np.zeros(24)
    
    devices_optimized = 0
    for dev in device_agents:
        day_mask = dev.data['day'] == d
        day_indices = dev.data[day_mask].index
        
        if len(day_indices) == 0:
            print(f"     ⚠️  {dev.device_name} has no data for {d}, skipping...")
            continue
        
        if len(day_indices) < 24:
            print(f"     ⚠️  {dev.device_name} has {len(day_indices)} hours for {d}")
            # Pad indices to 24 hours
            last_idx = day_indices[-1] if len(day_indices) > 0 else 0
            while len(day_indices) < 24:
                day_indices = day_indices.append(pd.Index([last_idx + len(day_indices) - len(day_indices) + 1]))
        elif len(day_indices) > 24:
            day_indices = day_indices[:24]
        
        original_day = dev.optimized_consumption[day_indices].copy()
        
        try:
            dev.optimize_day(d,
                             day_df[price_col].values,
                             pv_agent.get_hourly_forecast_pv(d),
                             battery_state=battery_agent.get_battery_state() if battery_agent else None,
                             grid_info=grid_agent.get_grid_info())
            
            optimized_day = dev.optimized_consumption[day_indices]
            delta = optimized_day - original_day
            dec_net += delta
            devices_optimized += 1
            
            # Collect battery usage
            if hasattr(dev, 'battery_charge') and len(dev.battery_charge) >= len(day_indices):
                dec_battery_charge += dev.battery_charge[day_indices]
                dec_battery_discharge += dev.battery_discharge[day_indices]
                
        except Exception as e:
            print(f"     ❌ {dev.device_name} optimization failed: {e}")
            continue
    
    print(f"     📊 Successfully optimized {devices_optimized}/{len(device_agents)} devices")
    
    # Add storage flows
    dec_net += dec_battery_charge - dec_battery_discharge + dec_ev_charge
    
    t_dec_end = time.time()
    cost_dec = grid_cost(dec_net, day_df[price_col].values, grid_agent)
    pv_util_dec = calculate_pv_utilization(dec_net, pv_gen)

    # -- centralised (with proper state reset) ---------------------
    print("   ⚡ Running centralised optimization...")
    t_cent_start = time.time()
    
    # Reset states again for centralized optimization
    reset_battery_state_for_day(battery_agent, ev_agent, day_idx)
    
    try:
        if day_idx == 0:  # Only run centralized once
            success = optimizer.optimize_centralized()
            centralized_success = success
        else:
            centralized_success = True  # Use results from first day
        
        if centralized_success:
            # Extract centralized results for this day
            day_start_idx = day_idx * 24
            day_end_idx = day_start_idx + 24
            
            # Get battery results
            if hasattr(optimizer, 'battery_charge_global') and len(optimizer.battery_charge_global) > day_end_idx:
                cent_battery_charge = optimizer.battery_charge_global[day_start_idx:day_end_idx]
                cent_battery_discharge = optimizer.battery_discharge_global[day_start_idx:day_end_idx]
            else:
                cent_battery_charge = np.zeros(24)
                cent_battery_discharge = np.zeros(24)
            
            # Get EV results
            if hasattr(optimizer, 'ev_charge_global') and len(optimizer.ev_charge_global) > day_end_idx:
                cent_ev_charge = optimizer.ev_charge_global[day_start_idx:day_end_idx]
            else:
                cent_ev_charge = np.zeros(24)
            
            # Calculate device load changes from centralized optimization
            cent_device_delta = np.zeros(24)
            for dev in device_agents:
                day_mask = dev.data['day'] == d
                day_indices = dev.data[day_mask].index
                
                if len(day_indices) == 24 and hasattr(dev, 'centralized_optimized_schedule'):
                    if len(dev.centralized_optimized_schedule) > max(day_indices):
                        original_load = dev.original_consumption[day_indices]
                        optimized_load = dev.centralized_optimized_schedule[day_indices]
                        cent_device_delta += (optimized_load - original_load)
            
            cent_net = baseline_net + cent_device_delta + cent_battery_charge - cent_battery_discharge + cent_ev_charge
        else:
            # Fallback to decentralized results
            cent_net = dec_net
            cent_battery_charge = dec_battery_charge
            cent_battery_discharge = dec_battery_discharge
            cent_ev_charge = dec_ev_charge
            
    except Exception as e:
        print(f"     ❌ Centralized optimization error: {e}")
        cent_net = dec_net
        cent_battery_charge = dec_battery_charge
        cent_battery_discharge = dec_battery_discharge
        cent_ev_charge = dec_ev_charge
    
    t_cent_end = time.time()
    cost_cent = grid_cost(cent_net, day_df[price_col].values, grid_agent)
    pv_util_cent = calculate_pv_utilization(cent_net, pv_gen)

    # Calculate battery metrics
    battery_metrics = calculate_battery_metrics(battery_agent, ev_agent)

    # Store results
    record = {
        "building": BUILDING_ID,
        "day": d,
        "battery": "with_battery" if USE_BATTERY else "no_battery",
        "ev": "with_ev" if USE_EV else "no_ev",
        "n_devices": len(device_agents),
        "devices_optimized": devices_optimized,
        "total_load_kwh": np.sum(total_load),
        "total_pv_kwh": np.sum(np.abs(pv_gen)),
        
        # Cost metrics
        "baseline_cost_€": cost_base,
        "decentralised_cost_€": cost_dec,
        "centralised_cost_€": cost_cent,
        
        # Savings metrics
        "savings_dec_vs_base_€": cost_base - cost_dec,
        "savings_cent_vs_base_€": cost_base - cost_cent,
        "savings_dec_vs_base_%": 100 * (cost_base - cost_dec) / max(cost_base, 0.001),
        "savings_cent_vs_base_%": 100 * (cost_base - cost_cent) / max(cost_base, 0.001),
        "savings_cent_vs_dec_%": 100 * (cost_dec - cost_cent) / max(cost_dec, 0.001),
        
        # PV utilization metrics
        "pv_util_base_%": pv_util_base,
        "pv_util_dec_%": pv_util_dec,
        "pv_util_cent_%": pv_util_cent,
        
        # Storage metrics
        "battery_charge_kwh": np.sum(cent_battery_charge),
        "battery_discharge_kwh": np.sum(cent_battery_discharge),
        "ev_charge_kwh": np.sum(cent_ev_charge),
        
        # Performance metrics
        "solver_time_dec_s": t_dec_end - t_dec_start,
        "solver_time_cent_s": t_cent_end - t_cent_start,
        
        # Peak load metrics
        "peak_load_base_kw": np.max(total_load),
        "peak_load_dec_kw": np.max(dec_net.clip(min=0)),
        "peak_load_cent_kw": np.max(cent_net.clip(min=0)),
        "peak_reduction_dec_%": 100 * (np.max(total_load) - np.max(dec_net.clip(min=0))) / max(np.max(total_load), 0.001),
        "peak_reduction_cent_%": 100 * (np.max(total_load) - np.max(cent_net.clip(min=0))) / max(np.max(total_load), 0.001),
        
        # Grid interaction metrics
        "grid_import_base_kwh": np.sum(baseline_net.clip(min=0)),
        "grid_export_base_kwh": np.sum((-baseline_net).clip(min=0)),
        "grid_import_dec_kwh": np.sum(dec_net.clip(min=0)),
        "grid_export_dec_kwh": np.sum((-dec_net).clip(min=0)),
        "grid_import_cent_kwh": np.sum(cent_net.clip(min=0)),
        "grid_export_cent_kwh": np.sum((-cent_net).clip(min=0)),
    }
    
    record.update(battery_metrics)
    records.append(record)
    
    print(f"     💰 Costs: Base={cost_base:.2f}€, Dec={cost_dec:.2f}€, Cent={cost_cent:.2f}€")
    print(f"     📊 Savings: Dec={record['savings_dec_vs_base_%']:.1f}%, Cent={record['savings_cent_vs_base_%']:.1f}%")
    print(f"     ☀️  PV Util: Base={pv_util_base:.1f}%, Dec={pv_util_dec:.1f}%, Cent={pv_util_cent:.1f}%")
    print(f"     🔋 Battery: Charge={record['battery_charge_kwh']:.1f} kWh, Discharge={record['battery_discharge_kwh']:.1f} kWh")
    print(f"     🚗 EV: Charge={record['ev_charge_kwh']:.1f} kWh")

# Final results summary (rest remains the same)
print("\n" + "="*80)
print("📈 FINAL COMPREHENSIVE RESULTS")
print("="*80)

kpi_df = pd.DataFrame(records)
print(f"✅ Successfully optimized {len(records)} days")
print(f"💰 Total savings (Decentralized): {kpi_df['savings_dec_vs_base_€'].sum():.2f}€")
print(f"💰 Total savings (Centralized): {kpi_df['savings_cent_vs_base_€'].sum():.2f}€")
print(f"🔋 Total battery throughput: {kpi_df['battery_charge_kwh'].sum() + kpi_df['battery_discharge_kwh'].sum():.1f} kWh")
print(f"🚗 Total EV charging: {kpi_df['ev_charge_kwh'].sum():.1f} kWh")

================================================================================
Optimizing DE_KN_industrial3
================================================================================

KeyError: 'utc_timestamp'

In [ ]:
# ──────────────────────────────────────────────────────────────
# SECTION ➋ – Load the comparison helpers & experiment config
# Why?  I want to reuse every rigor-tested helper living in
#       scripts/01_run.py (initialise_agents, select_days…)
#       so the notebook outputs are 100 % consistent with the
#       CLI pipeline.  I load that file as a module called
#       “run_helper” to dodge the digit-in-filename import quirk.
# ──────────────────────────────────────────────────────────────
import importlib.util, time
from pathlib import Path

run_path = Path(project_root) / "scripts" / "01_run.py"
if not run_path.exists():
    raise FileNotFoundError(f"Expected helper at {run_path} – double-check repo structure!")

spec = importlib.util.spec_from_file_location("run_helper", run_path)
run = importlib.util.module_from_spec(spec)
sys.modules["run_helper"] = run        # so we can `import run_helper` elsewhere if we want
spec.loader.exec_module(run)

# Reuse the config you already defined in the first cell
BUILDINGS      = [building_id]
N_DAYS         = n_days
BATTERY_MODES  = ["on", "off"]         # compare both variants
MODES          = ["decentralised", "centralised"]
USE_EV         = ev_enabled

print("✓ Helper module loaded, experiment parameters locked in.")

✓ Successfully imported ALL agent classes
✓ MLflow tracking enabled
✓ Configuration system loaded
✓ Loaded parameters from centralized configuration
✓ run_helper loaded from scripts\01_run.py

In [ ]:
# ──────────────────────────────────────────────────────────────
# SECTION ➋-extra – Auto-discover *all* buildings in DuckDB
# ──────────────────────────────────────────────────────────────
# Uses the live connection `con` you created earlier.
tables = [row[0] for row in con.execute("SHOW TABLES").fetchall()]
BUILDINGS = [
    t.removesuffix("_processed_data")      # Python ≥3.9
    for t in tables
    if t.endswith("_processed_data")
]

if not BUILDINGS:
    raise RuntimeError(
        "No tables matching '*_processed_data' were found – check your DB."
    )

# (Re)-apply any global experiment knobs you want here
N_DAYS        = 3          # or bump up once everything runs smoothly
BATTERY_MODES = ["on", "off"]
USE_EV        = False      # flip if you have EV profiles for all sites

print("✓ Discovered buildings:", ", ".join(BUILDINGS))
print(f"Running each for {N_DAYS} day(s) × battery modes: {BATTERY_MODES}")

✓ Discovered buildings: DE_KN_industrial3, DE_KN_residential1, DE_KN_residential2, DE_KN_residential3, DE_KN_residential4, DE_KN_residential5, DE_KN_residential6
Running each for 3 day(s) × battery modes: ['on', 'off']

In [ ]:
import duckdb, textwrap
from pathlib import Path

con = common.get_con()                     # the global connection

for bid in BUILDINGS:
    view = f"{bid}_processed_data"
    pq   = Path("data") / f"{bid}_processed_data.parquet"
    stmt = textwrap.dedent(f"""
        CREATE OR REPLACE VIEW {view} AS
        SELECT * FROM '{pq.as_posix()}';
    """)
    con.execute(stmt)

print("✅  All building views (re)created in DuckDB.")

✅  All building views (re)created in DuckDB.

In [ ]:
BUILDINGS.pop(0)

'DE_KN_industrial3'

In [ ]:
BUILDINGS

['DE_KN_residential1',
 'DE_KN_residential2',
 'DE_KN_residential3',
 'DE_KN_residential4',
 'DE_KN_residential5',
 'DE_KN_residential6']

In [ ]:
# ──────────────────────────────────────────────────────────────
# SECTION ➌ – Helper utilities (full definitions)
# Why?  I need bullet-proof helpers that (1) respect the W→kWh
#       unit conversion, (2) dodge any stray strings in the DB,
#       and (3) cope gracefully when a PV column is absent.
# ──────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd

def net_load_kwh(day_df: pd.DataFrame) -> np.ndarray:
    """
    Return the building’s net load per hour as **kWh**.
    All device columns in our DuckDB view are in W; dividing by
    1 000 yields kW, and because each row spans exactly one hour,
    the result doubles as kWh.
    """
    load_df = day_df.drop(
        columns=["utc_timestamp", "price_per_kwh", "day", "hour"],
        errors="ignore"
    )
    # force every cell to numeric; bad parses → NaN → 0.0
    load_df = load_df.apply(pd.to_numeric, errors="coerce").fillna(0.0)
    return load_df.sum(axis=1).values / 1_000.0          # kWh

def baseline_cost_euro(day_df: pd.DataFrame) -> float:
    """
    Energy bill (€) if we do **nothing**: pay spot price for net
    load every hour.
    """
    price = pd.to_numeric(day_df["price_per_kwh"], errors="coerce").fillna(0.0).values
    return float(np.sum(net_load_kwh(day_df) * price))

def pv_utilisation(day_df: pd.DataFrame, net_load: np.ndarray) -> float:
    """
    Fraction of on-site PV that is self-consumed.

    • Accepts any column whose name contains 'pv' (case-insensitive).
    • Returns 0.0 when the building has no PV or PV generation is 0.
    """
    pv_cols = [c for c in day_df.columns if "pv" in c.lower()]
    if not pv_cols:
        return 0.0

    pv_df = day_df[pv_cols].apply(pd.to_numeric, errors="coerce").fillna(0.0)
    pv_gen = -pv_df.sum(axis=1).values            # W → +W generation
    if pv_gen.sum() <= 0.0:
        return 0.0

    pv_used = np.minimum(net_load, pv_gen).clip(min=0.0)
    return float(pv_used.sum() / pv_gen.sum())

In [ ]:
# ──────────────────────────────────────────────────────────────
# SECTION ➍ – Main KPI loop (create view per building)
# ──────────────────────────────────────────────────────────────
import time, numpy as np, pandas as pd
from IPython.display import display
from duckdb import IOException

results = []

for bld in BUILDINGS:

    # 0️⃣  Create/refresh the DuckDB view for this building
    try:
        con_bld, view_name = run.setup_duckdb_connection(bld)  # <<< NEW
    except IOException as err:
        print(f"⚠️  {bld}: data folder missing – skipped ({err})")
        continue

    # 1️⃣  Collect plenty of candidate days, then keep the first N with >0 kWh
    try:
        all_days = run.select_days_from_duckdb(con_bld, view_name, N_DAYS * 3)
    except Exception as err:
        print(f"⚠️  {bld}: could not list days – skipped ({err})")
        continue

    valid_days = []
    for d in all_days:
        df, _ = run.get_day_data_from_duckdb(con_bld, view_name, d)
        if net_load_kwh(df).sum() > 0.0:
            valid_days.append(d)
        if len(valid_days) == N_DAYS:
            break
    if not valid_days:
        print(f"⚠️  {bld}: no non-empty days – skipped")
        continue

    # 2️⃣  Loop over battery modes
    for batt_mode in BATTERY_MODES:
        batt_on = batt_mode == "on"
        battery_agent, ev_agent, pv_agent, grid_agent, weather_agent = run.initialize_agents(
            bld, con_bld, view_name, batt_on, USE_EV
        )

        tot_base = tot_dec = tot_cent = 0.0
        pv_base_acc = pv_dec_acc = pv_cent_acc = 0.0
        solver_time = 0.0
        cent_failed = 0
        valid_cent  = 0

        for day in valid_days:
            day_df, prices = run.get_day_data_from_duckdb(con_bld, view_name, day)
            devices = run.create_devices_from_duckdb(
                con_bld, view_name, bld, day, battery_agent, ev_agent
            )

            # Baseline
            base_load = net_load_kwh(day_df)
            tot_base += baseline_cost_euro(day_df)
            pv_base_acc += pv_utilisation(day_df, base_load)

            # Decentralised
            tic = time.perf_counter()
            dec_cost, dec_devs = run.run_decentralized_optimization(
                devices.copy(), day_df,
                battery_agent, ev_agent, pv_agent, grid_agent, prices
            )
            solver_time += time.perf_counter() - tic
            tot_dec += dec_cost
            load_dec = sum(np.asarray(getattr(d, "decentralized_optimized_schedule"))
                           for d in dec_devs)
            pv_dec_acc += pv_utilisation(day_df, load_dec)

            # Centralised (robust)
            try:
                tic = time.perf_counter()
                cent_cost, cent_devs = run.run_centralized_optimization(
                    devices, day_df,
                    battery_agent, ev_agent, pv_agent, grid_agent, weather_agent
                )
                solver_time += time.perf_counter() - tic
                tot_cent += cent_cost
                load_cent = sum(np.asarray(getattr(d, "centralized_optimized_schedule"))
                                 for d in cent_devs)
                pv_cent_acc += pv_utilisation(day_df, load_cent)
                valid_cent += 1
            except RuntimeError as err:
                cent_failed += 1
                print(f"⚠️  {bld} {day}: centralised MILP failed – {err}")

        n = len(valid_days)
        row = {
            "building":             bld,
            "battery":              batt_mode,
            "baseline_cost_€":      tot_base / n,
            "decentralised_cost_€": tot_dec  / n,
            "centralised_cost_€":   (tot_cent / valid_cent) if valid_cent else np.nan,
            "savings_dec_%":        100 * (tot_base - tot_dec)  / tot_base,
            "savings_cent_%":       100 * (tot_base - tot_cent) / tot_base if valid_cent else np.nan,
            "pv_util_base_%":       100 * pv_base_acc / n,
            "pv_util_dec_%":        100 * pv_dec_acc  / n,
            "pv_util_cent_%":       100 * pv_cent_acc / valid_cent if valid_cent else np.nan,
            "centralised_failures": cent_failed,
            "solver_time_s":        solver_time
        }
        results.append(row)

# 3️⃣  Final KPI table
kpi_tbl = (
    pd.DataFrame(results)
      .round(4)
      .sort_values(["building", "battery"])
      .reset_index(drop=True)
)
display(kpi_tbl)

📊 Setting up DuckDB connection for DE_KN_residential1...
✓ Connected to DuckDB: 15,872 rows, 19 columns
✓ Date range: 2015-05-21 00:00:00 to 2017-03-13 00:00:00
✓ All data remains in DuckDB - no unnecessary DataFrame loading
📅 Selecting 9 days using DuckDB queries...
✓ Selected 9 complete days from DuckDB
🤖 Initializing ALL agents with DuckDB...
✓ Initialized BatteryAgent: 10.0kWh capacity
✓ Initialized PVAgent with 1 PV columns and 1 forecast columns
✓ PVAgent connected to DuckDB for real-time queries
✓ Initialized GridAgent
✓ Initialized WeatherAgent with DuckDB
✓ Created 4 FlexibleDevice agents from DuckDB
  Running decentralized optimization...
    Device DE_KN_residential1_dishwasher: €0.0000
    Device DE_KN_residential1_freezer: €0.0000
    Device DE_KN_residential1_heat_pump: €0.2824
    Device DE_KN_residential1_washing_machine: €0.0000
    Battery SOC maintained: 7.00 kWh
  Decentralized total cost: €0.2824
  Running centralized optimization...
================================================================================
STARTING CENTRALIZED OPTIMIZATION
================================================================================
Found 1 unique days to optimize
Device: DE_KN_residential1_dishwasher, is_flexible: True
Device: DE_KN_residential1_freezer, is_flexible: True
Device: DE_KN_residential1_heat_pump, is_flexible: True
Device: DE_KN_residential1_washing_machine, is_flexible: True

Processing day: 2015-05-22
Battery available with capacity: 10.0 kWh, current SOC: 7.0 kWh
  DE_KN_residential1_dishwasher: Found 0 hours with consumption > 0
  DE_KN_residential1_freezer: Found 0 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0
  DE_KN_residential1_washing_machine: Found 0 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  DE_KN_residential1_dishwasher: Skipping optimization (not flexible or no consumption)
  DE_KN_residential1_freezer: Skipping optimization (not flexible or no consumption)
  DE_KN_residential1_heat_pump: Creating shift variables
    Max shift hours: 6
    Price range: 0.0559 (min=-0.0050, max=0.0510)
    Hours with consumption: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    Created 270 shift variables
  DE_KN_residential1_washing_machine: Skipping optimization (not flexible or no consumption)

Enforcing building load constraints...
Added 642 constraints in total

Objective function has 373 cost terms
Solving problem with 541 variables and 642 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -183.74536457908442
Day 2015-05-22: Costs evaluated and stored using solver objective value: -183.74536457908442

Reconstructing optimized schedules...
  DE_KN_residential1_heat_pump: Processing optimal solution
    Shift from hour 0 to hour 3: 1.0000 * 0.2700 = 0.2700
    Shift from hour 1 to hour 3: 1.0000 * 0.0200 = 0.0200
    Shift from hour 2 to hour 3: 1.0000 * 0.0090 = 0.0090
    Shift from hour 3 to hour 3: 1.0000 * 0.0120 = 0.0120
    Shift from hour 4 to hour 3: 1.0000 * 0.0200 = 0.0200
    Shift from hour 5 to hour 3: 1.0000 * 0.3470 = 0.3470
    Shift from hour 6 to hour 3: 1.0000 * 1.6440 = 1.6440
    Shift from hour 7 to hour 3: 1.0000 * 2.0790 = 2.0790
    Shift from hour 8 to hour 3: 1.0000 * 0.3400 = 0.3400
    Shift from hour 9 to hour 3: 1.0000 * 0.0090 = 0.0090
    Shift from hour 10 to hour 4: 1.0000 * 0.5900 = 0.5900
    Shift from hour 11 to hour 5: 1.0000 * 0.2800 = 0.2800
    Shift from hour 12 to hour 6: 1.0000 * 0.0090 = 0.0090
    Shift from hour 13 to hour 11: 1.0000 * 0.0220 = 0.0220
    Shift from hour 14 to hour 11: 1.0000 * 0.3400 = 0.3400
    Shift from hour 15 to hour 11: 1.0000 * 0.0090 = 0.0090
    Shift from hour 16 to hour 11: 1.0000 * 0.0100 = 0.0100
    Shift from hour 17 to hour 11: 1.0000 * 0.0200 = 0.0200
    Shift from hour 18 to hour 13: 1.0000 * 0.3810 = 0.3810
    Shift from hour 19 to hour 13: 1.0000 * 0.6820 = 0.6820
    Shift from hour 20 to hour 14: 1.0000 * 0.2930 = 0.2930
    Shift from hour 21 to hour 15: 1.0000 * 0.9710 = 0.9710
    Shift from hour 22 to hour 16: 1.0000 * 0.3510 = 0.3510
    Shift from hour 23 to hour 17: 1.0000 * 0.7220 = 0.7220
    Applied 24 shifts
    Original: [0.27  0.02  0.009 0.012 0.02  0.347 1.644 2.079 0.34  0.009 0.59  0.28
 0.009 0.022 0.34  0.009 0.01  0.02  0.381 0.682 0.293 0.971 0.351 0.722]
    Optimized: [0.    0.    0.    4.75  0.59  0.28  0.009 0.    0.    0.    0.    0.401
 0.    1.063 0.293 0.971 0.351 0.722 0.    0.    0.    0.    0.    0.   ]
    Difference magnitude: 16.950000
    Index 0, Hour 0: Changed from 0.270000 to 0.000000
    Index 1, Hour 1: Changed from 0.020000 to 0.000000
    Index 2, Hour 2: Changed from 0.009000 to 0.000000
    Index 3, Hour 3: Changed from 0.012000 to 4.750000
    Index 4, Hour 4: Changed from 0.020000 to 0.590000
    Index 5, Hour 5: Changed from 0.347000 to 0.280000
    Index 6, Hour 6: Changed from 1.644000 to 0.009000
    Index 7, Hour 7: Changed from 2.079000 to 0.000000
    Index 8, Hour 8: Changed from 0.340000 to 0.000000
    Index 9, Hour 9: Changed from 0.009000 to 0.000000
    Index 10, Hour 10: Changed from 0.590000 to 0.000000
    Index 11, Hour 11: Changed from 0.280000 to 0.401000
    Index 12, Hour 12: Changed from 0.009000 to 0.000000
    Index 13, Hour 13: Changed from 0.022000 to 1.063000
    Index 14, Hour 14: Changed from 0.340000 to 0.293000
    Index 15, Hour 15: Changed from 0.009000 to 0.971000
    Index 16, Hour 16: Changed from 0.010000 to 0.351000
    Index 17, Hour 17: Changed from 0.020000 to 0.722000
    Index 18, Hour 18: Changed from 0.381000 to 0.000000
    Index 19, Hour 19: Changed from 0.682000 to 0.000000
    Index 20, Hour 20: Changed from 0.293000 to 0.000000
    Index 21, Hour 21: Changed from 0.971000 to 0.000000
    Index 22, Hour 22: Changed from 0.351000 to 0.000000
    Index 23, Hour 23: Changed from 0.722000 to 0.000000

Processing battery optimization results...
  Hour 0: SOC=7.00, Charge=0.36, Discharge=0.00
  Hour 1: SOC=7.00, Charge=0.36, Discharge=0.00
  Hour 2: SOC=7.72, Charge=1.08, Discharge=0.00
  Hour 3: SOC=9.36, Charge=2.00, Discharge=0.00
  Hour 4: SOC=10.00, Charge=1.00, Discharge=0.00
  Hour 5: SOC=10.00, Charge=0.00, Discharge=0.00
  Hour 6: SOC=9.36, Charge=0.00, Discharge=1.00
  Hour 7: SOC=7.72, Charge=0.00, Discharge=2.00
  Hour 8: SOC=5.08, Charge=0.00, Discharge=3.00
  Hour 9: SOC=2.84, Charge=0.00, Discharge=2.60
  Hour 10: SOC=1.60, Charge=0.00, Discharge=1.60
  Hour 11: SOC=1.36, Charge=0.00, Discharge=0.60
  Hour 12: SOC=1.76, Charge=0.40, Discharge=0.00
  Hour 13: SOC=3.16, Charge=1.40, Discharge=0.00
  Hour 14: SOC=5.56, Charge=2.40, Discharge=0.00
  Hour 15: SOC=7.84, Charge=2.64, Discharge=0.00
  Hour 16: SOC=9.48, Charge=1.64, Discharge=0.00
  Hour 17: SOC=10.00, Charge=0.64, Discharge=0.00
  Hour 18: SOC=10.00, Charge=0.00, Discharge=0.36
  Hour 19: SOC=9.00, Charge=0.00, Discharge=1.36
  Hour 20: SOC=7.00, Charge=0.00, Discharge=2.36
  Hour 21: SOC=4.36, Charge=0.00, Discharge=3.00
  Hour 22: SOC=2.36, Charge=0.00, Discharge=2.36
  Hour 23: SOC=1.36, Charge=0.00, Discharge=1.36
  Updated battery agent: SOC=1.36, day charge=13.92, day discharge=21.60

Finalizing optimization...
DE_KN_residential1_dishwasher: Difference between original and optimized: 0.000000
DE_KN_residential1_freezer: Difference between original and optimized: 0.000000
DE_KN_residential1_heat_pump: Difference between original and optimized: 16.950000
DE_KN_residential1_washing_machine: Difference between original and optimized: 0.000000

Centralized optimization complete with battery modeling!

Calculating and storing optimization costs...
DE_KN_residential1_dishwasher: Original=$0.00, Optimized=$0.00, Savings=$0.00
DE_KN_residential1_freezer: Original=$0.00, Optimized=$0.00, Savings=$0.00
DE_KN_residential1_heat_pump: Original=$0.28, Optimized=$0.08, Savings=$0.20
DE_KN_residential1_washing_machine: Original=$0.00, Optimized=$0.00, Savings=$0.00
  Centralized total cost: €-0.4812
✓ Created 4 FlexibleDevice agents from DuckDB
  Running decentralized optimization...
    Device DE_KN_residential1_dishwasher: €0.0000
    Device DE_KN_residential1_freezer: €0.0000
    Device DE_KN_residential1_heat_pump: €0.0633
    Device DE_KN_residential1_washing_machine: €0.0073
    Battery SOC maintained: 1.36 kWh
  Decentralized total cost: €0.0706
  Running centralized optimization...
================================================================================
STARTING CENTRALIZED OPTIMIZATION
================================================================================
Found 1 unique days to optimize
Device: DE_KN_residential1_dishwasher, is_flexible: True
Device: DE_KN_residential1_freezer, is_flexible: True
Device: DE_KN_residential1_heat_pump, is_flexible: True
Device: DE_KN_residential1_washing_machine, is_flexible: True

Processing day: 2015-05-23
Battery available with capacity: 9.96448 kWh, current SOC: 1.36 kWh
  DE_KN_residential1_dishwasher: Found 1 hours with consumption > 0
  DE_KN_residential1_freezer: Found 0 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0
  DE_KN_residential1_washing_machine: Found 7 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  DE_KN_residential1_dishwasher: Creating shift variables
    Max shift hours: 6
    Price range: 0.0314 (min=-0.0008, max=0.0306)
    Hours with consumption: [6]
    Created 13 shift variables
  DE_KN_residential1_freezer: Skipping optimization (not flexible or no consumption)
  DE_KN_residential1_heat_pump: Creating shift variables
    Max shift hours: 6
    Price range: 0.0314 (min=-0.0008, max=0.0306)
    Hours with consumption: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    Created 270 shift variables
  DE_KN_residential1_washing_machine: Creating shift variables
    Max shift hours: 6
    Price range: 0.0314 (min=-0.0008, max=0.0306)
    Hours with consumption: [ 1 11 12 13 14 15 16]
    Created 86 shift variables

Enforcing building load constraints...
Added 650 constraints in total

Objective function has 472 cost terms
Solving problem with 640 variables and 650 constraints...
Writing LP file to d:\Kenneth - TU Eindhoven\Jads\Graduation Project 2024-2025\ems_project\ems-optimization-pipeline\temp_optimizations\debug_optimization.lp for debugging
Attempting to solve with CBC CMD...
Optimization status: Optimal
Solver objective value: -188.55962831015557
Day 2015-05-23: Costs evaluated and stored using solver objective value: -188.55962831015557

Reconstructing optimized schedules...
  DE_KN_residential1_dishwasher: Processing optimal solution
    Shift from hour 6 to hour 7: 1.0000 * 0.0010 = 0.0010
    Applied 1 shifts
    Original: [0.    0.    0.    0.    0.    0.    0.001 0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
    Optimized: [0.    0.    0.    0.    0.    0.    0.    0.001 0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
    Difference magnitude: 0.002000
  DE_KN_residential1_heat_pump: Processing optimal solution
    Shift from hour 0 to hour 6: 1.0000 * 0.4200 = 0.4200
    Shift from hour 1 to hour 7: 1.0000 * 0.0100 = 0.0100
    Shift from hour 2 to hour 7: 1.0000 * 0.0100 = 0.0100
    Shift from hour 3 to hour 7: 1.0000 * 0.0190 = 0.0190
    Shift from hour 4 to hour 7: 1.0000 * 0.0120 = 0.0120
    Shift from hour 5 to hour 7: 1.0000 * 0.0700 = 0.0700
    Shift from hour 6 to hour 7: 1.0000 * 1.2480 = 1.2480
    Shift from hour 7 to hour 7: 1.0000 * 0.8210 = 0.8210
    Shift from hour 8 to hour 7: 1.0000 * 0.0210 = 0.0210
    Shift from hour 9 to hour 15: 1.0000 * 0.4300 = 0.4300
    Shift from hour 10 to hour 16: 1.0000 * 0.0090 = 0.0090
    Shift from hour 11 to hour 16: 1.0000 * 0.0100 = 0.0100
    Shift from hour 12 to hour 16: 1.0000 * 0.0100 = 0.0100
    Shift from hour 13 to hour 16: 1.0000 * 0.0200 = 0.0200
    Shift from hour 14 to hour 16: 1.0000 * 0.0090 = 0.0090
    Shift from hour 15 to hour 16: 1.0000 * 0.0120 = 0.0120
    Shift from hour 16 to hour 16: 1.0000 * 0.2380 = 0.2380
    Shift from hour 17 to hour 16: 1.0000 * 0.4010 = 0.4010
    Shift from hour 18 to hour 16: 1.0000 * 0.3490 = 0.3490
    Shift from hour 19 to hour 16: 1.0000 * 0.4100 = 0.4100
    Shift from hour 20 to hour 16: 1.0000 * 0.6610 = 0.6610
    Shift from hour 21 to hour 16: 1.0000 * 0.4290 = 0.4290
    Shift from hour 22 to hour 16: 1.0000 * 0.2500 = 0.2500
    Shift from hour 23 to hour 17: 1.0000 * 0.2620 = 0.2620
    Applied 24 shifts
    Original: [0.42  0.01  0.01  0.019 0.012 0.07  1.248 0.821 0.021 0.43  0.009 0.01
 0.01  0.02  0.009 0.012 0.238 0.401 0.349 0.41  0.661 0.429 0.25  0.262]
    Optimized: [0.    0.    0.    0.    0.    0.    0.42  2.211 0.    0.    0.    0.
 0.    0.    0.    0.43  2.808 0.262 0.    0.    0.    0.    0.    0.   ]
    Difference magnitude: 8.756000
    Index 0, Hour 0: Changed from 0.420000 to 0.000000
    Index 1, Hour 1: Changed from 0.010000 to 0.000000
    Index 2, Hour 2: Changed from 0.010000 to 0.000000
    Index 3, Hour 3: Changed from 0.019000 to 0.000000
    Index 4, Hour 4: Changed from 0.012000 to 0.000000
    Index 5, Hour 5: Changed from 0.070000 to 0.000000
    Index 6, Hour 6: Changed from 1.248000 to 0.420000
    Index 7, Hour 7: Changed from 0.821000 to 2.211000
    Index 8, Hour 8: Changed from 0.021000 to 0.000000
    Index 9, Hour 9: Changed from 0.430000 to 0.000000
    Index 10, Hour 10: Changed from 0.009000 to 0.000000
    Index 11, Hour 11: Changed from 0.010000 to 0.000000
    Index 12, Hour 12: Changed from 0.010000 to 0.000000
    Index 13, Hour 13: Changed from 0.020000 to 0.000000
    Index 14, Hour 14: Changed from 0.009000 to 0.000000
    Index 15, Hour 15: Changed from 0.012000 to 0.430000
    Index 16, Hour 16: Changed from 0.238000 to 2.808000
    Index 17, Hour 17: Changed from 0.401000 to 0.262000
    Index 18, Hour 18: Changed from 0.349000 to 0.000000
    Index 19, Hour 19: Changed from 0.410000 to 0.000000
    Index 20, Hour 20: Changed from 0.661000 to 0.000000
    Index 21, Hour 21: Changed from 0.429000 to 0.000000
    Index 22, Hour 22: Changed from 0.250000 to 0.000000
    Index 23, Hour 23: Changed from 0.262000 to 0.000000
  DE_KN_residential1_washing_machine: Processing optimal solution
    Shift from hour 1 to hour 7: 1.0000 * 0.0010 = 0.0010
    Shift from hour 11 to hour 16: 1.0000 * 0.5930 = 0.5930
    Shift from hour 12 to hour 16: 1.0000 * 0.2130 = 0.2130
    Shift from hour 13 to hour 16: 1.0000 * 0.3270 = 0.3270
    Shift from hour 14 to hour 16: 1.0000 * 0.0820 = 0.0820
    Shift from hour 15 to hour 16: 1.0000 * 0.0030 = 0.0030
    Shift from hour 16 to hour 16: 1.0000 * 0.0030 = 0.0030
    Applied 7 shifts
    Original: [0.    0.001 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.593
 0.213 0.327 0.082 0.003 0.003 0.    0.    0.    0.    0.    0.    0.   ]
    Optimized: [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 1.000e-03 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 1.221e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 0.000e+00]
    Difference magnitude: 2.438000
    Index 11, Hour 11: Changed from 0.593000 to 0.000000
    Index 12, Hour 12: Changed from 0.213000 to 0.000000
    Index 13, Hour 13: Changed from 0.327000 to 0.000000
    Index 14, Hour 14: Changed from 0.082000 to 0.000000
    Index 15, Hour 15: Changed from 0.003000 to 0.000000
    Index 16, Hour 16: Changed from 0.003000 to 1.221000

Processing battery optimization results...
  Hour 0: SOC=1.30, Charge=0.00, Discharge=0.42
  Hour 1: SOC=1.00, Charge=0.00, Discharge=0.30
  Hour 2: SOC=1.00, Charge=0.00, Discharge=0.00
  Hour 3: SOC=1.64, Charge=1.00, Discharge=0.00
  Hour 4: SOC=3.28, Charge=2.00, Discharge=0.00
  Hour 5: SOC=5.92, Charge=3.00, Discharge=0.00
  Hour 6: SOC=8.27, Charge=2.71, Discharge=0.00
  Hour 7: SOC=9.62, Charge=1.71, Discharge=0.00
  Hour 8: SOC=9.96, Charge=0.71, Discharge=0.00
  Hour 9: SOC=9.67, Charge=0.00, Discharge=0.29
  Hour 10: SOC=8.38, Charge=0.00, Discharge=1.29
  Hour 11: SOC=6.14, Charge=0.00, Discharge=2.24
  Hour 12: SOC=4.90, Charge=0.00, Discharge=1.24
  Hour 13: SOC=4.65, Charge=0.00, Discharge=0.24
  Hour 14: SOC=5.05, Charge=0.76, Discharge=0.00
  Hour 15: SOC=6.45, Charge=1.76, Discharge=0.00
  Hour 16: SOC=8.62, Charge=2.53, Discharge=0.00
  Hour 17: SOC=9.79, Charge=1.53, Discharge=0.00
  Hour 18: SOC=9.96, Charge=0.53, Discharge=0.00
  Hour 19: SOC=9.86, Charge=0.00, Discharge=0.47
  Hour 20: SOC=8.75, Charge=0.00, Discharge=1.47
  Hour 21: SOC=6.64, Charge=0.00, Discharge=2.47
  Hour 22: SOC=4.00, Charge=0.00, Discharge=3.00
  Hour 23: SOC=1.36, Charge=0.00, Discharge=3.00
  Updated battery agent: SOC=1.36, day charge=18.24, day discharge=16.44

Finalizing optimization...
DE_KN_residential1_dishwasher: Difference between original and optimized: 0.002000
DE_KN_residential1_freezer: Difference between original and optimized: 0.000000
DE_KN_residential1_heat_pump: Difference between original and optimized: 8.756000
DE_KN_residential1_washing_machine: Difference between original and optimized: 2.438000

Centralized optimization complete with battery modeling!

Calculating and storing optimization costs...
DE_KN_residential1_dishwasher: Original=$0.00, Optimized=$-0.00, Savings=$0.00
DE_KN_residential1_freezer: Original=$0.00, Optimized=$0.00, Savings=$0.00
DE_KN_residential1_heat_pump: Original=$0.06, Optimized=$-0.00, Savings=$0.07
DE_KN_residential1_washing_machine: Original=$0.01, Optimized=$-0.00, Savings=$0.01
  Centralized total cost: €-0.2384
✓ Created 4 FlexibleDevice agents from DuckDB
  Running decentralized optimization...
    Device DE_KN_residential1_dishwasher: €0.0212
    Device DE_KN_residential1_freezer: €0.0000
    Device DE_KN_residential1_heat_pump: €0.0672
    Device DE_KN_residential1_washing_machine: €0.0000
    Battery SOC maintained: 1.36 kWh
  Decentralized total cost: €0.0885
  Running centralized optimization...
================================================================================
STARTING CENTRALIZED OPTIMIZATION
================================================================================
Found 1 unique days to optimize
Device: DE_KN_residential1_dishwasher, is_flexible: True
Device: DE_KN_residential1_freezer, is_flexible: True
Device: DE_KN_residential1_heat_pump, is_flexible: True
Device: DE_KN_residential1_washing_machine, is_flexible: True

Processing day: 2015-05-24
Battery available with capacity: 9.929809471999999 kWh, current SOC: 1.36 kWh
  DE_KN_residential1_dishwasher: Found 4 hours with consumption > 0
  DE_KN_residential1_freezer: Found 0 hours with consumption > 0
  DE_KN_residential1_heat_pump: Found 24 hours with consumption > 0
  DE_KN_residential1_washing_machine: Found 2 hours with consumption > 0
Setting up battery variables and constraints...

Creating shift variables...
  DE_KN_residential1_dishwasher: Creating shift variables
    Max shift hours: 6
    Price range: 0.0640 (min=-0.0230, max=0.0409)
    Hours with consumption: [ 7 12 13 14]
    Created 52 shift variables
  DE_KN_residential1_freezer: Skipping optimization (not flexible or no consumption)
  DE_KN_residential1_heat_pump: Creating shift variables
    Max shift hours: 6
    Price range: 0.0640 (min=-0.0230, max=0.0409)
    Hours with consumption: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    Created 270 shift variables
  DE_KN_residential1_washing_machine: Creating shift variables
    Max shift hours: 6

,building,battery,baseline_cost_€,decentralised_cost_€,centralised_cost_€,savings_dec_%,savings_cent_%,pv_util_base_%,pv_util_dec_%,pv_util_cent_%,centralised_failures,solver_time_s
0,DE_KN_residential1,off,4.0944,0.1471,0.0126,96.4061,99.6922,0.0,0.0,0.0,0,1.1591
1,DE_KN_residential1,on,4.0944,0.1471,-0.4270,96.4061,110.4302,0.0,0.0,0.0,0,3.6065
2,DE_KN_residential2,off,8.6930,0.0691,0.0803,99.2050,99.0758,0.0,0.0,0.0,0,1.2658
3,DE_KN_residential2,on,8.6930,0.0812,-0.2679,99.0659,103.0816,0.0,0.0,0.0,0,9.1906
4,DE_KN_residential3,off,2.8895,0.2914,0.2914,89.9159,89.9159,0.0,0.0,0.0,0,1.6295
5,DE_KN_residential3,on,2.8895,0.2914,0.0655,89.9159,97.7321,0.0,0.0,0.0,0,13.4166
6,DE_KN_residential4,off,6.4973,0.0481,0.0505,99.2600,99.2229,0.0,0.0,0.0,0,1.8189
7,DE_KN_residential4,on,6.4973,0.0520,-0.2551,99.1998,103.9269,0.0,0.0,0.0,0,10.6393
8,DE_KN_residential5,off,3.7915,0.1001,0.0997,97.3605,97.3698,0.0,0.0,0.0,0,1.1133
9,DE_KN_residential5,on,3.7915,0.1215,-0.2611,96.7960,106.8878,0.0,0.0,0.0,0,10.2737
10,DE_KN_residential6,off,4.4279,0.0431,0.0451,99.0273,98.9809,0.0,0.0,0.0,0,1.3235
11,DE_KN_residential6,on,4.4279,0.0504,-0.5560,98.8608,112.5565,0.0,0.0,0.0,0,10.2677

In [ ]:
# ──────────────────────────────────────────────────────────────
# QUICK DIAGNOSTIC – do my parquet files actually exist & hold data?
# Run this cell while your CWD is  …/ems-optimization-pipeline/notebooks/
# ──────────────────────────────────────────────────────────────
from pathlib import Path
import pandas as pd

data_dir = Path("data")
rows = []

for pq_file in sorted(data_dir.glob("*_processed_data.parquet")):
    bid = pq_file.name.replace("_processed_data.parquet", "")
    rows.append({
        "building_id": bid,
        "repr(bid)":   repr(bid),           # reveals hidden \n, \t, spaces…
        "exists":      pq_file.exists(),
        "size_B":      pq_file.stat().st_size if pq_file.exists() else None,
    })

probe_tbl = pd.DataFrame(rows).sort_values("building_id").reset_index(drop=True)
display(probe_tbl)

          building_id             repr(bid)  exists   size_B
0   DE_KN_industrial3   'DE_KN_industrial3'    True  1446093
1  DE_KN_residential1  'DE_KN_residential1'    True  1035737
2  DE_KN_residential2  'DE_KN_residential2'    True  1119168
3  DE_KN_residential3  'DE_KN_residential3'    True  1726998
4  DE_KN_residential4  'DE_KN_residential4'    True  1187468
5  DE_KN_residential5  'DE_KN_residential5'    True   990867
6  DE_KN_residential6  'DE_KN_residential6'    True  1042138

In [ ]:
from pathlib import Path
BUILDINGS = [
    p.name.replace("_processed_data.parquet", "").strip()
    for p in Path("data").glob("*_processed_data.parquet")
]
print("✓ BUILDINGS =", BUILDINGS)

✓ BUILDINGS = ['DE_KN_industrial3', 'DE_KN_residential1', 'DE_KN_residential2', 'DE_KN_residential3', 'DE_KN_residential4', 'DE_KN_residential5', 'DE_KN_residential6']